### DISCUSSION TITLE
Changing the light hook

### DISCUSSION THREAD

**Discussion by vandalon** [EPMatt/awesome-ha-blueprints#31] [General]
Hi,

I have this idea I would like to pitch to you about the light hook in combination with the E1744 (symfonisk controller).

- Turning left/right de/increases light brightness
- single click will put the hook in color/color_temp mode
- now when you rotate left/right the color/color_temp will change instead of the brightness.
- after some time (configurable) without any rotation or when doing a single press the hook goes back to normal mode.
- double press toggles the light/on off (I choose double press for this and single press for the mode switch because it sometimes happens to me that i want to do double press, but only press once and then the lights turn off). 
- triple press can be either some custom command or maybe go directly to full brightness with a certain color_temp.
  or it can switch to audio mode so that the controller turns into a volume controller for a period of time, just as with the color/color_temp mode.

as an extra i would make a "confirmation" action (configurable) so that one can set an action when switching mode. (could for example be a short light blink). 

What do you think? Is this a good thing to build in the current light hook or should I maybe create a new hook that does this?

**Comment by EPMatt** [comment]
Hi @vandalon,

very interesting idea, it might be useful for implementing a really advanced light control with such a simple controller. I can see this could be applied also to other controllers as well (such as the E1812, which is currently pretty limited regarding light control).

> ...or it can switch to audio mode so that the controller turns into a volume controller for a period of time, just as with the color/color_temp mode.

I'd personally prefer not to mix light and audio control in a single Hook, since this could become way too complex.

Just brainstorming a couple of ideas:

* We can add an alternative mapping for the E1744 to the Light Hook. Actually the feature to have multiple mappings for a single controller was proposed in #8, and I think it could be really useful: thinking about the Media Player Hook for example, not every media player has the same actions, so a user might want to use a different mapping which better suits to its media device.

* We could add a way to route events to a specific Hook, Controller-side. This could enable to cycle through different Hooks and implement something similar to what you proposed (ie. moving to the Media Player Hook, then moving back to the Light Hook via a specific controller action). By the way I'd leave this feature out for now since it probably requires some breaking changes for Controller blueprints, and would require users to rewrite their automation config. :)

**Comment by vandalon** [comment]
I made an automation based on the E1714 controller blueprint. I'm sharing it here just to show you what I did :)

```
- id: '1617823061190'
  alias: Controller - WoonkamerDimmerTest
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1744.yaml
    input:
      integration: deCONZ
      rotate_right_loop: true
      rotate_left_loop: true
      helper_last_controller_event: input_text.ikea_dimmer_test
      action_rotate_left:
      - choose:
        - conditions:
          - condition: template
            value_template: '{{ "color_temp" in states("input_text.woonkamer_dimmer_mode")
              }}'
          sequence:
          - service: light.turn_on
            entity_id: light.woonkamer
            data:
              transition: 0.35
              color_temp: '{{ [state_attr("light.woonkamer","color_temp")|int - 20,
                300]|max }}'
        - conditions:
          - condition: template
            value_template: '{{ "audio" in states("input_text.woonkamer_dimmer_mode")
              }}'
          sequence:
          - service: media_player.volume_set
            entity_id: media_player.woonkamer
            data:
              volume_level: '{{ [ state_attr("media_player.woonkamer", "volume_level")-0.02,
                0 ] | max  }}'
        default:
        - service: light.turn_on
          target:
            entity_id: light.woonkamer
          data:
            transition: 0.35
            brightness_step: -15
      - delay:
          hours: 0
          minutes: 0
          seconds: 0
          milliseconds: 250
      action_rotate_left_stop:
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - service: input_text.set_value
        target:
          entity_id: input_text.woonkamer_dimmer_mode
        data:
          value: default
      action_rotate_right:
      - choose:
        - conditions:
          - condition: template
            value_template: '{{ "color_temp" in states("input_text.woonkamer_dimmer_mode")
              }}'
          sequence:
          - service: light.turn_on
            entity_id: light.woonkamer
            data:
              transition: 0.35
              color_temp: '{{ [state_attr("light.woonkamer","color_temp")|int + 20,
                500]|min }}'
        - conditions:
          - condition: template
            value_template: '{{ "audio" in states("input_text.woonkamer_dimmer_mode")
              }}'
          sequence:
          - service: media_player.volume_set
            entity_id: media_player.woonkamer
            data:
              volume_level: '{{ [ state_attr("media_player.woonkamer", "volume_level")+0.02,
                0.8 ] | min  }}'
        default:
        - service: light.turn_on
          target:
            entity_id: light.woonkamer
          data:
            transition: 0.35
            brightness_step: 15
      - delay:
          hours: 0
          minutes: 0
          seconds: 0
          milliseconds: 250
      action_rotate_right_stop:
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - service: input_text.set_value
        target:
          entity_id: input_text.woonkamer_dimmer_mode
        data:
          value: default
      debounce_delay: 50
      action_click_double:
      - choose:
        - conditions:
          - condition: template
            value_template: '{{ "audio" not in states("input_text.woonkamer_dimmer_mode")
              }}'
          sequence:
          - service: input_text.set_value
            entity_id: input_text.woonkamer_dimmer_mode
            data:
              value: audio
          - service: light.toggle
            entity_id: light.lamp_naast_de_trap
          - delay:
              milliseconds: 200
          - service: light.toggle
            entity_id: light.lamp_naast_de_trap
          - delay:
              milliseconds: 200
          - service: light.toggle
            entity_id: light.lamp_naast_de_trap
          - delay:
              milliseconds: 200
          - service: light.toggle
            entity_id: light.lamp_naast_de_trap
          - delay:
              seconds: 5
          - service: input_text.set_value
            entity_id: input_text.woonkamer_dimmer_mode
            data:
              value: default
          - service: light.toggle
            target:
              entity_id: light.lamp_naast_de_trap
          - delay:
              milliseconds: 500
          - service: light.toggle
            target:
              entity_id: light.lamp_naast_de_trap
        default:
        - service: input_text.set_value
          entity_id: input_text.woonkamer_dimmer_mode
          data:
            value: default
        - service: light.toggle
          target:
            entity_id: light.lamp_naast_de_trap
        - delay:
            milliseconds: 500
        - service: light.toggle
          target:
            entity_id: light.lamp_naast_de_trap
      action_click_short:
      - choose:
        - conditions:
          - condition: template
            value_template: '{{ "color_temp" not in states("input_text.woonkamer_dimmer_mode")
              }}'
          sequence:
          - service: input_text.set_value
            target:
              entity_id: input_text.woonkamer_dimmer_mode
            data:
              value: color_temp
          - service: light.toggle
            target:
              entity_id: light.lamp_naast_de_trap
          - delay:
              milliseconds: 200
          - service: light.toggle
            target:
              entity_id: light.lamp_naast_de_trap
          - delay:
              seconds: 5
          - service: light.toggle
            target:
              entity_id: light.lamp_naast_de_trap
          - delay:
              milliseconds: 500
          - service: light.toggle
            target:
              entity_id: light.lamp_naast_de_trap
        default:
        - service: input_text.set_value
          entity_id: input_text.woonkamer_dimmer_mode
          data:
            value: default
        - service: light.toggle
          target:
            entity_id: light.lamp_naast_de_trap
        - delay:
            milliseconds: 500
        - service: light.toggle
          target:
            entity_id: light.lamp_naast_de_trap
      controller_device: 8819eee2f90611eab89949a059f8809e
      helper_debounce_delay: 150
```

**Comment by EPMatt** [comment]
Hi @vandalon, thank you for sharing! :) 

Really interesting and advanced usage of just a controller blueprint.

As a little note,  I think you can try to simplify the sequence for making the light flash:
```yaml
- service: light.toggle
  target:
  entity_id: light.lamp_naast_de_trap
- delay:
  milliseconds: 200
- service: light.toggle
  target:
  entity_id: light.lamp_naast_de_trap
- delay:
  seconds: 5
- service: light.toggle
  target:
 entity_id: light.lamp_naast_de_trap
- delay:
  milliseconds: 500
- service: light.toggle
  target:
  entity_id: light.lamp_naast_de_trap
```
You can instead use the `flash` parameter in the `light.turn_on` service. :) 
By the way, really awesome job!
