### DISCUSSION TITLE
How to find e2001 zigbee2mqtt `controller_entity`

### DISCUSSION THREAD

**Discussion by wallzero** [EPMatt/awesome-ha-blueprints#609] [Q&A] [answered]
My e2001 controller is working in Home Assistant with Zigbee2MQTT but I currently use device ID's:
```
alias: Bedroom Switch Turn Down
description: ""
trigger:
  - platform: device
    domain: mqtt
    device_id: abcdefg1234567
    type: action
    subtype: "off"
    discovery_id: 0x00abcd123 action_off
condition: []
action:
  - target:
      entity_id:
        - light.bedroom_lamps
    data:
      brightness_step_pct: -6
    action: light.turn_on
mode: single
```

I would like to switch to using the e2001 blueprint but can't figure out how to get the action sensor/`controller_entity` for Zigbee2MQTT devices.
