### ISSUE TITLE
IKEA E1744 - rotary remote controller doesn't process STOP

### ISSUE THREAD

**Issue by thomas-svrts** [EPMatt/awesome-ha-blueprints#104]
Thank you for taking the time to report here! :tada:

**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to process your request more rapidly.

This template should only be used to report a bug with a blueprint. If this is not your case, you can [choose a different issue template](https://github.com/EPMatt/awesome-ha-blueprints/issues/new/choose). If you have a question instead, please open a discussion [here](https://github.com/EPMatt/awesome-ha-blueprints/discussions/new).

\*_=required_

## Bug Details\*

- Blueprint name: Controller IKEA E1744 SYMFONISK Rotary Remote
- Home Assistant Core Version: 2021.6.6
- Home Assistant Installation Type: Home Assistant Docker container

## Description\*
When turning the rotary remote to change volume, the volume keeps going up in an infinite loop.
The stop command is received but never sent to the media player.

## Automation YAML config\*

```yaml
alias: Controller - IKEA E1744 SYMFONISK Rotary Remote
description: ''
use_blueprint:
  path: EPMatt/ikea_e1744.yaml
  input:
    integration: deCONZ
    controller_device: f3b7a964a830dff84b9d310e77514c27
    helper_last_controller_event: input_text.symfonisk_controller_helper
    rotate_left_loop: false
    rotate_right_loop: false
```

```yaml
variables:
  integration: deCONZ
  rotate_left_loop: false
  rotate_left_max_loop_repeats: 500
  rotate_right_loop: false
  rotate_right_max_loop_repeats: 500
  helper_last_controller_event: input_text.symfonisk_controller_helper
  helper_debounce_delay: 0
  integration_id: '{{ integration | lower }}'
  actions_mapping:
    deconz:
      rotate_left:
        - '3001'
      rotate_stop:
        - '3003'
        - '2003'
      rotate_right:
        - '2001'
      click_short:
        - '1002'
      click_double:
        - '1004'
      click_triple:
        - '1005'
    zha:
      rotate_left:
        - move_1_195
      rotate_stop:
        - stop
      rotate_right:
        - move_0_195
      click_short:
        - toggle
      click_double:
        - step_0_1_0
      click_triple:
        - step_1_1_0
    zigbee2mqtt:
      rotate_left:
        - brightness_move_down
      rotate_stop:
        - brightness_stop
      rotate_right:
        - brightness_move_up
      click_short:
        - toggle
      click_double:
        - brightness_step_up
      click_triple:
        - brightness_step_down
  rotate_left: '{{ actions_mapping[integration_id]["rotate_left"] }}'
  rotate_stop: '{{ actions_mapping[integration_id]["rotate_stop"] }}'
  rotate_right: '{{ actions_mapping[integration_id]["rotate_right"] }}'
  click_short: '{{ actions_mapping[integration_id]["click_short"] }}'
  click_double: '{{ actions_mapping[integration_id]["click_double"] }}'
  click_triple: '{{ actions_mapping[integration_id]["click_triple"] }}'
  controller_entity: ''
  controller_device: f3b7a964a830dff84b9d310e77514c27
  controller_id: >-
    {% if integration_id=="zigbee2mqtt" %}{{controller_entity}}{% else
    %}{{controller_device}}{% endif %}
mode: restart
max_exceeded: silent
trigger:
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: ''
  - platform: event
    event_type:
      - zha_event
      - deconz_event
    event_data:
      device_id: f3b7a964a830dff84b9d310e77514c27
condition:
  - condition: and
    conditions:
      - >-
        {%- set trigger_action -%} {%- if integration_id == "zigbee2mqtt" -%} {{
        trigger.event.data.new_state.state }} {%- elif integration_id ==
        "deconz" -%} {{ trigger.event.data.event }} {%- elif integration_id ==
        "zha" -%} {{ trigger.event.data.command }}{{"_" if
        trigger.event.data.args|length > 0}}{{ trigger.event.data.args|join("_")
        }} {%- endif -%} {%- endset -%} {{ trigger_action not in ["","None"] }}
      - >-
        {{ integration_id != "zigbee2mqtt" or trigger.event.data.new_state.state
        != trigger.event.data.old_state.state }}
action:
  - delay:
      milliseconds: 0
  - variables:
      trigger_action: >-
        {%- if integration_id == "zigbee2mqtt" -%} {{
        trigger.event.data.new_state.state }} {%- elif integration_id ==
        "deconz" -%} {{ trigger.event.data.event }} {%- elif integration_id ==
        "zha" -%} {{ trigger.event.data.command }}{{"_" if
        trigger.event.data.args|length > 0}}{{ trigger.event.data.args|join("_")
        }} {%- endif -%}
      trigger_delta: >-
        {{ (as_timestamp(now()) -
        as_timestamp((states(helper_last_controller_event) |
        from_json).last_triggered if helper_last_controller_event is not none
        and (states(helper_last_controller_event) | regex_match("^\{(\".*\":
        \".*\"(, )?)*\}$")) else "1970-01-01 00:00:00")) * 1000 }}
      last_controller_event: >-
        {{ (states(helper_last_controller_event) | from_json).trigger_action if
        helper_last_controller_event is not none and
        (states(helper_last_controller_event) | regex_match("^\{(\".*\":
        \".*\"(, )?)*\}$")) else "" }}
  - service: input_text.set_value
    data:
      entity_id: input_text.symfonisk_controller_helper
      value: >-
        {{ {"trigger_action":trigger_action,"last_triggered":now()|string} |
        to_json }}
  - choose:
      - conditions: '{{ trigger_action | string in rotate_left }}'
        sequence:
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: rotate_left
          - choose:
              - conditions: '{{ rotate_left_loop }}'
                sequence:
                  - repeat:
                      while: '{{ repeat.index < rotate_left_max_loop_repeats | int }}'
                      sequence: []
            default: []
      - conditions:
          - '{{ trigger_action | string in rotate_stop }}'
          - '{{ last_controller_event in rotate_left }}'
        sequence:
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: rotate_left_stop
          - choose:
              - conditions: []
                sequence: []
      - conditions: '{{ trigger_action | string in rotate_right }}'
        sequence:
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: rotate_right
          - choose:
              - conditions: '{{ rotate_right_loop }}'
                sequence:
                  - repeat:
                      while: '{{ repeat.index < rotate_right_max_loop_repeats | int }}'
                      sequence: []
            default: []
      - conditions:
          - '{{ trigger_action | string in rotate_stop }}'
          - '{{ last_controller_event in rotate_right }}'
        sequence:
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: rotate_right_stop
          - choose:
              - conditions: []
                sequence: []
      - conditions: '{{ trigger_action | string in click_short }}'
        sequence:
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: click_short
          - choose:
              - conditions: []
                sequence: []
      - conditions: '{{ trigger_action | string in click_double }}'
        sequence:
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: click_double
          - choose:
              - conditions: []
                sequence: []
      - conditions: '{{ trigger_action | string in click_triple }}'
        sequence:
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: click_triple
          - choose:
              - conditions: []
                sequence: []
id: '1618526457315'
alias: Controller - IKEA E1744 SYMFONISK Rotary Remote
description: ''
```

## To Reproduce\*

Steps to reproduce the issue:

1. turn the button clockwise
2. stop turning

## Expected behavior\*

volume should go up and stops going higher

## Actual Behaviour\*

Volume keeps going to the max

## Additional Details\*

- [ ] I'd like to help developing a fix for this issue.

## Screenshots

<img width="1062" alt="Schermafbeelding 2021-07-04 om 11 14 33" src="https://user-images.githubusercontent.com/81048302/124379777-43d49d80-dcb9-11eb-8155-4eb62e1c52b3.png">
<img width="968" alt="Schermafbeelding 2021-07-04 om 11 15 20" src="https://user-images.githubusercontent.com/81048302/124379781-47682480-dcb9-11eb-80f3-a9b0dd62b965.png">
