### ISSUE TITLE
[SUGGESTION] Cover Hook

### ISSUE THREAD

**Issue by EPMatt** [EPMatt/awesome-ha-blueprints#11]
**Description**

Implement a Hook for controlling covers with any of the supported controllers.

**Implementation**

**Additional Details**

- [ ] I'd like to help developing this blueprint
- [ ] I've found a blueprint/automation not included in this project which achieves the same/similar goal
  - Link to the resources you've found: [Resource name here](https://link-goes-here)

**Additional context**

See #10.

**Comment by thehijacker** [comment]
Hello,

I will test this as soon as I can. In the mean time I kind of redesigned all in my mind. With single 5 button switch I plan to control two shutters. No sure how this will turn out. Need to take it easy so it works at end of WAF will got down again.

Thank you!

Best regards,
Andrej

**Comment by EPMatt** [comment]
You're welcome @thehijacker!

> With single 5 button switch I plan to control two shutters.

That's interesting, we could also provide a special action mapping for the IKEA E1524 which would allow to control two covers with a single controller (Or also provide two different mappings: for example, one which uses the up/down buttons, and the other which uses the left/right buttons).

Have a nice weekend :)

**Comment by thehijacker** [comment]
Checked your hook. Looks great for specific covers. Mine does not know how to do tilt by command. I need to stop it when moving up/down and change position up/down by around 5 to move it opposite way and "tilt".

Still brainstorming this in my mind. Currently I use single button to move one cover up/down by step. I created new input_number with each cover desired strep and I increase/decrease this by left/right single press to move cover down and left/right long press to move up. Example for left cover movement.

```
      action_left_short:
      - service: input_number.decrement
        target:
          entity_id: input_number.left_shutter_desired_position
      - service: cover.set_cover_position
        target:
          entity_id: cover.left_shutter_mqtt
        data_template:
          position: '{{ states(''input_number.left_shutter_desired_position'') | int
            }}'
      action_left_long:
      - service: input_number.increment
        target:
          entity_id: input_number.right_shutter_desired_position
      - service: cover.set_cover_position
        target:
          entity_id: cover.right_shutter_mqtt
        data_template:
          position: '{{ states(''input_number.right_shutter_desired_position'') |
            int }}'
```

But now I have different idea. To use left right only to select which one to "manage".

1. Single left press will change input_text to left cover entity. Single right press will change input_text to right cover entity.
2. With single up and down I would increment/decrement value for currently specific cover by step value. So if I wish to quickly move cover to 50% and if step value is 10 I would need to press single up/down 5 times. Doesn't sound quick unless I disable double clicking. Possible?
3. If I hold up/down it would move the cover to fully up/down.
4. If at any time I press middle button it will stop moving where it is.

How does this sound. Open for better ideas. :)
