### ISSUE TITLE
Improve documentation for Helper - Last Controller Event controller input

### ISSUE THREAD

**Issue by EPMatt** [EPMatt/awesome-ha-blueprints#111]
...
I think the documentation is not clear enough for us newbies. It would be ideal to halt creation of an automation from a blue-print if a required input was not present. I am not experienced enough with HA to know if this is possible.

_Originally posted by @aaronchilcott in https://github.com/EPMatt/awesome-ha-blueprints/issues/100#issuecomment-873804893_

**Comment by EPMatt** [comment]
Hi @aaronchilcott,

do you have any suggestions on how to improve documentation for the Helper - Last Controller Event input?

Regarding your second suggestion, unfortunately as far as I know there's no way to halt automation creation, but we can use the Persistent Notification integration to signal if the configuration for a specific automation is wrong (eg. if the text input helper is missing).

**Comment by aaronchilcott** [comment]
Hi @EPMatt,
I think that people need to be more aware of what is required than what is optional. Presently we have _optional_ fields **explicitly** marked as optional but the _required_ fields are only implicitly marked as such. i.e. Users don't have to think about what is optional because it's visually represented, but users _do_ need to think/abstract the absence of an "(optional)" notation to understand that a field is required. 

In short, I would posit that at a psychological level people are much less inclined to notice the required fields are _required_ .

If this hypothesis is true, then perhaps we could either:
1. Swap the explicit (optional) notation for implicit/absent notation and notate all the require fields with (required) instead
2. Leave the optional notation and add the required notation too.

In one of my PRs' where I have re-written some logic I have updated the input text to match below:

```    
# helpers used to properly recognize the remote button events
    helper_last_controller_event:
      name: (Required) Helper - State container
      description: >-
        A value is required here, without one your automation will not work. You will need to add an input_text
        helper (see: /config/helpers) and then select it for this input.
        This input_text helper will hold state information between events.
      default: ''
      selector:
        entity:
          domain: input_text
```
