### ISSUE TITLE
Light hook - support for adaptive lighting

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [EPMatt/awesome-ha-blueprints#112]
Thank you for taking the time to report here! :tada:

**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to process your request more rapidly.

This template should only be used to propose a new feature or enhancement for an existing blueprint. If this is not your case, you can [choose a different issue template](https://github.com/EPMatt/awesome-ha-blueprints/issues/new/choose). If you have a question instead, please open a discussion [here](https://github.com/EPMatt/awesome-ha-blueprints/discussions/new).

\*_=required_

## Details\*

- Blueprint name: Light hook

## Description\*

I'd like to add support for turning on lights with [adaptive lighting](https://github.com/basnijholt/adaptive-lighting) applied on turning on lights

## Automation YAML config

Adaptive lighting listens for tuning on lights and applies necessary changes, but it leaves a second or two of previous light setting before fix comes in. In order to start light with appropriate settings (so, no lag or wrong light when turning on) You need to execute `light.turn_on` with few templatable params
```yaml
    - service: light.turn_on
      target:
        entity_id: light.all_lights_in_toilet
      data:
        color_temp: >-
          {{ state_attr('switch.adaptive_lighting_toilet', 'color_temp_mired') |int }}
        brightness_pct: >-
          {{ state_attr('switch.adaptive_lighting_toilet', 'brightness_pct') |int }}
```

## Implementation

It would be great to offer another input in hook blueprint- entity of adaptive lighting switch.
If it is provided, use `state_attr` of that switch to set initial lighting values.

## Additional Details\*

- [X] I'd like to help developing this feature/improvement.
- [X] I've found a blueprint/automation not included in this project which achieves the same/similar goal
  - Link to the resources you've found: [Issue on adaptive-lighting](https://github.com/basnijholt/adaptive-lighting/issues/86#issuecomment-775904094)

## Additional context

It would be great to support adaptive-lighting, because getting blasted by 01:00PM light when you go to toilet at 02:30 AM is a little _unpleasant_ experience. Normally I should close my eyes for a second or so, until adaptive lighting changes lighting params. This can be avoided by starting lights properly on turning on.
