### ISSUE TITLE
Enhancement - Hook with selectable media players

### ISSUE THREAD

**Issue by nagyrobi** [EPMatt/awesome-ha-blueprints#116]
### Blueprint name

Media Player Hook for rotary controllers

### Description

Currently the _Controller - IKEA E1744 SYMFONISK Rotary Remote_ together with _Hook - Media Player_ allow controlling only one fixed media player which can be chosen when creating the automation from the blueprint.

It would be nice, with the addition of an `input_select` to pre-select on the fly which media player we want to actually control. This could be useful for multiroom systems which actually appear as different media players for each room, but the user would like to be able to choose that the actual rotary controller would apply to which media player.

### Automation YAML config

```yaml
- service: media_player.volume_up
        entity_id: >
            {% if is_state("input_select.media_players_list", "Room 1") %}
              media_player.sound_room_1
            {%-elif is_state("input_select.media_players_list", "Room 2") %}
              media_player.sound_room_2
            {%-elif is_state("input_select.media_players_list", "Room 3") %}
              media_player.sound_room_3
            {%-elif is_state("input_select.media_players_list", "Room 4") %}
              media_player.sound_room_4
            {%-elif is_state("input_select.media_players_list", "Room 5") %}
              media_player.sound_room_5
            {% endif %}
```

### Additional Details

- [ ] I'd like to help developing this feature/improvement.

**Comment by nagyrobi** [comment]
As a workaround, I made created the same automation using the same controller for all the different rooms, and a manual automation to enable/disable the automations created by the hook blueprint, according to the state of the `input_select` but this is kinda brute-force way to do it:

```yaml
  - id: symfonisk_rotary_select
    alias: Ikea Symfonisk Rotary Selector
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: input_select.media_players_list
    action:
      - service: automation.turn_off
        target:
          entity_id:
            - automation.hook_media_player_ikea_controller_room_1
            - automation.hook_media_player_ikea_controller_room_2
            - automation.hook_media_player_ikea_controller_room_3
            - automation.hook_media_player_ikea_controller_room_4
            - automation.hook_media_player_ikea_controller_room_5
      - service: automation.turn_on
        target:
          entity_id: >
            {% if is_state("input_select.media_players_list", "Room 1") %}
              automation.hook_media_player_ikea_controller_room_1
            {%-elif is_state("input_select.media_players_list", "Room 2") %}
              automation.hook_media_player_ikea_controller_room_2
            {%-elif is_state("input_select.media_players_list", "Room 3") %}
              automation.hook_media_player_ikea_controller_room_3
            {%-elif is_state("input_select.media_players_list", "Room 4") %}
              automation.hook_media_player_ikea_controller_room_4
            {%-elif is_state("input_select.media_players_list", "Room 5") %}
              automation.hook_media_player_ikea_controller_room_5
            {% endif %}

```
