### ISSUE TITLE
Bug - Hook - Media Player immediately errors

### ISSUE THREAD

**Issue by systemcrash** [EPMatt/awesome-ha-blueprints#128]
### Blueprint name

Hooks - Media Player

### Home Assistant Core Version

core-2021.8.7

### Home Assistant Installation Type

Home Assistant Container

### Description

Fresh import of https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/hooks/media_player
If I click on the "Run Actions" button in the created blueprint, it just logs:

```
ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'dict object' has no attribute 'event' when rendering '{{trigger.event.data.action}}'
ERROR (MainThread) [homeassistant.components.automation.hook_media_player] Hook - Media Player: Error executing script. Error rendering template for variables at pos 1: UndefinedError: 'dict object' has no attribute 'event'
ERROR (MainThread) [homeassistant.components.automation.hook_media_player] Error while executing automation automation.hook_media_player: UndefinedError: 'dict object' has no attribute 'event'
```
### Blueprint YAML config
```yaml
id: '1629237320983'
alias: Hook - Media Player
description: ''
use_blueprint:
  path: EPMatt/media_player.yaml
  input:
    controller_device: 9b0d0b0edeea7f06b435eb2c33a301ae
    controller_entity: sensor.ikea_symfonisk_white_power
    controller_model: IKEA E1744 SYMFONISK rotary remote
    media_player: media_player.living_room
    volume_steps_long: 30
```

### Automation YAML config

```yaml
variables:
  controller_model: IKEA E1744 SYMFONISK rotary remote
  volume_steps_short: 10
  volume_steps_long: 30
  media_player: media_player.living_room
  supported_controllers:
    IKEA E1524/E1810 5-Button remote: ikea_e1524_e1810
    IKEA E1743 On/Off Switch & Dimmer: ikea_e1743
    IKEA E1744 SYMFONISK rotary remote: ikea_e1744
    IKEA E1812 Shortcut button: ikea_e1812
    IKEA ICTC-G-1 TRADFRI wireless dimmer: ikea_ictc_g_1
    Osram SMART+ Switch Mini: osram_ac025xx00nj
    Philips Hue Dimmer switch: philips_324131092621
    Philips Hue Smart Button: philips_8718699693985
  controller_mapping:
    ikea_e1524_e1810:
      volume_up: button_up_short
      volume_up_repeat: button_up_long
      volume_down: button_down_short
      volume_down_repeat: button_down_long
      next_track: button_right_short
      prev_track: button_left_short
      stop: button_center_hold
      play_pause: button_center_short
    ikea_e1743:
      volume_up: button_up_short
      volume_up_repeat: button_up_long
      volume_down: button_down_short
      volume_down_repeat: button_down_long
      next_track: button_up_double
      play_pause: button_down_double
    ikea_e1744:
      volume_up_repeat: rotate_right
      volume_down_repeat: rotate_left
      next_track: click_double
      prev_track: click_triple
      play_pause: click_short
    ikea_e1812:
      next_track: button_double
      stop: button_long
      play_pause: button_short
    ikea_ictc_g_1:
      volume_up_repeat: rotate_right
      volume_down_repeat: rotate_left
    osram_ac025xx00nj:
      volume_up: button_up_short
      volume_up_repeat: button_up_long
      next_track: button_up_double
      play_pause: button_click_short
      toggle: button_click_long
      volume_down: button_down_short
      volume_down_repeat: button_down_long
      prev_track: button_down_double
    philips_324131092621:
      play_pause: button_on_short
      stop: button_off_short
      volume_up: button_up_short
      volume_up_repeat: button_up_long
      volume_down: button_down_short
      volume_down_repeat: button_down_long
      next_track: button_on_long
      prev_track: button_off_long
    philips_8718699693985:
      play_pause: button_short
      next_track: button_double
  controller_model_id: '{{ supported_controllers[controller_model] }}'
  volume_up: '{{ controller_mapping[controller_model_id]["volume_up"] | default(None) }}'
  volume_up_repeat: >-
    {{ controller_mapping[controller_model_id]["volume_up_repeat"] |
    default(None) }}
  volume_down: '{{ controller_mapping[controller_model_id]["volume_down"] | default(None) }}'
  volume_down_repeat: >-
    {{ controller_mapping[controller_model_id]["volume_down_repeat"] |
    default(None) }}
  next_track: '{{ controller_mapping[controller_model_id]["next_track"] | default(None) }}'
  prev_track: '{{ controller_mapping[controller_model_id]["prev_track"] | default(None) }}'
  stop: '{{ controller_mapping[controller_model_id]["stop"] | default(None) }}'
  play_pause: '{{ controller_mapping[controller_model_id]["play_pause"] | default(None) }}'
  volume_step_value_short: '{{ 1/volume_steps_short }}'
  volume_step_value_long: '{{ 1/volume_steps_long }}'
mode: restart
max_exceeded: silent
trigger:
  - platform: event
    event_type: ahb_controller_event
    event_data:
      controller: 9b0d0b0edeea7f06b435eb2c33a301ae
  - platform: event
    event_type: ahb_controller_event
    event_data:
      controller: sensor.ikea_symfonisk_white_power
condition: null
action:
  - variables:
      action: '{{trigger.event.data.action}}'
  - choose:
      - conditions: '{{ action == play_pause }}'
        sequence:
          - service: media_player.media_play_pause
            entity_id: media_player.living_room
      - conditions: '{{ action == stop }}'
        sequence:
          - service: media_player.media_stop
            entity_id: media_player.living_room
      - conditions: '{{ action == next_track }}'
        sequence:
          - service: media_player.media_next_track
            entity_id: media_player.living_room
      - conditions: '{{ action == prev_track }}'
        sequence:
          - service: media_player.media_previous_track
            entity_id: media_player.living_room
      - conditions: '{{ action == toggle }}'
        sequence:
          - service: media_player.toggle
            entity_id: media_player.living_room
      - conditions: '{{ action == volume_up }}'
        sequence:
          - choose:
              - conditions: '{{ state_attr(media_player, "volume_level") != None }}'
                sequence:
                  - service: media_player.volume_set
                    entity_id: media_player.living_room
                    data:
                      volume_level: >-
                        {{ [ state_attr(media_player,
                        "volume_level")+volume_step_value_short, 1 ] | min  }}
            default:
              - service: media_player.volume_up
                entity_id: media_player.living_room
      - conditions: '{{ action == volume_down }}'
        sequence:
          - choose:
              - conditions: '{{ state_attr(media_player, "volume_level") != None }}'
                sequence:
                  - service: media_player.volume_set
                    entity_id: media_player.living_room
                    data:
                      volume_level: >-
                        {{ [ state_attr(media_player,
                        "volume_level")-volume_step_value_short, 0 ] | max }}
            default:
              - service: media_player.volume_down
                entity_id: media_player.living_room
      - conditions: '{{ action == volume_up_repeat }}'
        sequence:
          - repeat:
              while: '{{ true }}'
              sequence:
                - choose:
                    - conditions: '{{ state_attr(media_player, "volume_level") != None }}'
                      sequence:
                        - service: media_player.volume_set
                          entity_id: media_player.living_room
                          data:
                            volume_level: >-
                              {{ [ state_attr(media_player,
                              "volume_level")+volume_step_value_long, 1 ] | min 
                              }}
                  default:
                    - service: media_player.volume_up
                      entity_id: media_player.living_room
                - delay:
                    milliseconds: 250
      - conditions: '{{ action == volume_down_repeat }}'
        sequence:
          - repeat:
              while: '{{ true }}'
              sequence:
                - choose:
                    - conditions: '{{ state_attr(media_player, "volume_level") != None }}'
                      sequence:
                        - service: media_player.volume_set
                          entity_id: media_player.living_room
                          data:
                            volume_level: >-
                              {{ [ state_attr(media_player,
                              "volume_level")-volume_step_value_long, 0 ] | max
                              }}
                  default:
                    - service: media_player.volume_down
                      entity_id: media_player.living_room
                - delay:
                    milliseconds: 250
id: '1629237320983'
alias: Hook - Media Player
description: ''
```

### To Reproduce

3. Trigger the automation '....'

### Expected behavior

No error...?

### Actual Behaviour

Only emits error.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
