### ISSUE TITLE
Bug - E1743 automation not triggering on first single click

### ISSUE THREAD

**Issue by FabioEight** [EPMatt/awesome-ha-blueprints#142]
### Blueprint name

IKEA E1743 On/Off Switch & Dimmer

### Home Assistant Core Version

core-2021.9.6

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Ciao,

I'm using the blueprint for E1743 to trigger state change on the IKEA plug (https://www.ikea.com/it/it/p/tradfri-kit-presa-e-telecomando-30364800/), so basically turning on/off a lamp connected to the plug.
I was able to configure the E1743 to simply turn off and on the plug using a single click, but I noticed that sometimes I have to repeat 2-4 times the click in order to change the lamp state.
Link quality of the E1743 is good (255) and it's near the Zigbee IKEA plug (it acts as router), I don't suppose it's a link quality issue.
I'm using zigbee2mqtt. I'm attaching the registry of HA, which shows that the "click" seems to be received by HA, but not processed via automation till the 3rd ON click.
Thanks!

### Automation YAML config

```yaml
alias: IKEA E1743 On/Off Lampada Salone
description: ''
use_blueprint:
  path: EPMatt/ikea_e1743.yaml
  input:
    integration: Zigbee2MQTT
    helper_last_controller_event: input_text.stato_lampada_salone
    action_button_up_short:
      - type: turn_on
        device_id: 746b1c32cdd8959aaa0fedaad8dc7605
        entity_id: switch.lampada_salone
        domain: switch
    action_button_down_short:
      - type: turn_off
        device_id: 746b1c32cdd8959aaa0fedaad8dc7605
        entity_id: switch.lampada_salone
        domain: switch
    controller_entity: sensor.pulsante_ikea_salone_action
```

### To Reproduce

1. Click on/off on the E1743
2. Repeat the click until the plug status change is performed

### Expected behavior

Immediate change of status.

### Actual Behaviour

I need to click on/off 2-3 times before the automation is triggered.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Screenshots

![image](https://user-images.githubusercontent.com/12196008/133253276-7d440d64-b051-410c-84d3-642e26e94428.png)
