### ISSUE TITLE
Bug - Controller + Light Hook: when controlling a Zigbee group (1 entity), Z2M throws warnings

### ISSUE THREAD

**Issue by SHxKM** [EPMatt/awesome-ha-blueprints#157]
### Blueprint name

Controller (Phillips Hue Dimmer Switch) + Light Hook 

### Home Assistant Core Version

2021.10.2

### Home Assistant Installation Type

Home Assistant Operating System

### Description

I'm using a fairly standard combo: 

- Controller (Phillips Hue Dimmer Switch)
- Light Hook

The controlled entity is a Zigbee **group**, called `ensis_group`, it represents two parts of the Phillips Hue Ensis hanging light, the top part, which I called `ensis_top`, and the bottom part, which I called `ensis_main`. I don't think that matters,  but including this information just in case.
When the Controller was set to control `ensis_group`, which is what I want, Zigbee2MQTT would throw a `warn` log on pretty much every action, here's a snippet of such sequence:

> Info: MQTT publish: topic 'zigbee2mqtt/ensis_remote/action', payload 'on-press'
> Debug: Received MQTT message on 'zigbee2mqtt/ensis_group/set' with data '{"state": "ON", "transition": 0.5, "brightness": 254}'
> Debug: Publishing 'set' 'brightness' to 'ensis_group'
> Debug: Ignoring message from coordinator
> Warning: Received message from unsupported device with Zigbee model 'undefined' and manufacturer name 'undefined'
> Warning: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
> Debug: Publishing 'set' 'transition' to 'ensis_group'
> Info MQTT publish: topic 'zigbee2mqtt/ph_ensis_main', payload '{"brightness":254,"color":{"h":32,"hue":32,"s":82,"saturation":82,"x":0.4599,"y":0.4106},"color_mode":"color_temp","color_temp":370,"color_temp_startup":370,"linkquality":247,"state":"ON","update":{"state":"available"},"update_available":true}'

When I adjust the automation to only control either of `ensis_top` and `ensis_main` (both and the only members of `ensis_group`), then no warnings are emitted.

### Automation YAML config

```yaml
- id: 'XXXXX'
  alias: Controller - ensis
  description: ''
  use_blueprint:
    path: EPMatt/philips_324131092621.yaml
    input:
      integration: Zigbee2MQTT
      controller_entity: sensor.ensis_remote_action
      helper_last_controller_event: input_text.test_helper_entity
      action_button_on_double: []
      action_button_off_double: []
      helper_double_press_delay: 500
      action_button_off_short: []
      button_on_double_press: false
- id: 'YYYY'
  alias: Hook - ensis
  description: ''
  use_blueprint:
    path: EPMatt/light.yaml
    input:
      light_color_mode: Hue - Saturation
      controller_entity: sensor.ensis_remote_action
      controller_model: Philips Hue Dimmer switch
      light: light.ensis_group
      on_brightness: 255
      force_brightness: true
      brightness_steps_short: 2
      light_transition: 500
      min_brightness: 120
````
```


### To Reproduce

1. Create an automation with -  Controller (Hue Dimmer Switch)
3. Create an automation with -  `Hook - Light` and set it to control a `light.entity` which represents a Zigbee group
4. Click a button on the Hue Dimmer Switch
5. See error


### Expected behavior

No warnings are emitted by Z2M.

### Actual Behaviour

Warnings are emitted from Z2M.

### Additional Details

- [X] I'd like to help developing a fix for this issue.

### Screenshots

It's flooding the logs **and** the UI:

<img width="1238" alt="Screen Shot 2021-10-14 at 22 49 59" src="https://user-images.githubusercontent.com/6573474/137385877-8ea70140-8c66-4996-918e-acfe9c53f4e5.png">


### Additional context

*Initially* had the Hook configured with a Controller Device until I realize that's not needed (only Controller Entity was).
