### ISSUE TITLE
Bug - Issues with Ikea E1743 and Zigbee2MQTT

### ISSUE THREAD

**Issue by runejuhl** [EPMatt/awesome-ha-blueprints#167]
### Blueprint name

Controller - IKEA E1743 On/Off Switch & Dimmer

### Home Assistant Core Version

2021.10.6

### Home Assistant Installation Type

Home Assistant Container

### Description

When configuring an automation using the E1743 blueprint and Zigbee2MQTT, Home Assistant shows warnings in the log when buttons are pressed:

~~~
2021-10-28 14:35:57 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'
2021-10-28 14:36:01 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'
~~~

Additionally long press and double press actions do not work.

When using the sensor `action` event the automation breaks completely if "Expose up/down button double press event" is enabled. If using the deprecated `click` event single press events work, but actions have a delay matching the configured "Helper - Double Press delay".

I've confirmed this by adding additional actions to long and double presses that send notifications.

### Automation YAML config

```yaml
alias: Bedroom RGBW LED strip
description: ''
use_blueprint:
  path: EPMatt/ikea_e1743.yaml
  input:
    integration: Zigbee2MQTT
    zigbee2mqtt_remote: sensor.0x5c0272fffe44cb9e_click
    action_up_short:
      - type: turn_on
        device_id: d89dbe23b8615d8b0927c053b8adeec7
        entity_id: light.rgbw_led_strip
        domain: light
      - service: notify.matrix_botsen
        data:
          message: turn on led strip
    action_down_short:
      - type: turn_off
        device_id: d89dbe23b8615d8b0927c053b8adeec7
        entity_id: light.rgbw_led_strip
        domain: light
    button_up_long_loop: true
    button_down_long_loop: true
    action_up_long:
      - device_id: d89dbe23b8615d8b0927c053b8adeec7
        domain: light
        entity_id: light.rgbw_led_strip
        type: brightness_increase
      - service: notify.matrix_botsen
        data:
          message: led strip increase
    action_down_long:
      - device_id: d89dbe23b8615d8b0927c053b8adeec7
        domain: light
        entity_id: light.rgbw_led_strip
        type: brightness_decrease
    helper_last_loop_event_input: input_text.bedroom_e1743_led_strip_helper
    action_up_double:
      - service: mqtt.publish
        data:
          payload: '{"color_temp": "500", "brightness": "254"}'
          topic: zigbee2mqtt/0x842e14fffe34429e/set
      - service: notify.matrix_botsen
        data:
          message: double press led strip remote
    button_up_double_press: true
    button_down_double_press: true
    remote: 89f6acce4fc881b810a4b48ab9a25b94
    helper_double_press_delay: 500
```

### To Reproduce

3. Trigger the automation '....'

### Expected behavior

Double and long press actions should work.

### Actual Behaviour

Double and long press actions do not work.

### Additional Details

- [X] I'd like to help developing a fix for this issue.

### Additional context

Thank you for the blueprints @EPMatt!

**Comment by bartjanisse** [comment]
Hi,

I have the same issue as the OP. My Home Assistant automation looks like this:

alias: Controller - IKEA E1743 TRÅDFRI On/Off Switch & Dimmer
description: ''
use_blueprint:
  path: EPMatt/ikea_e1743.yaml
  input:
    controller_entity: sensor.dimmer_switch_hal_action
    helper_last_controller_event: input_text.dimmer_hal
    integration: Zigbee2MQTT
    action_button_up_short:
      - service: light.turn_on
        target:
          entity_id: light.plafondlamp_hal
        data: {}
    action_button_up_long:
      - service: light.turn_on
        data:
          brightness_step_pct: 10
    action_button_down_short:
      - service: light.turn_off
        target:
          entity_id: light.plafondlamp_hal
    button_up_long_loop: true
    action_button_down_long:
      - service: light.turn_on
        data:
          brightness_step_pct: -10
    button_down_long_loop: true

Additionally the helper text (as needed) is showing the right states:

`{
  "trigger_action": "brightness_move_up",
  "last_triggered": "2021-10-31 15:59:39.427424+01:00"
}`
and
`{
  "trigger_action": "brightness_move_down",
  "last_triggered": "2021-10-31 16:00:31.889058+01:00"
}`
and
`{
  "trigger_action": "brightness_stop",
  "last_triggered": "2021-10-31 15:59:45.624972+01:00"
}`

I hope this might be helpfull and that we get this great blueprint to work.

Thanks for any assistance

Regards,
Bart

**Comment by runejuhl** [comment]
I just noticed that my blueprint was ancient -- it seems to be from `6bf93e59a7ae35801be166ee985d97eb05bb0626` or before. Somehow I had got the idea that blueprints were automatically updated.

I'll try upgrading the blueprint and seeing if it works properly.

**Comment by EPMatt** [comment]
Hi @runejuhl,

thank you for your report.

> I just noticed that my blueprint was ancient -- it seems to be from 6bf93e59a7ae35801be166ee985d97eb05bb0626 or before. 

Yeah, I can see from the YAML you provided that the version you're using is quite old. We did many improvements throughout the latest months (including better documentation, debouncing support, etc.). :) 

We also introduced a couple of Breaking Changes to blueprint inputs. I highly suggest you to read the [E1743 Changelog](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e1743#changelog) to see what's changed.

Anyway, I prepared the updated YAML for your automation. Here it is:

```yaml
alias: Bedroom RGBW LED strip
description: ''
use_blueprint:
  path: EPMatt/ikea_e1743.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.0x5c0272fffe44cb9e_entity
    helper_last_controller_event: input_text.bedroom_e1743_led_strip_helper
    action_up_short:
      - type: turn_on
        device_id: d89dbe23b8615d8b0927c053b8adeec7
        entity_id: light.rgbw_led_strip
        domain: light
      - service: notify.matrix_botsen
        data:
          message: turn on led strip
    action_down_short:
      - type: turn_off
        device_id: d89dbe23b8615d8b0927c053b8adeec7
        entity_id: light.rgbw_led_strip
        domain: light
    action_up_long:
      - device_id: d89dbe23b8615d8b0927c053b8adeec7
        domain: light
        entity_id: light.rgbw_led_strip
        type: brightness_increase
      - service: notify.matrix_botsen
        data:
          message: led strip increase
    action_down_long:
      - device_id: d89dbe23b8615d8b0927c053b8adeec7
        domain: light
        entity_id: light.rgbw_led_strip
        type: brightness_decrease
    action_up_double:
      - service: mqtt.publish
        data:
          payload: '{"color_temp": "500", "brightness": "254"}'
          topic: zigbee2mqtt/0x842e14fffe34429e/set
      - service: notify.matrix_botsen
        data:
          message: double press led strip remote
    button_up_long_loop: true
    button_down_long_loop: true
    button_up_double_press: true
    button_down_double_press: true
    helper_double_press_delay: 500
```
I converted a few input names, but kept all your custom actions and configs. I also removed the `remote` input (currently named `controller_device` but not required when using Zigbee2MQTT) and provided the `*_action` entity to the `controller_entity` input.

Let me know if updating the blueprint and using the above YAML to configure the automation solve your issue. If you've any additional questions or doubts I'd be glad to help. :) 

Thanks!

**Comment by rschoultz** [comment]
Not OP, but I have the same issue with the error message in version 2021.10.26 of EPMatt/ikea_e1743 

When "Run Actions", I get this error:
```log
2021-11-28 20:51:12 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'dict object' has no attribute 'event' when rendering '{%- if integration_id == "zigbee2mqtt" -%} {{ trigger.event.data.new_state.state }} {%- elif integration_id == "deconz" -%} {{ trigger.event.data.event }} {%- elif integration_id == "zha" -%} {{ trigger.event.data.command }}{{"_" if trigger.event.data.args|length > 0}}{{ trigger.event.data.args|join("_") }} {%- endif -%}'
2021-11-28 20:51:12 ERROR (MainThread) [homeassistant.components.automation.my_test] My Switch: Error executing script. Error rendering template for variables at pos 2: UndefinedError: 'dict object' has no attribute 'event'
2021-11-28 20:51:12 ERROR (MainThread) [homeassistant.components.automation.my_test] Error while executing automation automation.my_test: UndefinedError: 'dict object' has no attribute 'event'
```

I copied and modified from your message above (note you wrote action_up_long and I figured after a while it should be action_button_up_long). I do get the brightness to increase/decrease despite the problem with the Run Action, but this is as far as I have tested. 

```yaml
alias: My test
description: ''
use_blueprint:
  path: EPMatt/ikea_e1743.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.my_switch_action
    helper_last_controller_event: input_text.my_switch_help
    action_button_up_long:
      - type: brightness_increase
        entity_id: light.my_light_1
        device_id: d89dbe23b8615d8b0927c053b8adeec7
        domain: light
    action_button_down_long:
      - type: brightness_decrease
        entity_id: light.my_light_2
        device_id: d89dbe23b8615d8b0927c053b8adeec7
        domain: light
    button_up_long_loop: true
    button_down_long_loop: true
    button_up_double_press: true
    button_down_double_press: true
    helper_double_press_delay: 500

```

Also, here is a screenshot of what I believe you had requested:

<img width="1339" alt="Screenshot 2021-11-28 at 21 52 07" src="https://user-images.githubusercontent.com/727834/143785693-2496ae4a-77fb-4812-be90-d1a574951107.png">

Many thanks for providing these blueprints! Indeed awesome.
