### ISSUE TITLE
Bug - 

### ISSUE THREAD

**Issue by TiSDStudios** [EPMatt/awesome-ha-blueprints#174]
### Blueprint name

IKEA E1744  to Light Hook

### Home Assistant Core Version

core-2021.11.1

### Home Assistant Installation Type

Home Assistant Core

### Description

I am using Zigbee2MQTT with a IKEA E1744. I've imported both blueprints and made automations pointing at the E1774. 
The controller automation shows it is being triggered but the hook is never triggered. Am I missing some part of the configuration to connect the controller and hook?

### Automation YAML config

```yaml
alias: A Rotary New
description: ''
use_blueprint:
  path: EPMatt/ikea_e1744.yaml
  input:
    integration: Zigbee2MQTT
    controller_device: 7348d0cb86c0f788d4fd188d210f8c27
    controller_entity: sensor.a_client_dimmer_action
    helper_last_controller_event: input_text.a_client_dimmer_input
    action_click_double: []
    action_rotate_left: []
```

### To Reproduce

3. Trigger the automation '....'

### Expected behavior

Rotate dimmer knob and light dims

### Actual Behaviour

Controller shows trigger but light hook shows no action

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
