### ISSUE TITLE
Bug - Atomation based on ikea_e1743 won't run with deConz

### ISSUE THREAD

**Issue by dabrazhe** [EPMatt/awesome-ha-blueprints#185]
### Blueprint name

ikea_e1743 

### Home Assistant Core Version

2021.10.6

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Automation based on ikea_e1743 fails with. 
The helper is defined. 

Error: UndefinedError: 'dict object' has no attribute 'event'

Automation

### Automation YAML config

```yaml
alias: Ikea button1
description: ''
use_blueprint:
  path: EPMatt/ikea_e1743.yaml
  input:
    integration: deCONZ
    controller_device: a5a66e6f2203a1f3f97a8b458b6410f9
    action_button_up_short:
      - type: toggle
        device_id: 41adfd6f383f3056eb901f48a53de44e
        entity_id: light.dininig_room_ambiance_1
        domain: light
    helper_last_controller_event: input_text.tradfri_button
```

### To Reproduce

Create an automation from blueprint using Deconz automation and the open-close button.

Create the text input helper for the state.

### Expected behavior

The automation should trigger the light. 

### Actual Behaviour

Error as above. 

Trace : 

variables:
  trigger_action: >-
    {%- if integration_id == "zigbee2mqtt" -%} {{
    trigger.event.data.new_state.state }} {%- elif integration_id == "deconz"
    -%} {{ trigger.event.data.event }} {%- elif integration_id == "zha" -%} {{
    trigger.event.data.command }}{{"_" if trigger.event.data.args|length > 0}}{{
    trigger.event.data.args|join("_") }} {%- endif -%}
  trigger_delta: >-
    {{ (as_timestamp(now()) - as_timestamp((states(helper_last_controller_event)
    | from_json).last_triggered if helper_last_controller_event is not none and
    (states(helper_last_controller_event) | regex_match("^\{(\".*\": \".*\"(,
    )?)*\}$")) else "1970-01-01 00:00:00")) * 1000 }}
  last_controller_event: >-
    {{ (states(helper_last_controller_event) | from_json).trigger_action if
    helper_last_controller_event is not none and
    (states(helper_last_controller_event) | regex_match("^\{(\".*\": \".*\"(,
    )?)*\}$")) else "" }}

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
