### ISSUE TITLE
Enhancement - media_player-hook - (Optional setting) only allow volume-changes if media_player. is playing 

### ISSUE THREAD

**Issue by smathev** [EPMatt/awesome-ha-blueprints#186]
### Blueprint name

media_player / ikea_e1744

### Description

Hi. 

So, I'm using the media_player Hook with an ikea E1744 symfonisk remote. It is working wonderfully, and it was easy to set up the blueprints and automation.

However, I've noticed that I can change volume when the music isn't playing. That isn't really a bad thing in itself, but without feedback as to how much the volume has changed it would mean I could (potentially) turn it from easy-listening at 5% volume to 100% volume while paused and only know it when I turned the music back on.

So, my suggestion is that there should be an option in the media_player-Hook as to whether volume-changes could happen when the media_player is paused.

### Automation YAML config

```yaml
conditions:
      - condition: state
        entity_id: media_player.XXXXX-NameOfMediaPlayerThatTheHookIsControlling
        state: 'playing'
      - condition: state
        state: '{{ action == volume_up_repeat }}'

I'm fairly certain that something along these lines would mean that volume-changes wouldn't happen when the music is paused, and would ensure that you get feedback
```

### Implementation

A toggle in the media_player implementation whether volume changes should only be made when the media_player.XXXX is playing music.

### Additional Details

- [ ] I'd like to help developing this feature/improvement.
