### ISSUE TITLE
Bug - Philips 324131092621 Hue Dimmer switch - Event not fired

### ISSUE THREAD

**Issue by B1ob** [EPMatt/awesome-ha-blueprints#187]
### Blueprint name

Controller - Philips 324131092621 Hue Dimmer switch

### Home Assistant Core Version

2021.11.4

### Home Assistant Installation Type

Home Assistant Operating System

### Description

I have a Philips 324131092621 Hue Dimmer switch. The Automation is also started, however it stops at the "chose" step without any action. The step before changes the following variable:

`trigger_action: on_press_button_press_type_command_id_args
trigger_delta: 93.26291084289551`

Is here somehow a discrepancy to the condition statements?

### Automation YAML config

```yaml
- id: '1637310188794'
  alias: Controller - Philips 324131092621 Hue Dimmer switch
  description: ''
  use_blueprint:
    path: EPMatt/philips_324131092621.yaml
    input:
      integration: ZHA
      controller_device: def2e4b6220a313b3f68ba8d091ff464
      helper_last_controller_event: input_text.it_blueprint_switch_bedroom
```

### To Reproduce

3. Trigger the automation '....'

### Expected behavior

A condition in the chose step is taken and an event is fired. 

### Actual Behaviour

No action is taken

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Screenshots

![image](https://user-images.githubusercontent.com/75935521/142597632-3dc75e3d-fcdc-4f70-ac9f-a3a7e9db475f.png)
