### ISSUE TITLE
Bug -  Philips 324131092621 Hue Dimmer switch to Light Hook no action

### ISSUE THREAD

**Issue by Mugga6315** [EPMatt/awesome-ha-blueprints#193]
### Blueprint name

Controller - Philips 324131092621 Hue Dimmer switch

### Home Assistant Core Version

core-2021.11.4

### Home Assistant Installation Type

Home Assistant Operating System

### Description

I am using Zigbee2MQTT with a Phillips 324131092621 remote. Imported the Controller Blueprint and Hook Light Blueprint.
The controller automation shows it is being triggered but the hook is never triggered.
Checked if "ahb_controller_event" is fired, but it isnt.

Got exactly the same issue with an IKEA E1743, remote/controller automation is triggered but "ahb_controller_event" isnt.

I've got one automation running with an Ikea E1524/E1810 remote. This behaves normally and the "ahb_controller_event" does fire as expected.

### Automation YAML config

```yaml
Remote YAML
alias: Remote - Buero
description: ''
use_blueprint:
  path: EPMatt/philips_324131092621.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.remote_buero_action


Hook YAML
alias: Hook - Light Buero
description: ''
use_blueprint:
  path: EPMatt/light.yaml
  input:
    light_color_mode: None
    controller_entity: sensor.remote_buero_action
    controller_model: Philips 324131092621 Hue Dimmer switch
    light: light.group_buero
    brightness_steps_long: 30
```

### To Reproduce

3. Trigger the automation '....'

### Expected behavior

Hook Light being triggered.

### Actual Behaviour

Controller shows trigger but light hook shows no action

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
