### ISSUE TITLE
Bug - Philips 324131092621 Hue Dimmer switch - Zigbee2MQTT

### ISSUE THREAD

**Issue by mjhcdk** [EPMatt/awesome-ha-blueprints#216]
### Blueprint name

Controller - Philips 324131092621 Hue Dimmer switch

### Home Assistant Core Version

2021.12.1

### Home Assistant Installation Type

Home Assistant Supervised

### Description

Hi, seems there might be an issue with the action names triggered from Z2M is with "_" while the blueprint (  
Version 2021.11.19  ) is using "-" in action names i.e for off_press. This is causing no action is performed when the automation/blueprint is triggered.    

Mq log entry:
MQTT publish: topic 'zigbee2mqtt/lænestol_dim', payload '{"action":"off_press","battery":69.5,"last_seen":"2021-12-14T00:42:48+01:00","linkquality":129,"update":{"state":"idle"},"update_available":null}'

in Blueprint automation 
    zigbee2mqtt:
      button_on_short:
        - on-press
      button_on_long:
        - on-hold
      button_on_release:
        - on-hold-release
      button_off_short:
        - off-press
      button_off_long:
        - off-hold

z2m - Device info.  
-------------------------
Zigbee Model RWL021
Zigbee Manufacturer Philips
Description Hue dimmer switch
Firmware version 6.1.1.28573
Manufacturer Philips
Model 324131092621
 

### Automation YAML config

```yaml
alias: 'Controller - Fars Lampe '
description: ''
use_blueprint:
  path: EPMatt/philips_324131092621.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.laenestol_dim_action
    helper_last_controller_event: input_text.laenestol_dim_last
    action_button_on_short:
      - service: light.turn_on
        target:
          device_id: 9419bbee5ebc4c4d9592c642dd4f2d2b
    action_button_off_short:
      - service: light.turn_off
        target:
          device_id: 9419bbee5ebc4c4d9592c642dd4f2d2b
```

### To Reproduce

3. Trigger the automation '....'

### Expected behavior

when pressing the off button (4) it should trigger the action_button_off_short: 
The same goes for the other actions.   
 

### Actual Behaviour

No action is performed See screenshot below 

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Screenshots

<img width="560" alt="image" src="https://user-images.githubusercontent.com/61055519/145907703-042bbb70-36ff-486e-90ef-7a1e79e4a4e7.png">
