### ISSUE TITLE
IKEA E1812 Shortcut button double press does not work

### ISSUE THREAD

**Issue by vandalon** [EPMatt/awesome-ha-blueprints#22]
**Bug Details**

- Blueprint name: IKEA E1812 Shortcut button
- Home Assistant Core Version: 2021.3.4
- Home Assistant Installation Type: Homeassistant OS on Home-Assistant blue

**Description**
Double press does nothing, i have setup the helper, and I do see the helper being filled for 1 second and then cleared again.

**To Reproduce**
Setup double press automation with E1812 on 2021.3.4 and try a double click. 

**Expected behavior**
Execute the event configured with double press

**Actual Behaviour**
I don't get any error. I see that after 1 second the normal single press command is executed. 

**Additional context**
My config

```
  alias: Controller - IKEA E1812 Shortcut button
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1812.yaml
    input:
      integration: deCONZ
      controller_device: 118a7da2e7cca4bbc73b6a535ccf09c7
      action_button_double:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.woonkamer
      button_double_press: true
      helper_last_controller_event: input_text.woonkamer_shortcut_button_test
      action_button_short:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.plafondlamp_woonkamer

```
