### ISSUE TITLE
Bug - groups not dimming, only light.foo works

### ISSUE THREAD

**Issue by kompiz** [EPMatt/awesome-ha-blueprints#232]
### Blueprint name

Hook - Light

### Home Assistant Core Version

2021.12.7

### Home Assistant Installation Type

Home Assistant Container

### Description

If I specify ```light.foo```, dimming works as intended. However, if specifying ```group.bar```instead, nothing happens, and the following is logged in HA:

```ERROR (MainThread) [homeassistant.components.automation.hook_light] Error rendering variables: TypeError: argument of type 'NoneType' is not iterable```

Btw big thx for a great blueprint!

### Automation YAML config

```yaml
- id: '1641724220464'
  alias: Controller - IKEA E1744 SYMFONISK Rotary Remote
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1744.yaml
    input:
      integration: Zigbee2MQTT
      controller_entity: sensor.kontoret_symfcon1_action
      helper_last_controller_event: input_text.symfcon1_helper
- id: '1641724265803'
  alias: Hook - Light
  description: ''
  use_blueprint:
    path: EPMatt/light.yaml
    input:
      light_color_mode: Auto
      controller_entity: sensor.kontoret_symfcon1_action
      controller_model: IKEA E1744 SYMFONISK Rotary Remote
      light: group.kontoret
```

### To Reproduce

1. Set up the blueprint for the controller
2. Set up the blueprint for the hook
3. Trigger the automation by turning the Symfonisk

### Expected behavior

The group of lights should dim.

### Actual Behaviour

Nothing happens, except for error entry in log.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

**Comment by EPMatt** [comment]
Hi @kompiz,
thank you for reporting here!

The Light Hook blueprint only supports single lights and Light Groups, but not generic Home Assistant groups, as stated in the [blueprint Additional Notes](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/hooks/light#additional-notes):

> If you want to link multiple lights to the same controller you can either use [Light Groups](https://www.home-assistant.io/integrations/light.group/) or build multiple Hooks linked to the same Controller.

Light Groups are Home Assistant entities specifically designed to group lights only; they're defined under the `light` domain, and are totally different from the more generic HA groups (described by the `group` domain).

To control a group of lights with a single automation, please configure a Light Group and provide it to the blueprint in place of the `group.kontoret` entity:

```yaml
- id: '1641724265803'
  alias: Hook - Light
  description: ''
  use_blueprint:
    path: EPMatt/light.yaml
    input:
      light_color_mode: Auto
      controller_entity: sensor.kontoret_symfcon1_action
      controller_model: IKEA E1744 SYMFONISK Rotary Remote
      light: light.kontoret  # <- your light group's entity ID here
```
You can find more info on how to setup light groups in the [Light Group integration docs](https://www.home-assistant.io/integrations/light.group/).

Please let me know if this solves your issue.
Thanks again :)
