### ISSUE TITLE
Bug - IKEA E2001/E2002 STYRBAR override yields inconsistent results

### ISSUE THREAD

**Issue by SHxKM** [EPMatt/awesome-ha-blueprints#236]
### Blueprint name

IKEA E2001/E2002 STYRBAR

### Home Assistant Core Version

2021.2012.10

### Home Assistant Installation Type

Home Assistant Operating System

### Description

With no overrides this automation works great (alongside the hook), but when I override (for example) the `action_button_left_short`, inconsistent behavior is observed when that overridden button is pressed. Perhaps there's a cancellation effect going on, or multiple actions being run instead of one (the "override" action).

### Automation YAML config

```yaml
alias: Controller - Kitchen Group
description: ''
use_blueprint:
  path: EPMatt/ikea_e2001_e2002.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.kitchen_remote_action
    helper_last_controller_event: input_text.kitchen_remote_aut_helper
    action_button_left_long: []
    action_button_left_short:
      - service: light.turn_on
        target:
          entity_id: light.kitchen_lights
        data:
          color_temp: 153
    action_button_right_short: []
```

### To Reproduce

1. Create Controller & Hook
2. Override `action_button_left_short` using the UI
3. The override is `light.turn_on` with `"data": {"color_temp": 153}`
4. Click the left button of the `E2002` remote

### Expected behavior

When `left_button_short_press` override is provided (as in the automation YAML snippet), the lights will change to the desired state.

### Actual Behaviour

The lights seem to behave very oddly, I don't know the exact order of events but it seems like the first do the expected action, but then another action is triggered which sends them to an undesired state.

### Additional Details

- [X] I'd like to help developing a fix for this issue.
