### ISSUE TITLE
Bug - Ikea E1744 - Error: UndefinedError: 'dict object' has no attribute 'event'

### ISSUE THREAD

**Issue by weber8thomas** [EPMatt/awesome-ha-blueprints#237]
### Blueprint name

Controller - IKEA E1744 SYMFONISK Rotary Remote

### Home Assistant Core Version

2021.12.10

### Home Assistant Installation Type

Home Assistant Supervised

### Description

Hi everyone,

I just bought an IKEA E1744 SYMFONISK Rotary Remote and tried to use it to control my Sonos Symfonisk frame. I followed all the procedure two times (including the mandatoray input_text `helper_last_controller_event` by using first the controller blueprint and then the [Media Player one](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/hooks/media_player). I am using the Zigbee2MQTT configuration and obtained the following error in both automations : **Error: UndefinedError: 'dict object' has no attribute 'event'**.

I tried to dig from what the error could came from but didn't succeed. What is weird is that the `helper_last_controller_event ` input_text actually catch well the actions from the remote.

Thanks in advance for your help and for your amazing work !

Thomas

### Automation YAML config

```yaml
id: '1642575595166'
alias: Controller - IKEA E1744 SYMFONISK Rotary Remote
description: ''
use_blueprint:
  path: EPMatt/ikea_e1744.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.volume_sonos_bureau_action
    helper_last_controller_event: input_text.helper_last_controller_event
```

### To Reproduce

1. Pair remote with Zigbee2MQTT
2. Import and configure Controller - IKEA E1744 SYMFONISK Rotary Remote blueprint 
3. Import and configure Media Player blueprint

### Expected behavior

Media player responsive to the Ikea remote

### Actual Behaviour

Error: UndefinedError: 'dict object' has no attribute 'event'

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Screenshots

![2022-01-19 08_50_19-Configuration - Home Assistant](https://user-images.githubusercontent.com/32496011/150087107-ef0a0eb6-6bea-4f11-9cb6-fd30c0f8f7cf.png)

![2022-01-19 08_52_47-Journal - Home Assistant](https://user-images.githubusercontent.com/32496011/150087482-be8b85d5-d4ca-499d-970c-1ba9fb9080b7.png)
