### ISSUE TITLE
Bug - Zigbee2MQTT works only in legacy trigger mode

### ISSUE THREAD

**Issue by tomasbedrich** [EPMatt/awesome-ha-blueprints#244]
### Blueprint name

/all blueprints/

### Home Assistant Core Version

2021.12.10

### Home Assistant Installation Type

Home Assistant Operating System

### Description

When you set `homeassistant_legacy_triggers: false` ([docs](https://www.zigbee2mqtt.io/guide/configuration/homeassistant.html)), there is no `xxx_action` sensor created, therefore there is no entity which can be used as "(Zigbee2MQTT) Controller Entity".

As name suggests, relying on such entity is considered legacy, therefore can be removed in future?

### Automation YAML config

```yaml
# irrelevant, but for example:

alias: Bedroom controller
description: ''
use_blueprint:
  path: EPMatt/ikea_e1743.yaml
  input:
    integration: Zigbee2MQTT
    helper_last_controller_event: input_text.bedroom_controller_last_event
    button_up_double_press: false
    action_button_up_double: []
    helper_double_press_delay: 200
    button_down_double_press: false
    controller_entity: sensor.bedroom_controller_action # <<<<<< this field is the issue
```

### To Reproduce

1. Install Zigbee2MQTT addon.
2. Set:
 ```
advanced:
  homeassistant_legacy_triggers: true
```
3. Restart Zigbee2MQTT addon.
4. Attempt to create a new Blueprint.

### Expected behavior

A device can be selected (similarly to ZHA/Deconz) as a Controller Device. This would be consistent with native Home Assistant Automations, where a device must be selected for triggers to show.

### Actual Behaviour

No device / nor entity is available to proceed with Blueprint creation.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
