### ISSUE TITLE
Bug - Ikea E1744 Controller - FW2.1.024 - "Stopped because a condition failed"

### ISSUE THREAD

**Issue by tjxism** [EPMatt/awesome-ha-blueprints#253]
### Blueprint name

Controller - IKEA E1744 SYMFONISK Rotary Remote

### Home Assistant Core Version

2022.2.3

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Hi everyone,

I just bought an IKEA E1744 SYMFONISK Rotary Remote (FW2.1.024) and tried to use it to control my Sony Android TV A9G. Remote paired through Zigbee2MQTT. The Entity (sensor) responds properly in HA. 

I followed all the procedure several times (creating the mandatory input_text helper_last_controller_event, set up Controller E1744 Blueprint, Set up Hook Media Player Blueprint. I am using the Zigbee2MQTT configuration. The Input_Text helper captures the remote action. The automation will not go through and reports:
"Stopped because a condition failed at February 9, 2022, 2:50:39 PM (runtime: 0.00 seconds)". 

Thanks in advance for your help and for your amazing work !

Jingxi

### Automation YAML config

```yaml
- id: '1644384238280'
  alias: Controller - IKEA E1744 SYMFONISK Rotary Remote
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1744.yaml
    input:
      integration: Zigbee2MQTT
      controller_entity: sensor.ikea_rotary_remote_1_action
      helper_last_controller_event: input_text.helper_last_controller_input_ikea_rotary_1
      rotate_right_max_loop_repeats: 3
      rotate_left_max_loop_repeats: 4
      rotate_left_loop: false
      rotate_right_loop: false
      helper_debounce_delay: 0
      action_click_short: []
- id: '1644384325422'
  alias: Hook - IKEA Rotary Media Player Remote
  description: ''
  use_blueprint:
    path: EPMatt/media_player.yaml
    input:
      controller_entity: sensor.ikea_rotary_remote_1_action
      controller_model: IKEA E1744 SYMFONISK Rotary Remote
      media_player: media_player.sony_bravia_tv
      volume_steps_long: 20
```

### To Reproduce

Integrate TV with Bravia TV integration. Successful control through Lovelace Card. 

Pair remote with Zigbee2MQTT
Import and configure Controller - IKEA E1744 SYMFONISK Rotary Remote blueprint 
Import and configure Media Player blueprint

Click/Rotate Remote

### Expected behavior

TV to respond to control

### Actual Behaviour

No respond. 

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Screenshots

![Capture](https://user-images.githubusercontent.com/97436742/153140500-560978fc-6d19-4d3a-ae8b-e531f70680fb.JPG)

### Additional context

Input  Text  capture:
Changed to {"trigger_action": "rotate_stop", "last_triggered": "2022-02-09 14:50:39.637569+08:00"} by service input_text.set_value
2:50:39 PM - 18 minutes ago

Trace Timeline:
Triggered by the event 'state_changed' at February 9, 2022, 3:14:15 PM
Test multiple conditions using "and"
Stopped because a condition failed at February 9, 2022, 3:14:15 PM (runtime: 0.00 seconds)
