### ISSUE TITLE
Bug - Ikea e2002 Double press issue

### ISSUE THREAD

**Issue by apocaliss92** [EPMatt/awesome-ha-blueprints#259]
### Blueprint name

ikea_e2001_e2002

### Home Assistant Core Version

2022.2.5

### Home Assistant Installation Type

Home Assistant Supervised

### Description

The issue is quiet simple to reproduce, at least in my case. It's enough to enable the double press event handling for any of the button and associate an action to it; what happens is that the double event action is always executed, the short press is ignored 

### Automation YAML config

```yaml
alias: '[IKEA REMOTE Comodino Gianluca] Luci'
description: ''
use_blueprint:
  path: EPMatt/ikea_e2001_e2002.yaml
  input:
    integration: ZHA
    controller_device: 388883d20368b5e81d1d7ada2be62a31
    helper_last_controller_event: input_text.pulsante_camera_event
    action_button_up_short:
      - device_id: 5e74822022fb4a62f81defb9f6b7d4ee
        domain: light
        entity_id: light.lampadina_comodino_gianluca
        type: brightness_increase
    action_button_down_short:
      - device_id: 5e74822022fb4a62f81defb9f6b7d4ee
        domain: light
        entity_id: light.lampadina_comodino_gianluca
        type: brightness_decrease
    action_button_down_double: []
    button_down_double_press: false
    action_button_down_long:
      - device_id: 6e5564150d391a723df47686c7f590b3
        domain: light
        entity_id: light.proiettore
        type: brightness_decrease
    action_button_up_long:
      - device_id: 6e5564150d391a723df47686c7f590b3
        domain: light
        entity_id: light.proiettore
        type: brightness_increase
    action_button_up_double:
      - service: script.notifica
        data:
          message: L'asciugatrice ha finito
    button_up_double_press: true
    action_button_left_short:
      - service: light.turn_on
        data:
          color_temp: >-
            {{ state_attr("light.lampadina_comodino_gianluca","color_temp")|int
            - 50 }}
          transition: 0.25
        entity_id: light.lampadina_comodino_gianluca
    action_button_right_short:
      - service: light.turn_on
        data:
          color_temp: >-
            {{ state_attr("light.lampadina_comodino_gianluca","color_temp")|int
            + 50 }}
          transition: 0.25
        entity_id: light.lampadina_comodino_gianluca
    action_button_left_long:
      - type: turn_off
        device_id: 5e74822022fb4a62f81defb9f6b7d4ee
        entity_id: light.lampadina_comodino_gianluca
        domain: light
    action_button_right_long:
      - type: turn_on
        device_id: 5e74822022fb4a62f81defb9f6b7d4ee
        entity_id: light.lampadina_comodino_gianluca
        domain: light
        brightness_pct: 100
```

### To Reproduce

1. Create an automation with the ikea_e2001_e2002 blueprint
2. Associate an action to the up button short press
3. Associate an action to the up button double press
4. Activate the up button double press event
5. Press the up button once, the double press action is executed

### Expected behavior

The short press action should be executed 

### Actual Behaviour

The double press action is executed 

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

**Comment by EPMatt** [comment]
Hi @apocaliss92,
thank you for reporting here.

Are you sure the up button double press event is enabled? Based on the YAML you provided, it looks like such event is indeed disabled:
```yaml
    action_button_up_double:
      - service: script.notifica
        data:
          message: L'asciugatrice ha finito
    button_up_double_press: false
```

Thanks!
