### ISSUE TITLE
Bug - Addon Update Available Error

### ISSUE THREAD

**Issue by snipes040** [EPMatt/awesome-ha-blueprints#261]
### Blueprint name

Send a mobile notification when add-on update is available

### Home Assistant Core Version

2022.2.6

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Automation doesn't fire as it shows the below error in the logs:

**Template variable error: 'dict object' has no attribute 'to_state' when rendering '{{ trigger.to_state.state == "on" }}'**

### Automation YAML config

```yaml
- id: '1645034554285'
  alias: ESPHome Addon Update Available
  description: ''
  use_blueprint:
    path: EPMatt/addon_update_notification.yaml
    input:
      notification_channel_importance: default
      addon: a0d7b954_esphome
      addon_name: ESPHome
      addon_sensor_version: sensor.esphome_version
      addon_sensor_newest_version: sensor.esphome_newest_version
      addon_sensor_update_available: binary_sensor.esphome_update_available
      mobile_notify_service: notify.mobile_app_redmi_note_6_pro
      tap_action: /hassio/addon/{{ addon }}/info
      notification_message: Update available for {{ addon_name }} add-on ({{ version
        }} -> {{ newest_version }})
      notification_title: '{{ addon_name }} add-on : Update available'
      notification_color: homeassistant
      notification_channel: Home Assistant Updates
      notification_group: Available Updates
      update_success_notification_title: '{{ addon_name }} add-on: Update completed'
      update_success_notification_message: add-on {{ addon_name }} was succesfully
        updated to {{ newest_version }}
```

### To Reproduce

1. Go to 'Developer Tools'
2. Click on 'Services'
3. Trigger the automation 'Set Service to: Automation: Trigger and select the automation entity.'

### Expected behavior

Notification pops up on phone showing there is an update available

### Actual Behaviour

No notification and error in logs.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
