### ISSUE TITLE
Bug - IKEA E2001/E2002 STYRBAR Remote control #2

### ISSUE THREAD

**Issue by noiob** [EPMatt/awesome-ha-blueprints#263]
### Blueprint name

Hook - Light

### Home Assistant Core Version

2022.2.9

### Home Assistant Installation Type

Home Assistant Container

### Description

Choosing the `IKEA E2001/E2002 STYRBAR Remote control (#2)` variant of the STYRBAR mappings doesn't seem to work, it always chooses the default mapping.

### Automation YAML config

```yaml
alias: Hook - Light Deckenfluter
description: ''
use_blueprint:
  path: EPMatt/light.yaml
  input:
    light_color_mode: Color Temperature
    controller_device: 2693d0a408a729dc3698134a81ad6a67
    light: light.deckenfluter_009fd8fe_level_light_color_on_off
    controller_model: IKEA E2001/E2002 STYRBAR Remote control (#2)
    brightness_steps_long: 30
    force_brightness: true
    on_brightness: 176
    brightness_steps_short: 20

alias: Controller - IKEA E2001/E2002 STYRBAR Remote control
description: ''
use_blueprint:
  path: EPMatt/ikea_e2001_e2002.yaml
  input:
    integration: ZHA
    helper_last_controller_event: input_text.styrbar_4_button_deckenfluter_text
    controller_device: 2693d0a408a729dc3698134a81ad6a67
    action_button_left_short: []
    button_left_double_press: true
    button_right_double_press: true
    button_up_double_press: true
    button_down_double_press: true
```

### To Reproduce

- set up the STYRBAR Remote controller
- set up the light hook
- choose the `IKEA E2001/E2002 STYRBAR Remote control (#2)` mapping
- press a button on the remote that differs between the two mappings

### Expected behavior

the light responds according to the "Mapping #2" mapping

### Actual Behaviour

the light responds according to the default mapping

### Additional Details

- [X] I'd like to help developing a fix for this issue.

### Additional context

I suspected the `#` character in the name of the mapping to be the culprit as it's a reserved character in YAML, but removing it in the entire script and restarting my HA instance didn't seem to fix it.
