### ISSUE TITLE
Bug - ikea 1812 shortcut error and no trace in automation

### ISSUE THREAD

**Issue by seawiid** [EPMatt/awesome-ha-blueprints#287]
### Blueprint name

Controller - IKEA E1812 TRÅDFRI Shortcut button

### Home Assistant Core Version

2022.03.05

### Home Assistant Installation Type

Home Assistant Operating System

### Description

i added an automation using the 1812 blueprint. The automation runs, but I constantly get an error in the trace, and the trace doesn't show the actions executed. I'm unclear if this is expected behaviour. it reports that the result was false so the condition failed. trace shows only the following: 
```
condition: and
conditions:
  - >-
    {%- set trigger_action -%} {%- if integration_id == "zigbee2mqtt" -%} {{
    trigger.event.data.new_state.state }} {%- elif integration_id == "deconz"
    -%} {{ trigger.event.data.event }} {%- elif integration_id == "zha" -%} {{
    trigger.event.data.command }}{{"_" if trigger.event.data.args|length > 0}}{{
    trigger.event.data.args|join("_") }} {%- endif -%} {%- endset -%} {{
    trigger_action not in ["","None"] }}
  - >-
    {{ integration_id != "zigbee2mqtt" or trigger.event.data.new_state.state !=
    trigger.event.data.old_state.state }}
```

### Automation YAML config

```yaml
alias: Master Nighstand Button Left
description: ''
use_blueprint:
  path: EPMatt/ikea_e1812.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.nightstand_button_left_action
    helper_last_controller_event: input_text.nightstand_left_last_action
    action_button_short:
      - choose:
          - conditions:
              - condition: time
                before: '07:00:00'
                after: '22:00:00'
            sequence:
              - service: light.toggle
                data:
                  brightness_pct: 1
                target:
                  entity_id: light.master
              - choose:
                  - conditions:
                      - condition: state
                        entity_id: light.master
                        state: 'on'
                    sequence:
                      - service: input_boolean.turn_on
                        data: {}
                        target:
                          entity_id: input_boolean.master_lights_manual_control
                      - service: input_boolean.turn_off
                        data: {}
                        target:
                          entity_id: input_boolean.nightstand_button_activated
                default: []
          - conditions:
              - condition: time
                before: '22:00:00'
                after: '07:00:00'
            sequence:
              - service: light.toggle
                data:
                  brightness_pct: 20
                target:
                  entity_id: light.master
              - choose:
                  - conditions:
                      - condition: state
                        entity_id: light.master
                        state: 'on'
                    sequence:
                      - service: input_boolean.turn_on
                        data: {}
                        target:
                          entity_id: input_boolean.master_lights_manual_control
                      - service: input_boolean.turn_off
                        data: {}
                        target:
                          entity_id: input_boolean.nightstand_button_activated
                  - conditions:
                      - condition: state
                        entity_id: light.master
                        state: 'off'
                    sequence:
                      - service: input_boolean.turn_off
                        data: {}
                        target:
                          entity_id: input_boolean.master_lights_manual_control
                      - service: input_boolean.turn_on
                        data: {}
                        target:
                          entity_id: input_boolean.nightstand_button_activated
                default: []
        default: []
    action_button_long:
      - device_id: b987b17948b43f2c56dbbaacf102f1a1
        domain: light
        entity_id: light.master
        type: brightness_increase
    action_button_double:
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.master_bath_group
    button_long_loop: true
    button_double_press: true
```

### To Reproduce

triggering the automation produces this

### Expected behavior

light toggles on button press, and also sets input booleans. there is a different brightness setting depending on time of day. double press will turn off bathroom lights and holding the button increases brightness

### Actual Behaviour

seems to work, but i cannot see the actions executed in the trace and it reports that it was aborted.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
