### ISSUE TITLE
Bug - Send Web UI persistent notifications to Mobile Devices doesn't work

### ISSUE THREAD

**Issue by ElVit** [EPMatt/awesome-ha-blueprints#288]
### Blueprint name

Send Web UI persistent notifications to Mobile Devices

### Home Assistant Core Version

2022.3.5

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Blueprint doesn't work with the iOS Home Assistant App. 
The persistent notifications are not forwarded to my iPhone.
But I can send a notification to my iPhone by sending **notify.mobile_app_myiphone**.

### Automation YAML config

```yaml
id: '1643998917699'
alias: Update notification to all iPhones
description: ''
use_blueprint:
  path: EPMatt/persistent_notification_to_mobile.yaml
  input:
    mobile_notify_service: notify.mobile_app_myiphone
    notification_id: '1234'
```

### To Reproduce

1. Create automation with this blueprint. Define only **mobile_notify_service** and **notification_id = 1234**
2. persistent_notification.create (with messgae, title & **notification_id = 1234**)
3. -> **no** notify message on my iPhone
4. notify.mobile_app_myiphone (with message & title)
5. -> I can see a notification message on my iPhone

### Expected behavior

All persistent notifications with the ID="1234" shall be forwarded to my iPhone.

### Actual Behaviour

I don't get any notifications to my iPhone.
I get the follwing error in trace step details:
Error: Error rendering data template: UndefinedError: 'dict object' has no attribute 'event'

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

**Comment by EPMatt** [comment]
Hi @ElVit,

thank you for reaching out here, I'm sorry for my huge delay.
It seems the event is not properly recognized after the automation has been triggered. Could you please share screenshots from the HA trace tool regarding the automation you're setting up with this blueprint?

Thank you for your patience!

**Comment by Xx-Ness-xX** [comment]
Hello,

I have the exact same error message, and my notification ID is set to http-login, see the details below:

![Screenshot_20220708-154248](https://user-images.githubusercontent.com/17007480/178067728-77b4936d-1502-43dc-9ea2-473178907111.png)



### Blueprint name

Send Web UI persistent notifications to Mobile Devices
### Home Assistant Core Version

2022.3.9
### Home Assistant Installation Type

Home Assistant Core
### Description

Blueprint doesn't work with the Android Home Assistant App. The persistent notifications are not forwarded to my Android. But I can send a notification to my Android by sending **notify.mobile_app_pixel_5**.
### Automation YAML config

```yaml
id: '1631811045862'
alias: Invalid login attempts notifications to Mobile Devices
description: ''
use_blueprint:
  path: EPMatt/persistent_notification_to_mobile.yaml
  input:
    mobile_notify_service: notify.mobile_app_pixel_5
    notification_id: http-login
```

### To Reproduce

1. Invalid login attempts
2. persistent_notification.create
3. -> **no** notify message on my Android
4. notify.mobile_app_pixel_5 (with message & title)-> I can see a notification message on my Android

### Expected behavior

All persistent notifications with the ID="http-login" shall be forwarded to my Android.
### Actual Behaviour

I don't get any notifications to my Android. I get the follwing error in trace step details: Error: Error rendering data template: UndefinedError: 'dict object' has no attribute 'event'
### Additional Details

- [ ] I'd like to help developing a fix for this issue.


### Screenshots

_No response_
### Additional context

_No response_

**Comment by Xx-Ness-xX** [comment]
Hi

any update on this? Thanks

**Comment by Fruitsmart** [comment]
Hello i have the same mistake.

**Comment by niemtec** [comment]
I've noticed the same issue in my setup 😞

**Comment by niemtec** [comment]
I was able to create a dummy automation with the following action and it worked:
```yaml
service: notify.mobile_app_xxx
data:
  message: "{{ trigger.notification.message }}"
  title: "{{ trigger.notification.title }}"
  ```

**Comment by Xx-Ness-xX** [comment]
> I was able to create a dummy automation with the following action and it worked:
> 
> ```yaml
> service: notify.mobile_app_xxx
> data:
>   message: "{{ trigger.notification.message }}"
>   title: "{{ trigger.notification.title }}"
> ```

Hi, could you please elaborate how you get this to work?

**Comment by Fruitsmart** [comment]
i have a error

![grafik](https://github.com/EPMatt/awesome-ha-blueprints/assets/59370540/dbbbd8e5-0189-4287-a0e8-0be686b5a324)

**Comment by niemtec** [comment]
> > I was able to create a dummy automation with the following action and it worked:
> 
> > 
> 
> > ```yaml
> 
> > service: notify.mobile_app_xxx
> 
> > data:
> 
> >   message: "{{ trigger.notification.message }}"
> 
> >   title: "{{ trigger.notification.title }}"
> 
> > ```
> 
> 
> 
> Hi, could you please elaborate how you get this to work?

Sure, I created a new automation that is triggered on "When persistent notification is updated" and set the above as a call service action.

So the automation looks like so:

```yaml

alias: Notification Forward
description: ""
trigger:
  - platform: persistent_notification
    update_type:
      - added
      - updated
      - current
    notification_id: ""
condition: []
action:
  - service: notify.mobile_app_jakubs_iphone_15
    data:
      message: "{{ trigger.notification.message }}"
      title: "{{ trigger.notification.title }}"
mode: single

```
