### ISSUE TITLE
Bug - Ikea E1810 up/down left/right buttons do not work on ZHA

### ISSUE THREAD

**Issue by PhotosBySimonH** [EPMatt/awesome-ha-blueprints#311]
### Blueprint name

Controller - IKEA E1524/E1810 TRÅDFRI Wireless 5-Button Remote

### Home Assistant Core Version

2022.4.2

### Home Assistant Installation Type

Home Assistant Operating System

### Description

When I press anything other than the centre button the required action set in the blueprint does not trigger, I've attached the trace from the automation for a failed short button down push. 

I'm not a programmer but looking through the code and the trace I think the pattern expected by the automation from ZHA for the button press event is not matching what is recorded by the blueprint in the trigger_action variable so it errors out 

e.g. in this case trigger_action appears to be recorded as step_StepMode.Down_43_5_bitmap8.0_bitmap8.0 but my reading of the blueprint code make it look like it is expecting    button_down_short = step_1_43_5.

I've tried this with 2 different E1810 remotes and neither work with both remotes having the same result and the same data recorded.

[trace automation.controller_ikea_e1524_e1810_tradfri_wireless_5_button_remote 2022-04-13T17_31_16.895672+00_00.txt](https://github.com/EPMatt/awesome-ha-blueprints/files/8483581/trace.automation.controller_ikea_e1524_e1810_tradfri_wireless_5_button_remote.2022-04-13T17_31_16.895672%2B00_00.txt)

### Automation YAML config

```yaml
alias: Bedroom Light
description: ''
use_blueprint:
  path: EPMatt/ikea_e1524_e1810.yaml
  input:
    helper_last_controller_event: input_text.ikea1810
    controller_device: 752b1e18ad5b8ef9b62b4b0b9eb96ef4
    integration: ZHA
    action_button_up_short:
      - service: scene.turn_on
        target:
          entity_id: scene.bedroom_daylight
        metadata: {}
    action_button_down_short:
      - service: scene.turn_on
        target:
          entity_id: scene.bedroom_evening
        metadata: {}
    action_button_center_short:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.bedroom_level_light_color_on_off
    helper_debounce_delay: 100
```

### To Reproduce

1. push button on the remote
2. automation fires
3. nothing happens 

### Expected behavior

the desired action to tigger e.g. when up is pushed a scene activates

### Actual Behaviour

nothing happens when button is pushed e.g. when up is pushed the scene does not activate

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
