### ISSUE TITLE
Bug - IKEA E1743 longpress no longer works

### ISSUE THREAD

**Issue by kanflo** [EPMatt/awesome-ha-blueprints#312]
### Blueprint name

ikea_e1743.yaml

### Home Assistant Core Version

2022.4.3

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Prior to 2022.3 long press on the E1743 worked like a charm using ZHA. Long press yields the following in the log:
```
Invalid value: {"trigger_action": "move_MoveMode.Down_83_bitmap8.0_bitmap8.0", "last_triggered": "2022-04-13 21:25:11.011648+02:00"} (length range 0 - 100)
```

### Automation YAML config

```yaml
- id: '1638911675158'
  alias: Dimmer Johans skrivbord
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1743.yaml
    input:
      integration: ZHA
      controller_device: 7373e365206f24b54f6423ab692dde58
      helper_last_controller_event: input_text.johan_skrivbord_dimmer
      action_button_up_short:
      - type: turn_on
        device_id: 5b9e9eee8d41b76735b2b02fc452e0c0
        entity_id: light.skrivbord_hoger
        domain: light
      - type: turn_on
        device_id: 1bb7f39db1216c8254014b33de543dae
        entity_id: light.skrivbord_vanster
        domain: light
      action_button_up_long:
      - device_id: 5b9e9eee8d41b76735b2b02fc452e0c0
        domain: light
        entity_id: light.skrivbord_hoger
        type: brightness_increase
      - device_id: 1bb7f39db1216c8254014b33de543dae
        domain: light
        entity_id: light.skrivbord_vanster
        type: brightness_increase
      action_button_down_short:
      - type: turn_off
        device_id: 5b9e9eee8d41b76735b2b02fc452e0c0
        entity_id: light.skrivbord_hoger
        domain: light
      - type: turn_off
        device_id: 1bb7f39db1216c8254014b33de543dae
        entity_id: light.skrivbord_vanster
        domain: light
      action_button_down_long:
      - device_id: 5b9e9eee8d41b76735b2b02fc452e0c0
        domain: light
        entity_id: light.skrivbord_hoger
        type: brightness_decrease
      - device_id: 1bb7f39db1216c8254014b33de543dae
        domain: light
        entity_id: light.skrivbord_vanster
        type: brightness_decrease
      button_up_long_loop: true
      button_up_long_max_loop_repeats: 100
      button_down_long_loop: true
      button_down_long_max_loop_repeats: 197
```

### To Reproduce

1. Long press up or down on the E1743

### Expected behavior

The lights dimmed up or down.

### Actual Behaviour

1. Devtools / States claims the automation has run
2. Configuration / Logs show an error setting the text input helper
3. Light brightness did not change

### Additional Details

- [X] I'd like to help developing a fix for this issue.

### Additional context

This is the complete entry from the log. It seems my automation contains some kind of error but then I did not change the automation when upgrading HASS.

```
2022-04-13 17:06:17 ERROR (MainThread) [homeassistant.components.automation] Blueprint Controller - IKEA E1743 TRÅDFRI On/Off Switch & Dimmer generated invalid automation with inputs OrderedDict([('integration', 'ZHA'), ('controller_device', '7373e365206f24b54f6423ab692dde58'), ('helper_last_controller_event', 'input_text.johan_skrivbord_dimmer'), ('action_button_up_short', [OrderedDict([('type', 'turn_on'), ('device_id', '1bb7f39db1216c8254014b33de543dae'), ('entity_id', 'light.skrivbord_vanster'), ('domain', 'light')]), OrderedDict([('type', 'turn_on'), ('device_id', '5b9e9eee8d41b76735b2b02fc452e0c0'), ('entity_id', 'light.skrivbord_hoger'), ('domain', 'light')])]), ('action_button_up_long', [OrderedDict([('device_id', '5b9e9eee8d41b76735b2b02fc452e0c0'), ('domain', 'light'), ('entity_id', 'light.skrivbord_hoger'), ('type', 'brightness_increase_foo')]), OrderedDict([('device_id', '1bb7f39db1216c8254014b33de543dae'), ('domain', 'light'), ('entity_id', 'light.skrivbord_vanster'), ('type', 'brightness_increase')])]), ('action_button_down_short', [OrderedDict([('type', 'turn_off'), ('device_id', '5b9e9eee8d41b76735b2b02fc452e0c0'), ('entity_id', 'light.skrivbord_hoger'), ('domain', 'light')]), OrderedDict([('type', 'turn_off'), ('device_id', '1bb7f39db1216c8254014b33de543dae'), ('entity_id', 'light.skrivbord_vanster'), ('domain', 'light')])]), ('action_button_down_long', [OrderedDict([('device_id', '5b9e9eee8d41b76735b2b02fc452e0c0'), ('domain', 'light'), ('entity_id', 'light.skrivbord_hoger'), ('type', 'brightness_decrease')]), OrderedDict([('device_id', '1bb7f39db1216c8254014b33de543dae'), ('domain', 'light'), ('entity_id', 'light.skrivbord_vanster'), ('type', 'brightness_decrease')])]), ('button_up_long_loop', True), ('button_up_long_max_loop_repeats', 100), ('button_down_long_loop', True), ('button_down_long_max_loop_repeats', 197)]): value must be one of ['brightness_decrease', 'brightness_increase', 'flash', 'toggle', 'turn_off', 'turn_on'] for dictionary value @ data['type']. Got None```

**Comment by kanflo** [comment]
Actually it seems a bit unfair to label this as a bug in this repo. The input text has a default max length of 100 bytes and this limit is [two years in the making](https://github.com/home-assistant/core/blob/258ca30bc0e2740f68435ace0ed9f3a400c5a6d9/homeassistant/components/input_text/__init__.py#L35).

ZHA could be the culprit by suddenly creating longer events causing strings like this:

```
{"trigger_action": "move_MoveMode.Down_83_bitmap8.0_bitmap8.0", "last_triggered": "2022-04-13 22:47:23.227150+02:00"}
```

To regain dimming of lights, one first needs to bump the max length of the input texts (`min` might be optional):

```
input_text:
  johan_skrivbord_dimmer:
    name: Dimmer Johans skrivbord
    min: 0
    max: 255
```

Additionally, the automation needs to adapt to the new ZHA events. See #314 

Side note: as 255 is the max input string length, it seems to me HASS is written in Pascal :smile:
