### ISSUE TITLE
Bug - Ikea E1744

### ISSUE THREAD

**Issue by H0nzik1** [EPMatt/awesome-ha-blueprints#334]
### Blueprint name

Controller - IKEA E1744 SYMFONISK Rotary Remote

### Home Assistant Core Version

2022.5.3

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Since 2022.4.0 Ikea E1744 blueprint is not working anymore for turning right and left. It works only for press. 

### Automation YAML config

```yaml
alias: Mara SYMFONISK postel
description: ''
use_blueprint:
  path: EPMatt/ikea_e1744.yaml
  input:
    integration: ZHA
    controller_device: 5e9df99d6375a42fb081045ba13507a8
    helper_last_controller_event: input_text.ikea_symfonisk_mara
    action_rotate_left:
      - service: light.turn_on
        data:
          brightness_step_pct: -4
        target:
          device_id: 2df288a46d388f77660b4c7853fd19ef
    action_rotate_right:
      - service: light.turn_on
        data:
          brightness_step_pct: 4
        target:
          device_id: 2df288a46d388f77660b4c7853fd19ef
    rotate_right_loop: true
    rotate_left_loop: true
    action_click_short: []
```

### To Reproduce

1. Update HA 2022.4.0 or newer
2. Try left and right turn for Ikea E1744
3. See - not working anymore
4. I have to stay at 2022.3.8

### Expected behavior

left and right turn for Ikea E1744 is working

### Actual Behaviour

left and right turn for Ikea E1744 is not working

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
