### ISSUE TITLE
Bug - There is no option for the (Required) Helper - Last Controller Event

### ISSUE THREAD

**Issue by RaveGun** [EPMatt/awesome-ha-blueprints#336]
### Blueprint name

Controller - Philips 324131092621 Hue Dimmer switch

### Home Assistant Core Version

Home Assistant Core 2022.5.3

### Home Assistant Installation Type

Home Assistant Supervised

### Description

The automation for my HUE dimmer stopped working.
I tried to find out what is wrong on my mobile phone and manage to delete it by removing the referenced controller device and saving the automation. It just disappeared, but this is not the problem.

I made a new automation that did not worked either, still on my phone.
Through debugging I found out that it was failing on setting the helper text. It was failing because there was no helper input text configured. But on my phone it is not possible to define the helper text.

Hmm.. maybe the screen is to small. So I went on the computer and this is how it looks on Ubunutu - Firefox:
![image](https://user-images.githubusercontent.com/4079754/168168759-465ffe7c-2c78-4724-95f4-ea1f93d24470.png)

On my phone I am using the HA companion app.

After I edited the automation with the yaml editor and added the missing information it started working as expected.

A query on the entities shows the one input_text I have configured. I guess, it should be listed as an option, even if its the only one.
![image](https://user-images.githubusercontent.com/4079754/168169234-a1ace71d-7103-4d15-a438-f7e36aee8506.png)

Maybe this has nothing to do with the blueprint. As I saw in the blueprint's source code the same construction is used to get the list of all sensors for the controller_entity option.

### Automation YAML config

```yaml
alias: Controller - HUE
description: Wtf?
use_blueprint:
  path: EPMatt/philips_324131092621.yaml
  input:
    integration: ZHA
    controller_device: ed8b1700df05973cbe75f74521f066b7
    action_button_on_short:
      - type: turn_on
        device_id: 2fff802336743461e347295de884e5de
        entity_id: light.szmp_nightlamp
        domain: light
        brightness_pct: 16
    action_button_on_long:
      - type: turn_on
        device_id: ffdd29656792910fca2c31193e3536fb
        entity_id: light.smallbedroom
        domain: light
    action_button_off_short:
      - type: turn_off
        device_id: 2fff802336743461e347295de884e5de
        entity_id: light.szmp_nightlamp
        domain: light
    action_button_up_short:
      - type: turn_on
        device_id: 658b05dde9c31e65b467a5461133441e
        entity_id: light.ledvance_tibea_tw_z3_8a261400_level_light_color_on_off
        domain: light
    action_button_down_short:
      - type: turn_off
        device_id: 658b05dde9c31e65b467a5461133441e
        entity_id: light.ledvance_tibea_tw_z3_8a261400_level_light_color_on_off
        domain: light
    action_button_off_release: []
    button_on_long_loop: true
    action_button_off_long:
      - type: turn_off
        device_id: ffdd29656792910fca2c31193e3536fb
        entity_id: light.smallbedroom
        domain: light
```

### To Reproduce

Just create a new automation from the blueprint.

### Expected behavior

Described above.

### Actual Behaviour

Described above.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
