### ISSUE TITLE
Enhancement - Add option to configure delay between long press repeats

### ISSUE THREAD

**Issue by sabaatworld** [EPMatt/awesome-ha-blueprints#337]
### Blueprint name

Controller - IKEA E1524/E1810 TRÅDFRI Wireless 5-Button Remote

### Description

I'm trying use the controller for my climate / HVAC device. I'd like to use automated repeats on long press of up and down arrows to continue increasing or decreasing the temperature in a controllable manner. Currently, it simply executes all repeat very quickly and does not allow fine grain controls.

### Automation YAML config

```yaml
alias: Master Switch Using Blueprint
description: ''
use_blueprint:
  path: EPMatt/ikea_e1524_e1810.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.guest_room_master_switch_action
    helper_last_controller_event: input_text.master_switch_last_action
    action_button_up_short:
      - service: climate.set_temperature
        data:
          temperature: '{{ states.climate.guest_room_ac.attributes.temperature + 1 }}'
        target:
          entity_id: climate.guest_room_ac
    action_button_down_short:
      - service: climate.set_temperature
        data:
          temperature: '{{ states.climate.guest_room_ac.attributes.temperature - 1 }}'
        target:
          entity_id: climate.guest_room_ac
    action_button_center_short:
      - service: switch.toggle
        data: {}
        target:
          entity_id: switch.guest_room_main_lamp_outlet
    button_up_long_loop: true
    button_down_long_loop: true
    button_up_long_max_loop_repeats: 5
    button_down_long_max_loop_repeats: 5
    action_button_left_short:
      - device_id: 27bdff06a2df61d41f4095a2c995c8e3
        domain: climate
        entity_id: climate.guest_room_ac
        type: set_hvac_mode
        hvac_mode: cool
    action_button_right_short:
      - device_id: 27bdff06a2df61d41f4095a2c995c8e3
        domain: climate
        entity_id: climate.guest_room_ac
        type: set_hvac_mode
        hvac_mode: heat
    action_button_left_long:
      - device_id: 27bdff06a2df61d41f4095a2c995c8e3
        domain: climate
        entity_id: climate.guest_room_ac
        type: set_hvac_mode
        hvac_mode: 'off'
    action_button_right_long:
      - device_id: 27bdff06a2df61d41f4095a2c995c8e3
        domain: climate
        entity_id: climate.guest_room_ac
        type: set_hvac_mode
        hvac_mode: 'off'
    action_button_up_long:
      - service: climate.set_temperature
        data:
          temperature: '{{ states.climate.guest_room_ac.attributes.temperature + 1 }}'
        target:
          entity_id: climate.guest_room_ac
    action_button_down_long:
      - service: climate.set_temperature
        data:
          temperature: '{{ states.climate.guest_room_ac.attributes.temperature - 1 }}'
        target:
          entity_id: climate.guest_room_ac
    helper_debounce_delay: 1000
    helper_double_press_delay: 250
```

### Implementation

Probably a new configurable field should be added "long press repeat delay" or "long press repeat interval"

### Additional Details

- [ ] I'd like to help developing this feature/improvement.
