### ISSUE TITLE
Bug - 

### ISSUE THREAD

**Issue by r3mcos3** [EPMatt/awesome-ha-blueprints#341]
### Blueprint name

blueprint generate invalid automation E1810

### Home Assistant Core Version

2022.7.0.dev20220527

### Home Assistant Installation Type

Home Assistant Container

### Description

Blueprint generate a invalid automation 

### Automation YAML config

```yaml
- id: '1653409956101'
  alias: Remote - Woonkamer
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1524_e1810.yaml
    input:
      integration: Zigbee2MQTT
      controller_entity: sensor.remote_woonkamer_action
      helper_last_controller_event: input_text.helper_e1810
      action_button_left_short:
      - service: light.toggle
        data:
          brightness_pct: 100
        target:
          entity_id: light.tuin_lampen
      action_button_right_short:
      - service: light.toggle
        data:
          brightness_pct: 100
        target:
          entity_id: light.patio
      action_button_up_short:
      - type: toggle
        device_id: 4a2b72f0f45e6c51642e36d43ea5e32c
        entity_id: light.keuken
        domain: light
      action_button_center_short:
      - service: light.toggle
        data:
          brightness_pct: 100
        target:
          entity_id: light.woonkamer_spotjes
      action_button_down_short:
      - service: cover.toggle
        data: {}
        target:
          entity_id: cover.rolluiken
```

### To Reproduce

a restart of home assistant throws this error,

automation is still working

### Expected behavior

that it produce a valid automation.

no error in log 

### Actual Behaviour

throws errors at home assistant start up

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Additional context

`Logger: homeassistant.components.automation
Source: components/automation/__init__.py:651
Integration: Automation (documentation, issues)
First occurred: 06:00:43 (1 occurrences)
Last logged: 06:00:43

Blueprint Controller - IKEA E1524/E1810 TRÅDFRI Wireless 5-Button Remote generated invalid automation with inputs OrderedDict([('integration', 'Zigbee2MQTT'), ('controller_entity', 'sensor.remote_woonkamer_action'), ('helper_last_controller_event', 'input_text.helper_e1810'), ('action_button_up_short', [OrderedDict([('type', 'toggle'), ('device_id', '4a2b72f0f45e6c51642e36d43ea5e32c'), ('entity_id', 'light.keuken'), ('domain', 'light')])]), ('action_button_center_short', [OrderedDict([('service', 'light.toggle'), ('data', OrderedDict([('brightness_pct', 75)])), ('target', OrderedDict([('entity_id', 'light.woonkamer_spotjes')]))]), OrderedDict([('device_id', ''), ('domain', ''), ('entity_id', '')])])]): Integration '' not found. Got <homeassistant.components.blueprint.models.BlueprintInputs object at 0x7f1f2e8b5370>`
