### ISSUE TITLE
Bug - Updated IKEA controller ZHA args

### ISSUE THREAD

**Issue by denilsonsa** [EPMatt/awesome-ha-blueprints#357]
### Blueprint name

controllers/ikea_e1743

### Home Assistant Core Version

2022.6.6

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Starting sometime in 2022, the ZHA started having two extra trailing zeros on certain ZHA events. This has also been reported to `controllerx` project, and they have fixed it over there: https://github.com/xaviml/controllerx/commit/d68a1405b8311167b9b60dd32e591054f4ab1380

Thus, this bug here is to migrate that fix to this project. Possibly co-existing both the old args and the new args, just for backwards compatibility for people still running the older version.

### Automation YAML config

```yaml
-
```

### To Reproduce

1. Use the [IKEA E1743 TRÅDFRI On/Off Switch & Dimmer](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e1743/) controller.
    * This issue also applies to other IKEA controllers.
3. Configure everything as needed, either by setting individual actions or by hooking a hook.
4. Try using the controller. Especially, try the long-press commands.
5. BONUS: Use the developer tools to listen for `zha_event`.

### Expected behavior

It should work.

### Actual Behaviour

It doesn't work. No error, no notification, no action.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Additional context

Example event:

```json
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "…",
        "unique_id": "…",
        "device_id": "…",
        "endpoint_id": 1,
        "cluster_id": 8,
        "command": "move",
        "args": [
            1,
            83,
            0,
            0
        ],
        "params": {
            "move_mode": 1,
            "rate": 83,
            "options_mask": 0,
            "options_override": 0
        }
    },
    "origin": "LOCAL",
    "time_fired": "2022-06-27T14:33:57.722266+00:00",
    "context": {
        "id": "…",
        "parent_id": null,
        "user_id": null
    }
}
```

**Comment by ced455** [comment]
Same here, here is some more détails :

Up long press
``` yml
event_type: zha_event
data:
  device_ieee: 0c:43:14:ff:fe:68:bc:93
  unique_id: 0c:43:14:ff:fe:68:bc:93:1:0x0008
  device_id: 15c1c15df1d99e2072d5fef2a762a484
  endpoint_id: 1
  cluster_id: 8
  command: move_with_on_off
  args:
    - 0
    - 83
  params:
    move_mode: 0
    rate: 83
origin: LOCAL
time_fired: "2022-09-14T18:56:53.724913+00:00"
context:
  id: 01GCYNRXYWEG8Z7TMJ1K4S7PCN
  parent_id: null
  user_id: null
```

up release
``` yml
event_type: zha_event
data:
  device_ieee: 0c:43:14:ff:fe:68:bc:93
  unique_id: 0c:43:14:ff:fe:68:bc:93:1:0x0008
  device_id: 15c1c15df1d99e2072d5fef2a762a484
  endpoint_id: 1
  cluster_id: 8
  command: stop_with_on_off
  args: []
  params: {}
origin: LOCAL
time_fired: "2022-09-14T18:56:55.723750+00:00"
context:
  id: 01GCYNRZXB32S1ET3VXTZZF5VA
  parent_id: null
  user_id: null
```

down long press
``` yml
event_type: zha_event
data:
  device_ieee: 0c:43:14:ff:fe:68:bc:93
  unique_id: 0c:43:14:ff:fe:68:bc:93:1:0x0008
  device_id: 15c1c15df1d99e2072d5fef2a762a484
  endpoint_id: 1
  cluster_id: 8
  command: move
  args:
    - 1
    - 83
    - 0
    - 0
  params:
    move_mode: 1
    rate: 83
    options_mask: 0
    options_override: 0
origin: LOCAL
time_fired: "2022-09-14T18:56:57.998713+00:00"
context:
  id: 01GCYNS24EJSNDGJ161WZG488Z
  parent_id: null
  user_id: null
```

down release
``` yml
event_type: zha_event
data:
  device_ieee: 0c:43:14:ff:fe:68:bc:93
  unique_id: 0c:43:14:ff:fe:68:bc:93:1:0x0008
  device_id: 15c1c15df1d99e2072d5fef2a762a484
  endpoint_id: 1
  cluster_id: 8
  command: stop_with_on_off
  args: []
  params: {}
origin: LOCAL
time_fired: "2022-09-14T18:56:59.002582+00:00"
context:
  id: 01GCYNS33TTKJW4DWKD4FZAN9E
  parent_id: null
  user_id: null
```


I tried to edit the blueprint, without sucess, I am not too experienced on the subject.

Thanks for the help !
