### ISSUE TITLE
Bug -  error after upgrade to ja 2022.07

### ISSUE THREAD

**Issue by Delta1977** [EPMatt/awesome-ha-blueprints#362]
### Blueprint name

Hook-light 

### Home Assistant Core Version

2022.07

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Logger: homeassistant.components.automation.hook_light_schlafzimmer
Source: components/automation/__init__.py:525 
Integration: Automatisierung ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22)) 
First occurred: 21:53:33 (6 occurrences) 
Last logged: 21:58:40

Error while executing automation automation.hook_light_schlafzimmer: Error rendering data template: ValueError: Template error: int got invalid input 'None' when rendering template '{{ [state_attr(light,"color_temp")|int - 50, 1]|max }}' but no default was specified
Error while executing automation automation.hook_light_schlafzimmer: Error rendering data template: ValueError: Template error: int got invalid input 'None' when rendering template '{{ state_attr(light,"color_temp")|int + 50 }}' but no default was specified

### Automation YAML config

```yaml
alias: Hook - Light Schlafzimmer
description: ''
use_blueprint:
  path: EPMatt/light.yaml
  input:
    light_color_mode: Auto
    controller_device: 36ed4a3945985b599e82e025eca8af66
    controller_entity: sensor.ikea_taster_schlafzimmer_action
    controller_model: IKEA E2001/E2002 STYRBAR Remote control
    light: light.ikea_lampe_schlafzimmer
    smooth_power_off: true
```

### To Reproduce

3. Trigger the automation '....'

### Expected behavior

.

### Actual Behaviour

.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

**Comment by YAMLcase** [comment]
I am seeing this same error.  More info perhaps to help troubleshoot:
I have the following:

- [Sylvania 73741 LIGHTIFY LED](https://www.zigbee2mqtt.io/devices/73741.html#sylvania-73741) downlights on firmware version "Jan 7 2019" (latest in z2m OTA link)
- [Philips 324131092621 Hue Dimmer switch](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/philips_324131092621)
- [Blueprint of the same name as controller](https://github.com/EPMatt/awesome-ha-blueprints/blob/main/blueprints/controllers/philips_324131092621/philips_324131092621.yaml)
- [light hook](https://github.com/EPMatt/awesome-ha-blueprints/blob/main/blueprints/hooks/light/light.yaml)
- zigbee2mqtt:latest as of this week
- mosquitto:latest as of this week
- home-assistant:latest as of this week

The light takes either `color_temp, color_hs, or color_xy`.  I have been able to demonstrate when the light's current color_mode is `color_xy` and the hook's Light Color Mode is set to "Color Temperature", sending an action to color_up or color_down will result in the failure.  Any other combination will not show the error. 

I have narrowed it down to this block, but am getting into details I'm not understanding yet:
```
action:
  - choose:
      - conditions: '{{ action == color_up and light_color_mode_id != "none" }}'
        sequence:
          choose:
            - conditions: '{{ light_color_mode_id == "color_temp" }}'
              sequence:
                - service: light.turn_on
                  data:
                    color_temp: '{{ state_attr(light,"color_temp")|int + 50 }}'
                    transition: 0.25
                  entity_id: !input light
```

**Comment by YAMLcase** [comment]
@Delta1977 with my issue I discovered the light does not provide `color_temp: <int>` when the state was last set with a color.  
```diff
diff --git temp hs
supported_color_modes:
 friendly_name: office/lights/main02
 supported_features: 63
 color:
  x: 0.348
  'y': 0.368
last_seen: '2022-09-04T14:56:53.694Z'
 level_config:
   on_level: previous
linkquality: 102
 update:
   state: idle
 update_available: false
-color_mode: color_temp
+color_mode: xy
 brightness: 255
 hs_color:
  - 58.421
  - 14.902
 rgb_color:
   - 255
  - 254
  - 217
 xy_color:
  - 0.482
  - 0.38
-color_temp: 316
```

Given `'state_attr(light,"color_temp")... no default was specified`, I'm on the hunt on how to either give a default value for this bit or add some conditionals.  I'm just learning the Home Assistant templating syntax, so any pointers would be greatly appreciated @EPMatt @kingy444

**Comment by YAMLcase** [comment]
update: I think I solved my issue at least.   I'm basically calculating a good color_temp based on current brightness and using that if `color_temp` is missing.

```yaml
      - conditions: '{{ action == color_up and light_color_mode_id != "none" }}'
        sequence:
          choose:
            - conditions: '{{ light_color_mode_id == "color_temp" }}'
              sequence:
                - service: light.turn_on
                  data:
                    color_temp: >-
                      '{%- if state_attr(light,"color_temp") != None -%}
                        {{ state_attr(light,"color_temp")|int + 50 }}
                      {%- else -%}
                        {{ 500 - state_attr(light,"brightness")|int}}
                      {%- endif -%}'
                    transition: 0.25
                  entity_id: !input light
```
