### ISSUE TITLE
Bug - 

### ISSUE THREAD

**Issue by summed** [EPMatt/awesome-ha-blueprints#367]
### Blueprint name

Condition always false

### Home Assistant Core Version

2022.6.5

### Home Assistant Installation Type

Home Assistant Container

### Description

Condition is always false when using zigbee2mqtt.

      - '{{ integration_id != "zigbee2mqtt" or trigger.event.data.new_state.state != trigger.event.data.old_state.state }}'

If I tamper with this to make it resolve, the BP works fine. Otherwise always false.

### Automation YAML config

```yaml
condition:
  - condition: and
    conditions:
      # check that the button event is not empty
      - >-
        {%- set trigger_action -%}
        {%- if integration_id == "zigbee2mqtt" -%}
        {{ trigger.event.data.new_state.state }}
        {%- elif integration_id == "deconz" -%}
        {{ trigger.event.data.event }}
        {%- elif integration_id == "zha" -%}
        {{ trigger.event.data.command }}
        {%- endif -%}
        {%- endset -%}
        {{ trigger_action not in ["","None"] }}
      # only for zigbee2mqtt, check if the event is relative to a real state change, and not only some minor changes in the sensor attributes
      # this is required since multiple state_changed events are fired for a single button press, with the result of the automation being triggered multiple times
      - '{{ integration_id != "zigbee2mqtt" or trigger.event.data.new_state.state != trigger.event.data.old_state.state }}'
```

### To Reproduce

3. Trigger the automation '....'

### Expected behavior

That the trigger fires and the bp works with zigbee2mqtt

### Actual Behaviour

always stops with a false condition

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

**Comment by kahancock** [comment]
Just starting trying to use this blueprint and can confirm same behavior.

**Comment by EPMatt** [comment]
⚠️ Important announcement about the project: #371 ⚠️ 

I'd like to kindly ask for your feedback about our work here. If you have time, please answer the poll in the above discussion. This will help shaping the future of Awesome HA Blueprints. 🚀 

Thank you!

**Comment by EPMatt** [comment]
Hi @summed @kahancock, thank you for reporting here.

Can you please share the name of the blueprint you're experiencing issues with? 
Furthermore, can you please provide the full YAML configuration for the automation? I'm afraid it would be hard to solve your issue without having such information.

Moreover, I noticed that you're using Zigbee2MQTT. Please note that we're using legacy Home Assistant triggers to detect button clicks for Z2M ([docs](https://www.zigbee2mqtt.io/guide/usage/integrations/home_assistant.html#via-home-assistant-entity)). Our blueprints currently do not support device triggers.
Please make sure you've the `legacy_triggers` option set to `true` (default value) in the Z2M configuration for controller blueprints to work.

Thanks!

**Comment by summed** [comment]
@EPMatt Hi Matteo, sorry for the missinformation. I have update the ticket a bit. The bp seems to be working without issue atm, when I have changed the condition a bit.

```yaml
- condition: and
  conditions:
  - '{%- set trigger_action -%} {%- if integration_id == "zigbee2mqtt" -%} {{ trigger.event.data.new_state.state
    }} {%- elif integration_id == "deconz" -%} {{ trigger.event.data.event }} {%-
    elif integration_id == "zha" -%} {{ trigger.event.data.command }} {%- endif -%}
    {%- endset -%} {{ trigger_action not in ["","None"] }}'
  - '{{ **integration != "Zigbee2MQTT"** or trigger.event.data.new_state.state != trigger.event.data.old_state.state }}'
```
