### ISSUE TITLE
Bug - Philips Hue Dimmer V2 Short click doesn't trigger ahb_controller_event

### ISSUE THREAD

**Issue by HeimdallMidgard** [EPMatt/awesome-ha-blueprints#369]
### Blueprint name

Controller - Philips 929002398602 Hue Dimmer switch v2

### Home Assistant Core Version

2022.7.5

### Home Assistant Installation Type

Home Assistant Supervised

### Description

The Philips Hue Dimmer V2 has two different ways to be pushed for "on_press". The slightly longer one works as expected and triggers the ahb_controller_event. The slightly shorter one (just a few 100 ms) also triggers on_press_release which seems to change the automation or stops the ahb_controller_event. **I do not talk about long press**

### Automation YAML config

```yaml
alias: '[Wohnzimmer][Light][Controller] Deckenlicht'
description: ''
use_blueprint:
  path: EPMatt/philips_929002398602.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.wohnzimmer_schalter_deckenlampe_action
    helper_last_controller_event: input_text.controller_wohnzimmer_schalter_deckenlicht
    helper_double_press_delay: 250
```

### To Reproduce

1. Use blueprint
2. Click just slightly on the on button (little longer works)
3. Light is not beeing turned on

### Expected behavior

Turn on light while short clicking on

### Actual Behaviour

Light is not beeing turned on.

### Additional Details

- [X] I'd like to help developing a fix for this issue.

### Screenshots

Longer click (working):
![grafik](https://user-images.githubusercontent.com/50184150/179834825-118b3e72-7243-47db-a394-1425300b4050.png)

Shorterclick (not working):
![grafik](https://user-images.githubusercontent.com/50184150/179834855-2ab4dbe3-fb32-4b0d-9479-b33ac3f2708e.png)
