### ISSUE TITLE
Bug - Controller for Ikea E1810 (5 Button remote) - double press / long press not recognized anymore

### ISSUE THREAD

**Issue by hindseb** [EPMatt/awesome-ha-blueprints#375]
### Blueprint name

Controller - IKEA E1524/E1810 TRÅDFRI Wireless 5-Button Remote

### Home Assistant Core Version

2022.7.6

### Home Assistant Installation Type

Home Assistant Supervised

### Description

Double click or long-press actions are not recognized anymore. Instead, the short press action is always used. 

In the below example, I have different actions for the center button. 

### Automation YAML config

```yaml
alias: Controller - IKEA E1524/E1810 TRADFRI Wireless 5-Button Remote
description: ''
use_blueprint:
  path: EPMatt/ikea_e1524_e1810.yaml
  input:
    integration: deCONZ
    controller_device: 0e4f21c18de5824caeefb57837147d23
    helper_last_controller_event: input_text.ikea_remote_last_event
    action_button_center_short:
      - service: rest_command.pee_and_or_poop
        data:
          wet_bool: 'true'
          solid_bool: 'true'
      - service: notify.alexa_media
        data:
          target: media_player.sebastian_s_echo_dot
          message: Pee and Poop recorded
          data:
            type: tts
    action_button_left_short:
      - service: rest_command.feedings
        data:
          feeding_type: breast milk
          feeding_method: both breasts
      - service: notify.alexa_media
        data:
          target: media_player.sebastian_s_echo_dot
          message: Breast feeding recorded
          data:
            type: tts
    action_button_up_short:
      - service: rest_command.pee_and_or_poop
        data:
          wet_bool: 'false'
          solid_bool: 'true'
      - service: notify.alexa_media
        data:
          target: media_player.sebastian_s_echo_dot
          message: Poop recorded
          data:
            type: tts
    action_button_up_long: []
    action_button_up_double: []
    action_button_down_short:
      - service: rest_command.pee_and_or_poop
        data:
          wet_bool: 'true'
          solid_bool: 'false'
      - service: notify.alexa_media
        data:
          target: media_player.sebastian_s_echo_dot
          message: Pee recorded
          data:
            type: tts
    action_button_right_short:
      - service: rest_command.feedings
        data:
          feeding_type: formula
          feeding_method: bottle
      - service: notify.alexa_media
        data:
          target: media_player.sebastian_s_echo_dot
          message: Formula feeding recorded
          data:
            type: tts
    action_button_center_long:
      - service: media_player.play_media
        data:
          media_content_id: http://www.babysleepsite.com/downloads/noise-and-heartbeat.mp3
          media_content_type: Music
        target:
          entity_id:
            - media_player.soundtouch_living_room
    action_button_center_double:
      - service: media_player.play_media
        data:
          media_content_id: http://www.babysleepsite.com/downloads/noise-and-heartbeat.mp3
          media_content_type: Music
        target:
          entity_id:
            - media_player.soundtouch_living_room
```

### To Reproduce

Create automation with different actions for short, long, and double press. Here, e.g. for the center button.

### Expected behavior

Execute different actions based on short, long, double-press

### Actual Behaviour

Always the short-press action is executed. I.e., when double pressing, I get twice the action of the short press.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
