### ISSUE TITLE
Bug - Philips 324131092621 Hue Dimmer switch loop too quickly

### ISSUE THREAD

**Issue by mguaylam** [EPMatt/awesome-ha-blueprints#379]
### Blueprint name

Controller - Philips 324131092621 Hue Dimmer switch

### Home Assistant Core Version

2022.7.0

### Home Assistant Installation Type

Home Assistant Container

### Description

Hello!

First, thank you for such amazing Blueprints, it really has changed the way I can use my ZigBee devices!

I’m having an issue with the Controller - Philips 324131092621 Hue Dimmer switch blueprint where it iterates far too quickly into the dim loop :

- The number of events generated by the remote is the same as other remotes of the same model and also the same as the new 929002398602 Philips Hue remote (de-bouncing would / has no effect).
- The loop iterates as quickly as HA can (as much as 62 times with only one ZHA event) with the blueprint 324131092621 compared with 929002398602 as it has no delay :
![Philips Hue](https://user-images.githubusercontent.com/16389438/182044257-e49799f5-036c-46c6-8c82-818b81673ab7.png)

### Automation YAML config

```yaml
alias: Télécommande pièce secrète lit
description: ''
use_blueprint:
  path: EPMatt/philips_324131092621.yaml
  input:
    integration: ZHA
    controller_device: 43d5d0b4d8d38e3357f1e0a330d34306
    action_button_on_short:
      - service: light.turn_on
        data: {}
        target:
          entity_id: light.lumieres_piece_secrete
    action_button_off_short:
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.lumieres_piece_secrete
    action_button_up_short:
      - service: light.turn_on
        data:
          transition: 1
          brightness_step_pct: 10
        target:
          entity_id: light.lumieres_piece_secrete
    action_button_up_long:
      - service: light.turn_on
        data:
          transition: 1
          brightness_step_pct: 10
        target:
          entity_id: light.lumieres_piece_secrete
    action_button_down_short:
      - service: light.turn_on
        data:
          transition: 1
          brightness_step_pct: -10
        target:
          entity_id: light.lumieres_piece_secrete
    action_button_down_long:
      - service: light.turn_on
        data:
          transition: 1
          brightness_step_pct: -10
        target:
          entity_id: light.lumieres_piece_secrete
    button_on_long_loop: false
    button_off_long_loop: false
    button_up_long_loop: true
    button_down_long_loop: true
    helper_last_controller_event: input_text.telecommande_piece_secrete_lit
    helper_debounce_delay: 0
```

### To Reproduce

Press and hold up or down light intensity on the remote.

### Expected behavior

The lights dim smootlhy

### Actual Behaviour

The ZigBee network get overloaded of events and the lights dim from 0 to 100% immediately.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
