### ISSUE TITLE
Bug - Hook light using light color mode while set to none

### ISSUE THREAD

**Issue by TFhdKi95ae8L** [EPMatt/awesome-ha-blueprints#383]
### Blueprint name

Hook - light

### Home Assistant Core Version

2022.7.7

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Using an IKEA E2002 for dimmable only light group via Z2M.
Set light color mode to none, to be able to use left and right buttons for other purposes.
While long pressing right button, the light group does switch on though. All other possible presses on left or right do not control the light group (as intended)

### Automation YAML config

```yaml
alias: Controller - IKEA E2001/E2002 STYRBAR Remote control
description: ''
use_blueprint:
  path: EPMatt/ikea_e2001_e2002.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.ikea_dimmer_knop_action
    helper_last_controller_event: input_text.ikeadimmerhelper
    action_button_up_short: []
    action_button_down_short: []
    action_button_up_long: []
    action_button_left_short:
      - service: cover.close_cover
        data: {}
        target:
          device_id: 748ebcb73cb88cfecc6853d6529cf996
    action_button_left_double:
      - service: cover.open_cover
        data: {}
        target:
          device_id: 748ebcb73cb88cfecc6853d6529cf996
    button_left_double_press: true
    button_right_double_press: true
    action_button_right_short:
      - service: media_player.toggle
        data: {}
        target:
          device_id: 89a0e0185fb71730ecbc496e26540f82
    action_button_right_long:
      - service: script.netflix
        data: {}
    action_button_right_double:
      - service: script.youtube
        data: {}


alias: Hook - Light
description: ''
use_blueprint:
  path: EPMatt/light.yaml
  input:
    controller_device: 4a99f5edc69f7ad59a2fc63f4391edf4
    controller_model: IKEA E2001/E2002 STYRBAR Remote control
    controller_entity: sensor.ikea_dimmer_knop_action
    light_color_mode: None
    light: light.woonkamer
```

### To Reproduce

Use right button on Styrbar E2002 with Controller - IKEA E2001/E2002 STYRBAR Remote control and Hook - Light with color mode set to none.

### Expected behavior

No action on light with color mode to none and using left and / or right buttons (specifically right long press)

### Actual Behaviour

Switching of light with right long press

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Additional context

Executed: 3 August 2022 at 10:42:13
Result:
params:
  domain: light
  service: turn_on
  service_data:
    transition: 0.25
    entity_id:
      - light.woonkamer
  target:
    entity_id:
      - light.woonkamer
running_script: false
limit: 10
