### ISSUE TITLE
Osram Smart+ Mini Switch broadcasting and turning all other Osram devices on (Plugs, Light bulbs, LED Strips etc.)

### ISSUE THREAD

**Issue by Secoashimself** [EPMatt/awesome-ha-blueprints#385]
### Blueprint name

Controller - OSRAM AC025XX00NJ SMART+ Switch Mini

### Home Assistant Core Version

2022.08.1

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Pairing of Osram mini switch without any problems in ZHA via Sonoff Zigbee Dongle. Pressing upper button turns all Osram lights, led stripes and plugs on, pressing down turns all of them off. The implemented automations from your blueprint are working in parallel. For Example: If I bind opening/closing of my the window covers every time all the other Osram devices turn on/off. I am probably not the only one, because the broadcasting problem was already discussed [here](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/294) and [here](https://github.com/Koenkk/zigbee2mqtt/issues/962) even though these are different integration. 
Is there a way to disable or delete this behaviour? Thanks!

### Automation YAML config

```yaml
- id: '1659650612687'
  alias: Controller - OSRAM AC025XX00NJ SMART+ Switch Mini
  description: ''
  use_blueprint:
    path: EPMatt/osram_ac025xx00nj.yaml
    input:
      helper_last_controller_event: input_text.osramswitchmini
      controller_device: fed1ba38f3963d048a4657f494358303
      action_button_up_short:
      - type: turn_on
        device_id: 47c245670ac8b0471e8c77372f4d1c1b
        entity_id: switch.led_bett_81b0010a_on_off
        domain: switch
      action_button_up_long:
      - service: script.alle_rollos_auf
        data: {}
      action_button_down_long:
      - service: script.alle_rollos_zu
        data: {}
      action_button_down_short:
      - type: turn_off
        device_id: 47c245670ac8b0471e8c77372f4d1c1b
        entity_id: switch.led_bett_81b0010a_on_off
        domain: switch
      action_button_center_short:
      - device_id: 6a1129fcc024ee205e778478713ae0b9
        domain: cover
        entity_id: cover.rollos_im_schlafzimmer_curtain_2
        type: open
      action_button_center_long:
      - device_id: 6a1129fcc024ee205e778478713ae0b9
        domain: cover
        entity_id: cover.rollos_im_schlafzimmer_curtain_2
        type: close
      integration: ZHA
```

### To Reproduce

1. Have other Osram devices connected in ZHA
2. Pair Osram mini switch 
3. Be connected 
4. Press upper arrow: All Osram devices turn on
5. Press lower arrow: All Osram devices turn off
6. Independently of your blueprint the broadcasting is still happening

### Expected behavior

No broadcasting of turning all Osram devices on/off

### Actual Behaviour

Broadcasting of turning all Osram devices on/off, even though it is not selected.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Additional context

Hello,

fIrst, thank you for implementing all these blueprints for all controllers. I very much appreciate you work! I have a request regarding the Osram Switch blueprint. I do have the Osram Switch and Switch Mini and wanted to integrate and use them in my home assistant environment. I paired them with my Raspberry Pi 4 and Sonoff Zigbee USB Dongle in my HAOS. The Mini is supported right now, the implementation of the bigger 4x Switch is already requested some month ago by someone else.
