### ISSUE TITLE
Bug - Ikea E2002 Styrbar Brightness/Up,Down Hold action doesn't work

### ISSUE THREAD

**Issue by LewisSpring** [EPMatt/awesome-ha-blueprints#399]
### Blueprint name

Controller - IKEA E2001/E2002 STYRBAR Remote control

### Home Assistant Core Version

2022.8.7

### Home Assistant Installation Type

Home Assistant Container

### Description

The remote works perfectly using **both the hook and automation blueprints**, except for the up and down button hold action, which does not do anything.

### Automation YAML config

```yaml
alias: Hook - Light
description: ""
use_blueprint:
  path: EPMatt/light.yaml
  input:
    controller_device: xxxx
    controller_model: IKEA E2001/E2002 STYRBAR Remote control
    light: light.ikea
    light_color_mode: Hue - Saturation
    brightness_steps_short: 20
    brightness_steps_long: 5
```

### To Reproduce

Press and hold either up or down button. 

### Expected behavior

Hook automation controls the brightness of the bulb.

### Actual Behaviour

No changes to the bulb brightness.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

**Comment by ioExpander** [comment]
Hi. I had the same issue and it seems that your proposal [here](https://gist.github.com/LewisSpring/b0e625f91971dc3df4aa5c270662715b) is working fine. I'm going to run some more tests to confirm. Do you want to open a PR to help fix the issue for everyone using this repo ? Otherwise I could do it.

**Comment by crazytil** [comment]
I am having the same issue with an e1810. Any ideas on how to fix it?

**Comment by klemmari1** [comment]
> Edit: I wasn't entirely sure how to implement the release action fix, I've not made that change. Please feel free to have a go.

https://github.com/EPMatt/awesome-ha-blueprints/compare/main...klemmari1:awesome-ha-blueprints:fix-holding?expand=1

**Comment by Ragingfire105** [comment]
> > Edit: I wasn't entirely sure how to implement the release action fix, I've not made that change. Please feel free to have a go.
> 
> Fixed the release action in my fork but works only on ZHA and probably breaks the other integrations: [main...fd61dd0](https://github.com/EPMatt/awesome-ha-blueprints/compare/main...fd61dd034aa785bb851623e0a92c0167444fd46e)
> 
> Direct link to file if you want to try the blueprint: https://github.com/klemmari1/awesome-ha-blueprints/blob/fix-holding/blueprints/controllers/ikea_e2001_e2002/ikea_e2001_e2002.yaml
> 
> Credit to Luis Sismeiro for figuring it out in: https://community.home-assistant.io/t/zha-deconz-zigbee2mqtt-ikea-e2001-e2002-styrbar-remote-control-universal-blueprint-all-actions-double-click-events-control-lights-media-players-and-more-with-hooks/354176/18

Thank you for this temp fix.  I have been fighting this for over an hour.

**Comment by JamieBriers** [comment]
I bought some of these Styrbars last night and have been fighting this all morning! Finally thought to check the GitHub issues. 

Could you advise on what the current best solution is, and how to implement it?

Thanks!

**Comment by klemmari1** [comment]
> I didn't mention it on this issue, but I am having issues with the left/right hold actions - same issue, it doesn't stop if you release. If anybody else experiences this, I can create a second issue to report this - or we can continue it here.

Hmm, for me the left/right hold actions work without issues. What's your config on the controller blueprint? Do you have the "Last Controller Event" helper defined? Do you use double tap actions?

**Comment by klemmari1** [comment]
> Could you advise on what the current best solution is, and how to implement it?

What's your issue exactly? If you want to try out the blueprint, just go to blueprints in HA and click "Import Blueprint"

**Comment by simon-mettler** [comment]
Tested it (the updated version from @lsismeiro), works fine for me :+1:  Thank you :)

**Comment by lsismeiro** [comment]
> Tested it (the updated version from @lsismeiro), works fine for me 👍 Thank you :)
Good to know that is working fine for you and the hours (I'm not a developer) I invested in it are helpful for someone else. Besides myself I don't know anyone who has used it, thank you for testing it.

**Comment by lsismeiro** [comment]
> Yep, Can concur! Thanks Luis. I'm very interested in pushing for this to be pulled. (#411) I've updated the pull request with your code if that's alright with you?

I'm glad it works for more people than me. Please update the pull request with my code so everybody can benefit from the fix.

**Comment by klemmari1** [comment]
Btw, the holding "got stuck" again for me.

Eventually I got it working again by increasing the max lenghth of the last controller event helper to 500. By default it is 100 characters which was not enough to store the hold up or down button text so it failed to save it.

**Comment by soxhi8** [comment]
Still having issues with this, with my Zigbee2MQTT setup and the latest fix version from the forum (https://community.home-assistant.io/t/zha-deconz-zigbee2mqtt-ikea-e2001-e2002-styrbar-remote-control-universal-blueprint-all-actions-double-click-events-control-lights-media-players-and-more-with-hooks/354176/35) and max helper length set to 255.

Long press actions do loop, but show huge delays, not matter the step size or call-type (brightness change for device directly or light-service). It is not smooth at all. Does someone have it up and running smoothly at the moment?

**Comment by giraz82** [comment]
> Still having issues with this, with my Zigbee2MQTT setup and the latest fix version from the forum (https://community.home-assistant.io/t/zha-deconz-zigbee2mqtt-ikea-e2001-e2002-styrbar-remote-control-universal-blueprint-all-actions-double-click-events-control-lights-media-players-and-more-with-hooks/354176/35) and max helper length set to 255.
> 
> Long press actions do loop, but show huge delays, not matter the step size or call-type (brightness change for device directly or light-service). It is not smooth at all. Does someone have it up and running smoothly at the moment?

I also have loop issue on long press for up/down button.
Associated light via hook goes to 100% or 0%, even if I release the button just after long press is triggered.
I tried to check `(Optional) Up button long press - loop until release` with no luck.
Any suggestion would be appreciated.

**Comment by giraz82** [comment]
Ok I think this is the solution: https://github.com/EPMatt/awesome-ha-blueprints/pull/546
Thanks to @LordSushiPhoenix

**Comment by bit111** [comment]
Hi,
I read all posts, tried to import edited version of @LewisSpring (https://github.com/LewisSpring/awesome-ha-blueprints/blob/380130b3a8b87037402b0f1da55e93635737804f/blueprints/controllers/ikea_e2001_e2002/ikea_e2001_e2002.yaml) and increased to 255 my input_text helper but up/down long press button still don't work.
I am using HA Core 2023..4.4.

How can I solve this issue?

**Comment by bit111** [comment]
@LewisSpring where can I find the full path to the yaml? in ([#411](https://github.com/EPMatt/awesome-ha-blueprints/pull/411)) fix I cannot find the code.
Finally, can you tell me where version of your code works with 2023.4 HA version?
Thanks.

**Comment by MikeGuest** [comment]
Hi.

Thanks for your work on this. I'm definitely seeing an improvement. However I have a strange issue.

I'm just using a standard hold action (not loop) and while the up hold is now working (it wasn't originally) the down hold still does nothing. i'm calling service light.turn_off - the same call is working if i assign it to the right button.

I'm running the E2002 version of the styrbar

Any clues or any information I can give you to help you to advise please?

HA: 2023.7.1

Thanks

**Comment by eugeugov** [comment]
https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fgithub.com%2Flsismeiro%2Fawesome-ha-blueprints%2Fblob%2Fmain%2Fblueprints%2Fcontrollers%2Fikea_e2001_e2002%2Fikea_e2001_e2002.yaml

**Comment by neuronflow** [comment]
> Tested Ikea e2002 in ZHA and working as it should (incl. long press UP/DOWN) https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fgithub.com%2Flsismeiro%2Fawesome-ha-blueprints%2Fblob%2Fmain%2Fblueprints%2Fcontrollers%2Fikea_e2001_e2002%2Fikea_e2001_e2002.yaml

I used this, and tried to increase / decrease brightness by holding the up/down button:
```
alias: lr_styrbar_dim
description: ""
use_blueprint:
  path: lsismeiro/ikea_e2001_e2002 (2023 version).yaml
  input:
    integration: Zigbee2MQTT
    controller_device: 8b42b1e00a6fa4752381304aa7f66f3c
    controller_entity: sensor.lr_styrbar_action
    helper_last_controller_event: input_text.lr_styrbar_last_action
    button_down_long_loop: true
    button_up_long_loop: true
    action_button_left_short:
      - service: light.toggle
        metadata: {}
        data:
          kelvin: 2000
          brightness_pct: 100
        target:
          device_id: d89fcfb052e124eae8e11e8378f0014f
    action_button_right_short:
      - service: light.toggle
        metadata: {}
        data: {}
        target:
          device_id: 7bb23a40ddfb723d79a6c98f031c206e
    action_button_up_short:
      - service: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: 5
        target:
          device_id: d89fcfb052e124eae8e11e8378f0014f
    action_button_down_short:
      - service: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: -5
        target:
          device_id: d89fcfb052e124eae8e11e8378f0014f
    helper_double_press_delay: 100
    helper_debounce_delay: 100

```

What am I doing wrong?
