### ISSUE TITLE
[SUGGESTION] TRADFRI shortcut button (IKEA E1812)

### ISSUE THREAD

**Issue by ShagoY** [EPMatt/awesome-ha-blueprints#4]
**Description**

ZHA, deCONZ, Zigbee2MQTT - Ikea E1812 shortcut button Universal blueprint - all actions - control lights, media players and more with Hooks

**Additional Details**

- [X] I've found a blueprint/automation not included in this project which achieves the same/similar goal
  - [ZHA - IKEA Tradfri Shortcut button](https://community.home-assistant.io/t/zha-ikea-tradfri-shortcut-button/261936)
  - [ZHA - IKEA Tradfri Shortcut button debounced](https://community.home-assistant.io/t/zha-ikea-tradfri-shortcut-button-debounced/265921)
  - [deCONZ - Ikea Tradfri Shortcut Button](https://community.home-assistant.io/t/deconz-ikea-tradfri-shortcut-button/282684)

**Additional Details**

[IKEA E1812](https://www.zigbee2mqtt.io/devices/E1812.html#ikea-e1812)

**Comment by ShagoY** [comment]
Hi :)

I just discovered your Blueprints.

I'm currently using the ones for E1743 and E1744 on Zigbee2MQTT, especially for the double-tap/long-tap functions, it's just perfect!

Now my Tradfri Shortcut would like the same treatment :-D

I don't have a long experience on HA/blueprint/Zigbee2MQTT but I'll be glad to help you and give you some information about this controller.

**Comment by EPMatt** [comment]
Hi @ShagoY,

thank you for reporting here, this could be a great addition to the collection of Controllers.

I'll try to implement the blueprint in the next couple of days, I'll let you know as soon as it's ready. :)

**Comment by EPMatt** [comment]
Hi @ShagoY,

I've implemented a Controller blueprint for the IKEA E1812 Shortcut button. Support for this remote has been also added for the Light and Media Player Hooks. 👍🏻 

Could you please test the Controller blueprint on your system? Moreover, if you could check that everything is also working with the Light and Media Player Hooks, when paired with an E1812, it would be really helpful.

Please let me know if everything runs as expected. :)
Thanks again for your suggestion!

**Comment by ShagoY** [comment]
Hi EpMatt !

I got this error message : Invalid blueprint: Missing input definition for action_up_long

**Comment by EPMatt** [comment]
@ShagoY I'm sorry, that was another typo....btw should be fixed now! (commit 1466142589e848b042ff3399610b03fd893fb4a4)

**Comment by EPMatt** [comment]
You can use this automation to check that all actions are working as expected. It creates a web notification whenever an event is raised from this controller:

```yaml
- alias: Controller - IKEA E1812 Shortcut button
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1812.yaml
    input:
      integration: Zigbee2MQTT
      zigbee2mqtt_remote: <your_zigbee_remote>
      button_double_press: true
      button_long_loop: true
      action_button_short:
        - service: persistent_notification.create
          data:
            message: button short
      action_button_long:
        - service: persistent_notification.create
          data:
            message: button long
      action_button_release:
        - service: persistent_notification.create
          data:
            message: button release
      action_button_double:
        - service: persistent_notification.create
          data:
            message: button double
```
