### ISSUE TITLE
Bug - Hue Dimmer Switch controller not working with Zigbee2MQTT

### ISSUE THREAD

**Issue by Insight-Rich** [EPMatt/awesome-ha-blueprints#406]
### Blueprint name

Controller - Philips 324131092621 Hue Dimmer switch

### Home Assistant Core Version

2022.8.7

### Home Assistant Installation Type

Home Assistant Supervised

### Description

Automation created from blueprint doesn't seem to recognise button presses from switch connected via Zigbee2MQTT.

### Automation YAML config

```yaml
alias: Controller - Hue Dimmer switch 1
description: ""
use_blueprint:
  path: EPMatt/philips_324131092621.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.hue_dimmer_switch_1_action
    helper_last_controller_event: input_text.last_controller_event_hue_dimmer_switch_1
    action_button_on_short:
      - service: notify.persistent_notification
        data:
          message: hello world
```

### To Reproduce

Short press On button of selected controller.

### Expected behavior

Notification appears.

### Actual Behaviour

Notification does not appear.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Additional context

From having had a dig around, it looks as though the action_mappings for zigbee2mqtt ([lines 323 - 335](https://github.com/EPMatt/awesome-ha-blueprints/blob/9ee5920a3633c87bd8ee8713b83bbbf4705cc31d/blueprints/controllers/philips_324131092621/philips_324131092621.yaml#L323)) are incorrect.

According to the [zigbee2mqtt website](https://www.zigbee2mqtt.io/devices/324131092621.html#action-enum), it uses the form "on_press", rather than "on-press" as the code here seems to expect.

**Comment by Insight-Rich** [comment]
[trace automation.controller_hue_dimmer_switch_1 2022-09-03T11_30_19.535507+00_00.json.txt](https://github.com/EPMatt/awesome-ha-blueprints/files/9482486/trace.automation.controller_hue_dimmer_switch_1.2022-09-03T11_30_19.535507%2B00_00.json.txt)

**Comment by Insight-Rich** [comment]
Further investigation reveals that zigbee2mqtt also fires off undocumented *_press_release actions:

![image](https://user-images.githubusercontent.com/60673296/188271977-0e94768b-a837-4d8e-9d62-5c0b6e2a77b8.png)

**Comment by Bastian007** [comment]
Facing the same issue. Then I have replaced at line 372-396 minus character with underscore character. All newly created automations are running now as expected. 
```
zigbee2mqtt:
      button_on_short:
        - on_press
      button_on_long:
        - on_hold
      button_on_release:
        - on_hold_release
      button_off_short:
        - off_press
      button_off_long:
        - off_hold
      button_off_release:
        - off_hold_release
      button_up_short:
        - up_press
      button_up_long:
        - up_hold
      button_up_release:
        - up_hold_release
      button_down_short:
        - down_press
      button_down_long:
        - down_hold
      button_down_release:
        - down_hold_release
```
