### ISSUE TITLE
Bug - Ikea e1744 Symfonisk rotatory controller does not stop increasing/decreasing values on rotation

### ISSUE THREAD

**Issue by rafuz** [EPMatt/awesome-ha-blueprints#413]
### Blueprint name

ikea_e1744

### Home Assistant Core Version

2022.9.4

### Home Assistant Installation Type

Home Assistant Operating System

### Description

When rotation of the controller stops the light hook continues to increase or decrease brightness until 100% or 0.

### Automation YAML config

```yaml
# Device automation
alias: Switch - SYMFONISK Rotary Remote Studio
description: ""
use_blueprint:
  path: EPMatt/ikea_e1744.yaml
  input:
    integration: deCONZ
    controller_device: b9dee76a0a4111eba9975f6cadff2333
    helper_last_controller_event: input_text.symfonisk_sound_controller_1
    rotate_left_loop: true
    rotate_right_loop: true
    rotate_left_max_loop_repeats: 10
    rotate_right_max_loop_repeats: 10
    helper_debounce_delay: 100

# Hook automation
alias: Hook - Piantana Studio
description: ""
use_blueprint:
  path: EPMatt/light.yaml
  input:
    controller_device: b9dee76a0a4111eba9975f6cadff2333
    controller_model: IKEA E1744 SYMFONISK Rotary Remote
    light: light.piantana_studio
    force_brightness: false
    light_color_mode: None
    on_brightness: 190
```

### To Reproduce

1. Create device automation from blueprint
2. Bind hook automation to light and device
3. Rotate the symfonisk controller
4. When rotation stops light continues to increase/decrease brightness until maximum is reached

### Expected behavior

Brightness should stop changing when the rotary controller is still

### Actual Behaviour

 When rotation stops light continues to increase/decrease brightness until maximum is reached

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Additional context

Version 2021.10.26 of ikea_e1744.yaml works correctly.

**Comment by drsound** [comment]
First off, this is just a guess... Maybe this issue is happening because [9ee5920](https://github.com/EPMatt/awesome-ha-blueprints/commit/9ee5920a3633c87bd8ee8713b83bbbf4705cc31d) changed the format the data is stored in the helper? So maybe the hook code needs an update too?

**Comment by drsound** [comment]
No, I was wrong. The issue is coming from ZHA: in HA 2022.4 they changed the format of the events reported by the Ikea E1744 controller, so the trigger_action variable has no more the expected values.
You can find a fix [here](https://community.home-assistant.io/t/zha-deconz-zigbee2mqtt-ikea-e1744-symfonisk-rotary-remote-universal-blueprint-all-actions-control-lights-media-players-and-more-with-hooks/287536/114).

**Comment by rafuz** [comment]
You are right, I have noticed it some time ago but I didn't fixed the helpers as the controller continued working with the old blueprint. Thank you, this can be closed.

**Comment by rafuz** [comment]
After update to 2022.10.1 the problem seems to be here again.
It happens only with Symfonisk rotatory controller and the helpers are set to 200 characters

**Comment by codeaphex** [comment]
> After update to 2022.10.1 the problem seems to be here again. It happens only with Symfonisk rotatory controller and the helpers are set to 200 characters

Did you try setting a debounce delay?

**Comment by alxch-** [comment]
I am hitting the same issue with HA `2022.12.8`. This is the first time I am setting up the automation. Whenever I do a rotation, it always goes back to 100% brightness when rotating right and 0% rotating left.
I have tried setting a debounce delay without success. In HA I can see that the "stop" even is received correctly, though the increase/decrease of luminosity does not stop.

Device automation:
```
alias: Rotary automation
description: ""
use_blueprint:
  path: EPMatt/ikea_e1744.yaml
  input:
    integration: deCONZ
    controller_device: 2f93a7ba6508d582a305b12cace5998c
    helper_last_controller_event: input_text.symfonisk_salon_last_controller_event
    action_rotate_left: []
    action_rotate_right: []
    helper_debounce_delay: 10
    rotate_left_loop: true
    rotate_right_loop: true
    rotate_left_max_loop_repeats: 10
    rotate_right_max_loop_repeats: 10
```

Hook automation: 
```
alias: kitchen automatisation
description: ""
use_blueprint:
  path: EPMatt/light.yaml
  input:
    controller_device: 2f93a7ba6508d582a305b12cace5998c
    controller_model: IKEA E1744 SYMFONISK Rotary Remote
    light: light.cuisine
    brightness_steps_short: 100
    brightness_steps_long: 100
```
