### ISSUE TITLE
Bug - E1810 Up and down not working

### ISSUE THREAD

**Issue by crazytil** [EPMatt/awesome-ha-blueprints#414]
### Blueprint name

ikea_e1524_e1810

### Home Assistant Core Version

2022.9.4

### Home Assistant Installation Type

Home Assistant Supervised

### Description

Long and short not working for up and down on remote E1810.

Managed to get it working by changing the zha_event settings

The below changes made it work for me.

### Automation YAML config

```yaml
zha:
      button_left_short:
      - press_257_13_0
      button_left_long:
      - hold_3329_0
      button_left_release:
      - release
      button_right_short:
      - press_256_13_0
      button_right_long:
      - hold_3328_0
      button_right_release:
      - release
      button_up_short:
      - Up_43_5
      - step_with_on_off_StepMode.Up_43_5
      button_up_long:
      - move_with_on_off_0_83
      - move_with_on_off_0_84
      - move_with_on_off_MoveMode.Up_84
      button_up_release:
      - stop
      - stop_with_on_off
      button_down_short:
      - step_StepMode.Down_43_5_bitmap8.0_bitmap8.0
      - Down_43_5_bitmap8.0_bitmap8.0
      button_down_long:
      - move_MoveMode.Down_84_bitmap8.0_bitmap8.0
      - move_1_84
      button_down_release:
      - stop
      - stop_bitmap8.0_bitmap8.0
      button_center_short:
      - toggle
      button_center_long:
      - press_2_0_0
```

### To Reproduce

1. Set up automation
2. press up or down
3. no action with Hook

### Expected behavior

Lights to fade and step up or down

### Actual Behaviour

No action on lights

### Additional Details

- [X] I'd like to help developing a fix for this issue.
