### ISSUE TITLE
E1743 does not dim with deCONZ 

### ISSUE THREAD

**Issue by xbmcnut** [EPMatt/awesome-ha-blueprints#421]
### Blueprint name

EPMatt/ikea_e1743.yaml

### Home Assistant Core Version

2022.9.7

### Home Assistant Installation Type

Home Assistant Operating System

### Description

I've never been able to get dimming on long press working with this remote. Light turns on and off fine but when light is on and I hold the down button, it dims down to 80% then locks up and won't go any further. Reading through the issues, I've increased the input helper to 255 characters and restarted but that did not help.

- Hook version is 2022.07.30
- ikea_e1743.yaml version Version 2022.08.08

### Automation YAML config

```yaml
alias: Master Bedroom Ikea switch mapping
description: ""
use_blueprint:
  path: EPMatt/ikea_e1743.yaml
  input:
    integration: deCONZ
    controller_device: 2e7ebf435f2268f19a0e689232c30e5d
    helper_last_controller_event: input_text.mb_switch_last_controller_event
    action_button_up_short:
      - type: turn_on
        device_id: b2907fe03bd0e9c5daee497e9e029b48
        entity_id: light.master_bedroom_dimmer
        domain: light
        brightness_pct: 100
    action_button_up_long:
      - device_id: b2907fe03bd0e9c5daee497e9e029b48
        domain: light
        entity_id: light.master_bedroom_dimmer
        type: brightness_increase
    action_button_down_short:
      - type: turn_off
        device_id: b2907fe03bd0e9c5daee497e9e029b48
        entity_id: light.master_bedroom_dimmer
        domain: light
    action_button_down_long:
      - device_id: b2907fe03bd0e9c5daee497e9e029b48
        domain: light
        entity_id: light.master_bedroom_dimmer
        type: brightness_decrease
    button_up_long_loop: true
    button_down_long_loop: true
    button_up_double_press: false
    button_down_double_press: false

alias: Master Bedroom Hook for Ikea E1743 switch
description: ""
use_blueprint:
  path: EPMatt/light.yaml
  input:
    controller_device: 2e7ebf435f2268f19a0e689232c30e5d
    controller_model: IKEA E1743 TRÅDFRI On/Off Switch & Dimmer
    force_brightness: true
    on_brightness: 255
    light_color_mode: None
    light: light.master_bedroom_dimmer
```

### To Reproduce

3. Trigger the automation '....'

### Expected behavior

Light dims and and down on long-press

### Actual Behaviour

Light turns on and off and will only dim down to 80%. Dimming up does not work at all.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
