### ISSUE TITLE
Bug - SYMFONISK Up/Down rotation not working

### ISSUE THREAD

**Issue by Reproduktor** [EPMatt/awesome-ha-blueprints#423]
### Blueprint name

ikea_e1744

### Home Assistant Core Version

2022.10.1

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Newly purchased SYMFONISK E1744 with firmware 0x23080631, connected via ZHA, with Quirk: zhaquirks.ikea.symfonisk.IkeaSYMFONISK1.

Up/Down rotations do not work at all.

### Automation YAML config

```yaml
alias: Controller - IKEA E1744 SYMFONISK Rotary Remote
description: ""
use_blueprint:
  path: EPMatt/ikea_e1744.yaml
  input:
    integration: ZHA
    controller_device: d82b1e8bcf25e96f846edc11614d4ab6
    helper_last_controller_event: input_text.symfoniskhelper
    rotate_left_loop: true
    rotate_right_loop: true
```

### To Reproduce

{straightforward)

### Expected behavior

The blueprint should check for correct strings in `trigger_action`.

### Actual Behaviour

Investigated a little bit, and it seems that `trigger_action` generated by the blueprint for my events are:

Rotate right: `move_MoveMode.Up_195_bitmap8.0_bitmap8.0`
Rotate left: `move_MoveMode.Down_195_bitmap8.0_bitmap8.0`
Click (handled OK): `toggle`
Double click: `step_StepMode.Up_1_0_bitmap8.0_bitmap8.0`
Triple click: `step_StepMode.Down_1_0_bitmap8.0_bitmap8.0`

However, the blueprint is checking for these:

`
zha:
      rotate_left: [move_1_195]
      rotate_stop: [stop]
      rotate_right: [move_0_195]
      click_short: [toggle]
      click_double: [step_0_1_0]
      click_triple: [step_1_1_0]
`

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Additional context

Maybe this is caused by device firmware, maybe (Z)HA version, maybe ZHA quirk. I cannot say.
