### ISSUE TITLE
Bug - 

### ISSUE THREAD

**Issue by Mariuss811** [EPMatt/awesome-ha-blueprints#424]
### Blueprint name

Blueprint Controller - IKEA E2001/E2002 STYRBAR Remote control 

### Home Assistant Core Version

2022.10.2

### Home Assistant Installation Type

Home Assistant Operating System

### Description

At every Restart of Hassio or using my Remote I get this error. 
But the Remote works as expected. 

I am using deConz and by now no Problems with using the Remote. But I don't know if this issue came up with newer hassio version.
But in my understanding the Blueprint tries to crate a automation with ZHA  which I don't use and didn't select in the blueprint.

> Logger: homeassistant.components.automation
Source: components/automation/__init__.py:280 
Integration: Automatisierung (documentation, issues) 
First occurred: 11:38:51 (2 occurrences) 
Last logged: 11:39:05
>Blueprint Controller - IKEA E2001/E2002 STYRBAR Remote control generated invalid automation with inputs OrderedDict([('integration', 'ZHA'), ('controller_device', 'befe810b2621e1df058cf0fe5ff17079'), ('helper_last_controller_event', 'input_text.ikea_fernbedienung_last_event'), ('action_button_left_short', [OrderedDict([('device_id', ''), ('domain', ''), ('entity_id', '')])]), ('action_button_up_short', [OrderedDict([('type', 'turn_on'), ('device_id', 'c1bc26a189030dac92bb4925eb4709a0'), ('entity_id', 'light.nachttisch_charleen'), ('domain', 'light'), ('brightness_pct', 80)]), OrderedDict([('type', 'turn_on'), ('device_id', '29620ad82c6c2ce47d79c2e7d8069be7'), ('entity_id', 'light.nachttisch_marius'), ('domain', 'light'), ('brightness_pct', 80)]), OrderedDict([('type', 'turn_on'), ('device_id', 'f4ee2911daeb17235945709b3560a1cf'), ('entity_id', 'light.controller_rgb_803d9d'), ('domain', 'light'), ('brightness_pct', 100)])])]): Integration '' not found. Got <homeassistant.components.blueprint.models.BlueprintInputs object at 0x7f99396050>

### Automation YAML config

```yaml
alias: "Schlafzimmer: STYRBAR Remote control"
description: ""
use_blueprint:
  path: EPMatt/ikea_e2001_e2002.yaml
  input:
    integration: deCONZ
    controller_device: befe810b2621e1df058cf0fe5ff17079
    helper_last_controller_event: input_text.ikea_fernbedienung_last_event
    action_button_left_short:
      - service: light.turn_on
        data:
          brightness_step_pct: -10
        target:
          entity_id:
            - light.schlafzimmer
        alias: 10% Dimmen
    action_button_right_short:
      - service: light.turn_on
        data:
          brightness_step_pct: 10
        target:
          entity_id: light.schlafzimmer
    action_button_up_short:
      - service: light.turn_on
        data:
          brightness_pct: 90
        target:
          entity_id: light.schlafzimmer_2
    action_button_up_long:
      - service: light.turn_on
        data:
          brightness_pct: 50
        target:
          entity_id:
            - light.nachttischlampe
            - light.controller_rgb_803d9d
    action_button_down_short:
      - service: light.turn_off
        data:
          transition: 1
        target:
          entity_id: light.schlafzimmer
    action_button_down_long:
      - service: scene.turn_on
        data:
          transition: 1
        target:
          entity_id: scene.gute_nacht
      - service: script.1662110288141
        data: {}
```

### To Reproduce

1. Add Blueprint and create Automation
2. Using it
3. See error

### Expected behavior

A Error free use

### Actual Behaviour

Getting Error in Logs 

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
