### ISSUE TITLE
Bug - 

### ISSUE THREAD

**Issue by DBobsn** [EPMatt/awesome-ha-blueprints#437]
### Blueprint name

Controller - IKEA E1812 TRÅDFRI Shortcut button

### Home Assistant Core Version

2022.10.5

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Hi,

i've tried to define an automation for my Tradfri Shortcut-Button. 
The following error-message appears in the HomeAssistant Log:

Logger: homeassistant.components.automation.kueche_dashbutton
Source: helpers/script.py:409
Integration: Automatisierung ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 20:17:27 (94 occurrences)
Last logged: 23:31:21

    Kueche-Dashbutton: Error executing script. Invalid data for call_service at pos 3: not a valid value for dictionary value @ data['entity_id']
    Kueche-Dashbutton: Error executing script. Error rendering template for variables at pos 2: UndefinedError: 'dict object' has no attribute 'event'

### Automation YAML config

```yaml
alias: Kueche-Dashbutton
description: ""
use_blueprint:
  path: EPMatt/ikea_e1812.yaml
  input:
    integration: Zigbee2MQTT
    controller_device: ccc5d766e901b22c6e7a4dc9d0104928
    controller_entity: sensor.kueche_dashbutton_action
    helper_last_controller_event: Singleclick
    action_button_short:
      - type: toggle
        device_id: 20758c51c37db1788ba83b8f97a6235f
        entity_id: switch.lampe_sofa
        domain: switch
```

### To Reproduce

1. Go to 'Automations'
2. Click on 'Execute'
3. Trigger the automation '....'

### Expected behavior

When im click the button, my smartplug gets triggered. 

### Actual Behaviour

Nothing.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
