### ISSUE TITLE
Bug - 

### ISSUE THREAD

**Issue by socialhugo** [EPMatt/awesome-ha-blueprints#445]
### Blueprint name

https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/philips_929002398602

### Home Assistant Core Version

2022.11.1

### Home Assistant Installation Type

Home Assistant Operating System

### Description

I have the philips hue dimmer v2 connected to zigbee2mqtt
I added the two variables as mentioned in the configuration

The blueprint actions aren't triggered
The automation does detect the input from the remote / hue dimmer.
The automation does change the input text according to the pressed button.
The automation is triggered so the remote does work.

<img width="878" alt="Schermafbeelding 2022-11-08 121138" src="https://user-images.githubusercontent.com/98784041/200552363-901ebfc0-4235-420b-b8fd-78ca0f15e514.png">
<img width="843" alt="Schermafbeelding 2022-11-08 121935" src="https://user-images.githubusercontent.com/98784041/200552371-a602ea71-15d5-470d-b0c4-c310535ed1ba.png">

The action within the automation is not triggered (tried various devices)

See attachements

### Automation YAML config

```yaml
alias: Dimmerswitch Hue
description: ""
use_blueprint:
  path: EPMatt/philips_324131092621.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.0x001788010b59bff7_action
    helper_last_controller_event: input_text.text1
    action_button_on_short:
      - type: turn_off
        device_id: b036a57cf6827c82c020d21acc64996a
        entity_id: light.0x70ac08fffeca7eaa
        domain: light
    action_button_on_long:
      - type: turn_off
        device_id: b036a57cf6827c82c020d21acc64996a
        entity_id: light.0x70ac08fffeca7eaa
        domain: light
    action_button_up_short:
      - device_id: b036a57cf6827c82c020d21acc64996a
        domain: light
        entity_id: light.0x70ac08fffeca7eaa
        type: brightness_increase
```

### To Reproduce

Activate the automation
Press a button on the physical remote
See the variabele change
Don't a action happening 

### Expected behavior

action triggered as configured in blueprint

### Actual Behaviour

input text variabele is changed by detected hardware button input

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Additional context

Thanks for all the effort
