### ISSUE TITLE
Bug - wxcjkg13lm Aqara Opple 6 Button remote actions are not executed (new/different events?)

### ISSUE THREAD

**Issue by pschmitt** [EPMatt/awesome-ha-blueprints#447]
### Blueprint name

xiaomi_wxcjkg13lm

### Home Assistant Core Version

2022.11.2

### Home Assistant Installation Type

Home Assistant Operating System

### Description

A while back I noticed that my Opple 6 button remote stopped working in conjunction with this blueprint.

My device buttons yield the following events (notice the `command` values)

```yaml

# Button 1

event_type: zha_event
data:
    device_ieee: 04:cf:8c:df:3c:7d:99:c2
    unique_id: 04:cf:8c:df:3c:7d:99:c2:1:0x0006
    device_id: ac542098393659490987fe17fdf0046c
    endpoint_id: 1
    cluster_id: 6
    command: off
    args: []
    params: {}
origin: LOCAL
time_fired: '2022-11-10T16:36:52.167743+00:00'
context:
    id: 01GHH6DGA7DX0EP76B3XSSSF6H
    parent_id:
    user_id:


# Button 2

event_type: zha_event
data:
    device_ieee: 04:cf:8c:df:3c:7d:99:c2
    unique_id: 04:cf:8c:df:3c:7d:99:c2:1:0x0006
    device_id: ac542098393659490987fe17fdf0046c
    endpoint_id: 1
    cluster_id: 6
    command: on
    args: []
    params: {}
origin: LOCAL
time_fired: '2022-11-10T16:36:54.390583+00:00'
context:
    id: 01GHH6DJFP7ERPT0SZTXDSVFR6
    parent_id:
    user_id:

# Button 3

event_type: zha_event
data:
    device_ieee: 04:cf:8c:df:3c:7d:99:c2
    unique_id: 04:cf:8c:df:3c:7d:99:c2:1:0x0008
    device_id: ac542098393659490987fe17fdf0046c
    endpoint_id: 1
    cluster_id: 8
    command: step
    args:
       -  1
       -  85
       -  7
       -  0
       -  0
    params:
        step_mode: 1
        step_size: 85
        transition_time: 7
        options_mask: 0
        options_override: 0
origin: LOCAL
time_fired: '2022-11-10T16:36:57.228654+00:00'
context:
    id: 01GHH6DN8C7W79F01VVHSSV0GJ
    parent_id:
    user_id:

# Button 4

event_type: zha_event
data:
    device_ieee: 04:cf:8c:df:3c:7d:99:c2
    unique_id: 04:cf:8c:df:3c:7d:99:c2:1:0x0008
    device_id: ac542098393659490987fe17fdf0046c
    endpoint_id: 1
    cluster_id: 8
    command: step
    args:
       -  0
       -  85
       -  7
       -  0
       -  0
    params:
        step_mode: 0
        step_size: 85
        transition_time: 7
        options_mask: 0
        options_override: 0
origin: LOCAL
time_fired: '2022-11-10T16:36:58.567556+00:00'
context:
    id: 01GHH6DPJ7ZZX5Z7ZD6Y0NPS6Q
    parent_id:
    user_id:

# Button 5

event_type: zha_event
data:
    device_ieee: 04:cf:8c:df:3c:7d:99:c2
    unique_id: 04:cf:8c:df:3c:7d:99:c2:1:0x0300
    device_id: ac542098393659490987fe17fdf0046c
    endpoint_id: 1
    cluster_id: 768
    command: step_color_temp
    args:
       -  1
       -  69
       -  7
       -  0
       -  0
       -  0
       -  0
    params:
        step_mode: 1
        step_size: 69
        transition_time: 7
        color_temp_min_mireds: 0
        color_temp_max_mireds: 0
        options_mask: 0
        options_override: 0
origin: LOCAL
time_fired: '2022-11-10T16:36:59.607001+00:00'
context:
    id: 01GHH6DQJQH2NX6GNCBGTSHHAA
    parent_id:
    user_id:

# Button 6

event_type: zha_event
data:
    device_ieee: 04:cf:8c:df:3c:7d:99:c2
    unique_id: 04:cf:8c:df:3c:7d:99:c2:1:0x0300
    device_id: ac542098393659490987fe17fdf0046c
    endpoint_id: 1
    cluster_id: 768
    command: step_color_temp
    args:
       -  3
       -  69
       -  7
       -  0
       -  0
       -  0
       -  0
    params:
        step_mode: 3
        step_size: 69
        transition_time: 7
        color_temp_min_mireds: 0
        color_temp_max_mireds: 0
        options_mask: 0
        options_override: 0
origin: LOCAL
time_fired: '2022-11-10T16:37:00.575311+00:00'
context:
    id: 01GHH6DRGZKMC174KG0GV4EQDH
    parent_id:
    user_id:
```

### Automation YAML config

```yaml
alias: ⚫ Aqara Opple 6 button remote
description: Office wall switch
use_blueprint:
  path: EPMatt/xiaomi_wxcjkg13lm.yaml
  input:
    integration: ZHA
    controller_device: ac542098393659490987fe17fdf0046c
    helper_last_controller_event: input_text.aqara_opple_6_button_remote_last_controller_event
    action_button_1_short:
      - service: light.toggle
        target:
          device_id: a2d83b96429bb2af08bf5693bcfa7eaa
        data:
          color_name: white
          brightness_pct: 85
    action_button_2_short:
      - type: toggle
        device_id: 44741c665a3d24187ff69ef43335b149
        entity_id: light.office_yeelight
        domain: light
    action_button_1_long:
      - type: toggle
        device_id: e05788bdc7c394cc709ec14d58a0ea92
        entity_id: switch.office_motion_sensor_motion
        domain: switch
    action_button_6_short:
      - service: light.toggle
        target:
          entity_id: light.turris_omnia_leds
        data: {}
    action_button_3_short:
      - service: light.toggle
        target:
          entity_id: light.hallway_lights_group
        data: {}
    action_button_3_long:
      - service: light.turn_off
        target:
          entity_id: light.hallway_lights_group
          area_id: bathroom_2
        data: {}
    action_button_1_double:
      - type: turn_off
        device_id: e05788bdc7c394cc709ec14d58a0ea92
        entity_id: switch.office_motion_sensor_motion
        domain: switch
    action_button_1_release:
      - type: toggle
        device_id: e05788bdc7c394cc709ec14d58a0ea92
        entity_id: switch.office_motion_sensor_motion
        domain: switch
    action_button_2_double:
      - service: light.turn_on
        data:
          brightness_pct: 50
          rgb_color:
            - 255
            - 128
            - 0
        target:
          device_id: 44741c665a3d24187ff69ef43335b149
    action_button_2_triple:
      - service: light.turn_on
        data:
          color_name: white
          brightness_pct: 100
        target:
          device_id: 44741c665a3d24187ff69ef43335b149
    action_button_4_short: []
    action_button_6_long:
      - type: toggle
        device_id: 6f553bf41ba9d1e0def2929cf4958a03
        entity_id: switch.office_desk_power_socket
        domain: switch
    action_button_6_release:
      - type: toggle
        device_id: 6f553bf41ba9d1e0def2929cf4958a03
        entity_id: switch.office_desk_power_socket
        domain: switch
    action_button_3_release:
      - service: light.turn_off
        target:
          area_id:
            - bathroom_2
            - hallway
        data: {}
    action_button_6_triple:
      - service: script.feierabend
        data: {}
    action_button_5_short:
      - type: toggle
        device_id: 067e2f5cf4bd091a64dedb4eefb8203e
        entity_id: switch.office_desk_shelf_power_socket
        domain: switch
```

### To Reproduce

1. Install blueprint
2. Set up a new automation
3. Trigger the automation bay pressing buttons
4. Notice the actions are not executed

### Expected behavior

The button actions are executed as defined in the automation.

### Actual Behaviour

None of the buttons lead to the corresponding action being executed.

Here's how the trace looks in the GUI:

![image](https://user-images.githubusercontent.com/37886/201154458-4517739f-dded-4f6b-a00e-c730dc8cdcb0.png)

### Additional Details

- [X] I'd like to help developing a fix for this issue.
