### ISSUE TITLE
Enhancement - Ignore brightness up commands while light is off

### ISSUE THREAD

**Issue by Ririshi** [EPMatt/awesome-ha-blueprints#450]
### Blueprint name

Hook - Light

### Description

I would like to add an optional boolean input to the light hook that, when enabled, will make the light ignore brightness up commands while it is off.

Let's say you have multiple lights connected to the same controller, but you can turn them on and off separately through custom actions. If a light is currently off, and a brightness up command is sent by the controller, it will turn on because of this code in the blueprint:
```yaml
- conditions: '{{ states(light) == "off" and not smooth_power_on}}'
  sequence:
  - service: light.turn_on
    data:
      transition: '{{ light_transition / 1000 }}'
      entity_id: !input light
```

With the extra input I am suggesting, the automation will also check if the input is set to true, and if it is, it will ignore the brightness command if the light is currently off.

### Automation YAML config

```yaml
alias: Hook - Office RGB Floor light
description: ""
use_blueprint:
  path: EPMatt/light.yaml
  input:
    controller_entity: sensor.office_styrbar_remote_action
    controller_model: IKEA E2001/E2002 STYRBAR Remote control
    light: light.office_rgb_floor_light
    ignore_brightness_when_off: true
```

### Implementation

The steps for implementing this would be:
- Add a boolean input to the blueprint.
- Add checks to check the boolean input state for each brightness action:
Only execute brightness action if the boolean state is off, or if the light is already on.

### Additional Details

- [X] I'd like to help developing this feature/improvement.
