### ISSUE TITLE
Bug - On button short press of Philips HUE Dimmer V2 is executed twice

### ISSUE THREAD

**Issue by Sab3rRid3r** [EPMatt/awesome-ha-blueprints#457]
### Blueprint name

philips_929002398602

### Home Assistant Core Version

2022.11.5

### Home Assistant Installation Type

Home Assistant Supervised

### Description

The "On button short press" action executes the toggle command twice.

Mqtt Messages send from the Dimmer switch on single press (zigbee2mqtt/hue_dimmer_switch_kinderzimmer)
1. {"action":"on_press","battery":100,"brightness":40,"linkquality":160,"update":{"state":"idle"},"update_available":false}
2. {"action":"","battery":100,"brightness":40,"linkquality":160,"update":{"state":"idle"},"update_available":false}
3. .../action: on_press
4. {"action":"on_press_release","battery":100,"brightness":40,"linkquality":160,"update": {"state":"idle"},"update_available":false}
5. {"action":"","battery":100,"brightness":40,"linkquality":160,"update":{"state":"idle"},"update_available":false}
6. .../action: on_press_release

MQTT Messages send to the light (zigbee2mqtt/hue_lightstrip_kinderzimmer_lowboard)
1. {"brightness":118,"color":{"x":0.453,"y":0.432},"color_mode":"xy","color_temp":338,"linkquality":47,"state":"OFF","update":{"state":"idle"},"update_available":false}
2. {"brightness":118,"color":{"x":0.453,"y":0.432},"color_mode":"xy","color_temp":338,"linkquality":51,"state":"ON","update":{"state":"idle"},"update_available":false}

Thanks in advance
Andreas

### Automation YAML config

```yaml
alias: Wohnzimmer Lowboard Steuern über HUE Dimmer Switch
description: ""
use_blueprint:
  path: EPMatt/philips_929002398602.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.kinderzimmer_dimmerswitch_action
    helper_last_controller_event: input_text.last_controller_event_hue_dimmer_controller
    action_button_on_short:
      - type: toggle
        device_id: c5c795b71a0711eb9cb407713ab5d453
        entity_id: light.hue_lightstrip_kinderzimmer_lowboard_light
        domain: light
```

### To Reproduce

It always occurs on button short press 

### Expected behavior

My expectation would have been that either an event to turn on or off would be sent.

### Actual Behaviour

The toggle event is triggered twice

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
