### ISSUE TITLE
IKEA E1810 long press not working correctly

### ISSUE THREAD

**Issue by jullit31** [EPMatt/awesome-ha-blueprints#46]
Thank you for taking the time to report here! :tada:

**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to process your request more rapidly.

This template should only be used to report a bug with a blueprint. If this is not your case, you can [choose a different issue template](https://github.com/EPMatt/awesome-ha-blueprints/issues/new/choose). If you have a question instead, please open a discussion [here](https://github.com/EPMatt/awesome-ha-blueprints/discussions/new).

\*_=required_

## Bug Details\*

- Blueprint name: IKEA E1524/E1810 5-Button Remote
- Home Assistant Core Version: 2021.4.6
- Home Assistant Installation Type: Home Assistant OS

## Description\*

Long pressing the **center**, **left** or **right** button does not work as intended. The **up** and **down** button work fine.

## Automation YAML config\*

```yaml
alias: Controller - Tisch
description: ''
use_blueprint:
  path: EPMatt/ikea_e1524_e1810.yaml
  input:
    integration: deCONZ
    controller_device: 17bb609d7a03b50403259f3adf62aff3
    action_button_down_long:
      - type: toggle
        device_id: a25e30293914d399998ffde669c069b7
        entity_id: light.bild_n
        domain: light
    action_button_center_long:
      - type: toggle
        device_id: a25e30293914d399998ffde669c069b7
        entity_id: light.bild_n
        domain: light
    action_button_left_long:
      - type: toggle
        device_id: a25e30293914d399998ffde669c069b7
        entity_id: light.bild_n
        domain: light
    action_button_right_long:
      - type: toggle
        device_id: a25e30293914d399998ffde669c069b7
        entity_id: light.bild_n
        domain: light
    action_button_up_long:
      - type: toggle
        device_id: a25e30293914d399998ffde669c069b7
        entity_id: light.bild_n
        domain: light
    action_button_left_short:
      - type: toggle
        device_id: 5c34876c756d5d1b68c3203d6a140171
        entity_id: light.tisch_fenster_n
        domain: light
    action_button_right_short:
      - type: toggle
        device_id: 5c34876c756d5d1b68c3203d6a140171
        entity_id: light.tisch_fenster_n
        domain: light
    action_button_up_short:
      - type: toggle
        device_id: 5c34876c756d5d1b68c3203d6a140171
        entity_id: light.tisch_fenster_n
        domain: light
    action_button_down_short:
      - type: toggle
        device_id: 5c34876c756d5d1b68c3203d6a140171
        entity_id: light.tisch_fenster_n
        domain: light
    action_button_center_short:
      - type: toggle
        device_id: 5c34876c756d5d1b68c3203d6a140171
        entity_id: light.tisch_fenster_n
        domain: light
```

## To Reproduce\*

Steps to reproduce the issue:

1. Set up above automation
2. Press a button on the remote
3. See error

## Expected behavior\*

Any short press toggles **light.tisch_fenster_n**, any long press toggles **light.bild_n** once.

## Actual Behaviour\*
Any short press toggles **light.tisch_fenster_n** :heavy_check_mark:
Long pressing the **up** or **down** button toggles **light.bild_n** once :heavy_check_mark:
Long pressing the **left** or **right** button continually toggles **light.tisch_fenster_n** for as long as the button is pressed :x:
Long pressing the **center** button toggles **light.tisch_fenster_n** instantly and (assuming you keep it pressed for that long) approx. 4 seconds later toggles **light.bild_n** :x:

## Additional Details\*

The E1810 is brand new.
