### ISSUE TITLE
Bug - Brightness not turning group lights at 255 (max) (Ikea E1524 with LIDL Livarno Lux bulbs)

### ISSUE THREAD

**Issue by oudoulj** [EPMatt/awesome-ha-blueprints#463]
### Blueprint name

Hook Light

### Home Assistant Core Version

2022.12.0

### Home Assistant Installation Type

Home Assistant Operating System

### Description

I have a Conbee II stick using the Deconz integration.
My Ikea E1524 switch turns on a group of 2 color lights (LIDL Livarno Lux bulbs from LIDL)

### Automation YAML config

```yaml
alias: Study - Hook Light - IKEA Tradfri E1524/E1810 5-Button Remote
description: ""
use_blueprint:
  path: EPMatt/light.yaml
  input:
    light_color_mode: Auto
    controller_device: e731dfd279799fd6d208e604e727e0a7
    controller_model: IKEA E1524/E1810 TRÅDFRI Wireless 5-Button Remote
    light: light.office_lights
    on_brightness: 255
    max_brightness: 255


alias: Study - Controller IKEA Tradfri E1524/E1810 5-Button Remote
description: ""
use_blueprint:
  path: EPMatt/ikea_e1524_e1810.yaml
  input:
    integration: deCONZ
    controller_device: e731dfd279799fd6d208e604e727e0a7
    helper_last_controller_event: input_text.study_lights_last_controller_event
```

### To Reproduce

1. Create a Helper light.office_lights of type Group with 2 lights in it
2. Configure a Hook Light and Controller like the yaml code provided above with the default options and "Light maximum brightness" at 255
3. Press the center button of the switch
4. Lights turn on at only brightness 1

### Expected behavior

Lights should turn on at the specified "Light maximum brightness" value (`max_brightness`) from the Hook - Light.

### Actual Behaviour

Lights turn on at only brightness 1 :crying_cat_face: 

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
