### ISSUE TITLE
Bug - Light Hook Not Firing Anymore

### ISSUE THREAD

**Issue by juuukaaay** [EPMatt/awesome-ha-blueprints#496]
### Blueprint name

Hook - Light

### Home Assistant Core Version

2023.1.5

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Woke up today to all my Dimmer Switches not working anymore. They were working fine yesterday.
The Controller automation works as it should, but the Hook is not firing.
The MQTT signals are coming in fine, the Controller automation works as intended.

Already tried:
- Restarting System
- Removing all automations & helpers and redoing only one for testing.
- Renaming the switch in z2m & ha, redoing the automations with the new entities/device.

### Automation YAML config

```yaml
This is the Hook:

alias: Büro / Schalter
description: ""
use_blueprint:
  path: EPMatt/light.yaml
  input:
    controller_device: fe86268b1c376b04a9480974f4cae08d
    controller_entity: sensor.buro_schalter_action
    controller_model: Philips 324131092621 Hue Dimmer switch
    light: light.buro_licht
    light_color_mode: None
    light_transition: 500
    force_brightness: true
    on_brightness: 204

This is the Controller:

alias: Büro / Schalter Controller
description: ""
use_blueprint:
  path: EPMatt/philips_324131092621.yaml
  input:
    integration: Zigbee2MQTT
    helper_last_controller_event: input_text.buro_schalter_helper_text
    controller_entity: sensor.buro_schalter_action
```

### To Reproduce

1. Press a button the Dimmer Switch
2. See that the Controller automation fires
3.  See that the Hook doesn't fire

### Expected behavior

The Hook should fire and ajdust the lights accordingly.

### Actual Behaviour

Hook doesn't fire.

### Additional Details

- [X] I'd like to help developing a fix for this issue.
