### ISSUE TITLE
[BUG] IKEA E1744 SYMFONISK Rotary Remote

### ISSUE THREAD

**Issue by ShagoY** [EPMatt/awesome-ha-blueprints#5]
**Bug Details**

- Blueprint name: IKEA E1744 SYMFONISK Rotary Remote
- Home Assistant Core Version: 2021.3.4
- Home Assistant Installation: Home Assistant OS

**Description**
The action on "Rotate left" doesn't work if I don't add an action on "Rotate right stop".

**To Reproduce**
YAML automation which does not work.
```
alias: Controller - IKEA E1744 SYMFONISK rotary remote
description: ''
use_blueprint:
  path: EPMatt/ikea_e1744.yaml
  input:
    integration: Zigbee2MQTT
    zigbee2mqtt_remote: sensor.tradfri_controller_action
    helper_last_controller_event: input_text.tradfri_controller
    action_click_double: []
    action_click: []
    action_rotate_left:
      - service: script.demo_simple_test
    action_rotate_right: []
    action_rotate_right_stop: []
    action_rotate_left_stop: []
    rotate_left_loop: false
    rotate_right_loop: false
```
YAML automation which works.
```
alias: Controller - IKEA E1744 SYMFONISK rotary remote
description: ''
use_blueprint:
  path: EPMatt/ikea_e1744.yaml
  input:
    integration: Zigbee2MQTT
    zigbee2mqtt_remote: sensor.tradfri_controller_action
    helper_last_controller_event: input_text.tradfri_controller
    action_click_double: []
    action_click: []
    action_rotate_left:
      - service: script.demo_simple_test
    action_rotate_right: []
    action_rotate_right_stop:
      - service: script.demo_simple_test
    action_rotate_left_stop: []
    rotate_left_loop: false
    rotate_right_loop: false
```

**Expected behavior**
Be able to configure the action "Rotate left" and "Rotate right" without configuring an action on "Rotate right stop".

**Additional context**
I created an input text in configuration.yaml (in HA) like this:
```
input_text: 
  tradfri_controller:
    name: Tradfri Controller
```
zigbee2mqtt/devices.yaml as recommended on [zigbee2mqtt.io](https://www.zigbee2mqtt.io/devices/E1744.html#ikea-e1744)
```
'0xabc457fffe679xyz':
  friendly_name: Tradfri Controller
  legacy: false
```
```
{"action":"brightness_move_down","action_rate":195,"battery":74,"brightness":128,"linkquality":197,"rate":195,"update":{"state":"idle"},"update_available":false}
```

**Comment by ShagoY** [comment]
Testing the "media_player.volume_down" service on an entity where I can decrease/increase the volume using the lovelace widget. It appears that the "rotate Left" trigger "action_rotate_right_stop" instead of "action_rotate_left".
So no matter which way I turn the knob, the volume increases.

```
alias: Controller - IKEA E1744 SYMFONISK rotary remote
description: ''
use_blueprint:
  path: EPMatt/ikea_e1744.yaml
  input:
    integration: Zigbee2MQTT
    zigbee2mqtt_remote: sensor.tradfri_controller_action
    helper_last_controller_event: input_text.tradfri_controller
    action_click_double: []
    action_click:
      - service: media_player.media_play_pause
        target:
          entity_id: media_player.lg_webos_smart_tv
    action_rotate_left:
      - service: media_player.volume_down
        target:
          entity_id: media_player.lg_webos_smart_tv
    action_rotate_right: []
    action_rotate_right_stop:
      - service: media_player.volume_up
        target:
          entity_id: media_player.lg_webos_smart_tv
    action_rotate_left_stop: []
    rotate_left_loop: false
    rotate_right_loop: false
```
