### ISSUE TITLE
Bug - 

### ISSUE THREAD

**Issue by jjpaq** [EPMatt/awesome-ha-blueprints#520]
### Blueprint name

Controller - IKEA E1743 TRÅDFRI On/Off Switch & Dimmer

### Home Assistant Core Version

2023.2.3

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Long-press events on the IKEA E1743 On/Off button are not detected by the blueprint. 

The blueprint expects the trigger_action for a long-press down command to be "move_1_83", meaning the **command** would be "move", and there would be two **arg**s: [1, 83].

Based on some debugging, the trigger_action variable _actually_ ends up set to "move_MoveMode.Down_83_bitmap8.0_bitmap8.0", and so the blueprint doesn't trigger the correct action. I have no idea where these MoveMode.Down and bitmap8.0 event args are coming from.

Here's the zha_event that's fired when holding the button:
```
event_type: zha_event
data:
  device_ieee: 94:34:69:ff:fe:3e:2f:d8
  unique_id: 94:34:69:ff:fe:3e:2f:d8:1:0x0008
  device_id: 5409783488f16c21a6e5876287718384
  endpoint_id: 1
  cluster_id: 8
  command: move
  args:
    - 1
    - 83
    - 0
    - 0
  params:
    move_mode: 1
    rate: 83
    options_mask: 0
    options_override: 0
origin: LOCAL
time_fired: "2023-02-13T01:09:38.290483+00:00"
context:
  id: 01GS453ZBJD276GSMEVQBCA1R4
  parent_id: null
  user_id: null 
```

As far as I can tell, this should set trigger_action correctly ("move" + "_" because args > 0 + underscore-joined list of args would result in "move_1_83").

I also listened to all events during this time, in case an event was being generated elsewhere that was triggering the blueprint but with unexpected arguments. None showed up with "MoveMode" or "bitmap" arguments.

### Automation YAML config

```yaml
alias: Family Room Light Switch
description: ""
use_blueprint:
  path: EPMatt/ikea_e1743.yaml
  input:
    integration: ZHA
    controller_device: 5409783488f16c21a6e5876287718384
    helper_last_controller_event: input_text.family_room_switch_text
    action_button_up_short:
      - service: scene.turn_on
        target:
          entity_id: scene.family_room_on_2
        metadata: {}
    action_button_down_short:
      - service: scene.turn_on
        target:
          entity_id: scene.family_room_off_2
        metadata: {}
    button_up_long_loop: true
    action_button_up_long:
      - parallel:
          - device_id: 053168c8cdd3749fc3e6dab7dd716828
            domain: light
            entity_id: light.family_room_ceiling_1_light_2
            type: brightness_increase
          - device_id: ede31b90874cd569f09cace1f007ef8d
            domain: light
            entity_id: light.family_room_ceiling_2_light
            type: brightness_increase
          - device_id: 6fa279558227b8c3791d876e0fdc8744
            domain: light
            entity_id: light.family_room_ceiling_3_light
            type: brightness_increase
          - device_id: dd238a58fe341e5c03b9580222f14d99
            domain: light
            entity_id: light.family_room_ceiling_4_light
            type: brightness_increase
    button_up_long_max_loop_repeats: 100
    action_button_down_long:
      - parallel:
          - device_id: 053168c8cdd3749fc3e6dab7dd716828
            domain: light
            entity_id: light.family_room_ceiling_1_light_2
            type: brightness_decrease
          - device_id: ede31b90874cd569f09cace1f007ef8d
            domain: light
            entity_id: light.family_room_ceiling_2_light
            type: brightness_decrease
          - device_id: 6fa279558227b8c3791d876e0fdc8744
            domain: light
            entity_id: light.family_room_ceiling_3_light
            type: brightness_decrease
          - device_id: dd238a58fe341e5c03b9580222f14d99
            domain: light
            entity_id: light.family_room_ceiling_4_light
            type: brightness_decrease
        enabled: false
      - service: scene.turn_on
        target:
          entity_id: scene.family_room_off_2
        metadata: {}
    button_down_long_max_loop_repeats: 100
    button_down_long_loop: true
```

### To Reproduce

1. Set up an automation using the blueprint to trigger on a long-press of the up or down button.
2. Long-press the button that was set.
3. Go to Settings -> Automations -> _{{relevant automation name}}_ and click "Traces" at the top right.
4. From the drop-down at the top, select the most recent trace (or second-most recent if not still holding the button).
5. From the tabs at the top of the right pane, choose "Trace Timeline". 
6. Observe that a) the action set in Step 1 did not occur, and "Choose: no action taken" appears in the trace timeline.
7. Go to Settings -> Devices -> Helpers -> _{{relevant last-action text helper}}_ and view the currently set text (or second-most recent if not still holding the button). It will not be "move_1_83" as it should be, it will be "move_MoveMode.Down_83_bitmap8.0_bitmap8.0".

### Expected behavior

Action set for long-press of either up or down button will trigger when the button is long-pressed.

### Actual Behaviour

No action is triggered.

### Additional Details

- [X] I'd like to help developing a fix for this issue.

### Additional context

I recently upgraded to the Silicon Labs Multiprotocol firmware for my SkyConnect stick, but not sure if this could have any impact on the incoming ZHA events.
