### ISSUE TITLE
Ikea E1743 only respond to short press

### ISSUE THREAD

**Issue by bkje14** [EPMatt/awesome-ha-blueprints#53]
Thank you for taking the time to report here! :tada:

**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to process your request more rapidly.

This template should only be used to report a bug with a blueprint. If this is not your case, you can [choose a different issue template](https://github.com/EPMatt/awesome-ha-blueprints/issues/new/choose). If you have a question instead, please open a discussion [here](https://github.com/EPMatt/awesome-ha-blueprints/discussions/new).

\*_=required_

## Bug Details\*

- Blueprint name: Controller - IKEA E1743 On/Off Switch & Dimmer
- Home Assistant Core Version: 2021.4.3
- Home Assistant Installation Type: Home Assistant OS

## Description\*

I had an automation configured with short, long and double clicks that have been running smoothly for weeks since i set it up.
Currently the automation only fires correctly when removing actions for the long and double clicks and only having short presses configured.
Configuring either long presses or double click actions results in errors in the execution flow. 

Below is a screen dump of the error when inspecting the flow.

## Automation YAML config\*

```yaml
alias: stue switch
description: Ikea remote som lys styring i stuen
use_blueprint:
  path: EPMatt/ikea_e1743.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.stue_switch_action
    action_button_up_short:
      - service: light.turn_on
        target:
          entity_id: light.stue_lamper
        data:
          brightness_pct: 60
    action_button_down_short:
      - service: light.turn_off
        target:
          entity_id: light.stue_lamper
    helper_last_controller_event: input_text.stue_switch_helper
    action_button_up_long:
      - service: light.turn_on
        target:
          entity_id: light.stue_lamper
        data:
          brightness_step_pct: 15
    action_button_up_double:
      - service: light.turn_on
        target:
          entity_id: light.stue_lamper
        data:
          brightness_pct: 15
    action_button_down_long:
      - service: light.turn_on
        target:
          entity_id: light.stue_lamper
        data:
          brightness_step_pct: -15
    action_button_down_double:
      - service: light.turn_off
        target:
          entity_id: light.spisebords_lamper
    button_up_double_press: true
    button_down_double_press: true
    button_up_long_loop: false
    button_down_long_loop: false
    helper_double_press_delay: 1500
```

## To Reproduce\*

Steps to reproduce the issue:

3. Trigger the automation '....'

## Expected behavior\*

That long presses and double clicks fire expected actions

## Actual Behaviour\*

automation only works when removing actions for long press and double click, otherwise it results in errors

## Additional Details\*

- [x] I'd like to help developing a fix for this issue. 

## Screenshots

![Skærmbillede 2021-05-03 kl  20 37 50](https://user-images.githubusercontent.com/42773361/116918072-bee4ed80-ac4f-11eb-9e11-4331bd178524.png)

## Additional context

After browsing the repo i can't help to think it might somehow be related to #25 or [this post](https://community.home-assistant.io/t/help-needed-with-automation-and-json-template-warning/297258/13?u=bkje14) or perhaps #45
