### ISSUE TITLE
IKEA E1744 SYMFONISK Rotary Remote does not change Homepod volume using rotate

### ISSUE THREAD

**Issue by smartmatic** [EPMatt/awesome-ha-blueprints#533]
### Blueprint name

Controller - IKEA E1744 SYMFONISK Rotary Remote

### Home Assistant Core Version

2023.3.6

### Home Assistant Installation Type

Home Assistant Operating System

### Description

I am trying to use the blueprint to control my new Homepod 2. I can play / pause the Homepod media player but not chnange the volume. Neither up or down.

### Automation YAML config

```yaml
alias: "Büro: Homepod Symfonisk"
description: ""
use_blueprint:
  path: EPMatt/ikea_e1744.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.ikea_symfonisk_sonos_buero_action
    action_rotate_left:
      - service: media_player.volume_down
        data: {}
        target:
          entity_id: media_player.homepod_buero
    action_rotate_left_stop: []
    action_click_short:
      - service: media_player.media_play_pause
        data: {}
        target:
          entity_id: media_player.homepod_buero
    helper_last_controller_event: input_text.symfonisk_sonos_buero
    action_rotate_right:
      - service: media_player.volume_up
        data: {}
        target:
          entity_id: media_player.homepod_buero
    action_click_double:
      - service: media_player.media_next_track
        data: {}
        target:
          entity_id: media_player.homepod_buero
```

### To Reproduce

3. Trigger the automation '....'

### Expected behavior

Volume can be changed up or down using rotate left or rotate right

### Actual Behaviour

Action is not excecuted. Volume does not chnage

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Additional context

Zigbee2MQTT:info  2023-04-02 12:02:06: MQTT publish: topic 'zigbee2mqtt/IKEA SYMFONISK Sonos Buero/action', payload 'brightness_move_down'
Zigbee2MQTT:info  2023-04-02 12:02:07: MQTT publish: topic 'zigbee2mqtt/IKEA SYMFONISK Sonos Buero', payload '{"action":"brightness_stop","battery":74,"brightness":134,"elapsed":293,"linkquality":255,"rate":195,"update":{"installed_version":587728433,"latest_version":587728433,"state":"idle"},"update_available":false}'
Zigbee2MQTT:info  2023-04-02 12:02:07: MQTT publish: topic 'zigbee2mqtt/IKEA SYMFONISK Sonos Buero', payload '{"action":"","battery":74,"brightness":134,"linkquality":255,"rate":195,"update":{"installed_version":587728433,"latest_version":587728433,"state":"idle"},"update_available":false}'
Zigbee2MQTT:info  2023-04-02 12:02:07: MQTT publish: topic 'zigbee2mqtt/IKEA SYMFONISK Sonos Buero/action', payload 'brightness_stop'
Zigbee2MQTT:info  2023-04-02 12:02:08: MQTT publish: topic 'zigbee2mqtt/IKEA SYMFONISK Sonos Buero', payload '{"action":"toggle","battery":74,"brightness":134,"elapsed":1322,"linkquality":244,"rate":195,"update":{"installed_version":587728433,"latest_version":587728433,"state":"idle"},"update_available":false}'
Zigbee2MQTT:info  2023-04-02 12:02:08: MQTT publish: topic 'zigbee2mqtt/IKEA SYMFONISK Sonos Buero', payload '{"action":"","battery":74,"brightness":134,"linkquality":244,"rate":195,"update":{"installed_version":587728433,"latest_version":587728433,"state":"idle"},"update_available":false}'
