### ISSUE TITLE
Bug - UndefinedError: 'dict object' has no attribute 'event'

### ISSUE THREAD

**Issue by ataa** [EPMatt/awesome-ha-blueprints#536]
### Blueprint name

Controller - IKEA E1744 SYMFONISK Rotary Remote

### Home Assistant Core Version

2023.4.4

### Home Assistant Installation Type

Home Assistant Operating System

### Description

```
Error while executing automation automation.controller_ikea_e1744_symfonisk_rotary_remote: UndefinedError: 'dict object' has no attribute 'event'
3:14:02 PM – (ERROR) Automation
Controller - IKEA E1744 SYMFONISK Rotary Remote: Error executing script. Error rendering template for variables at pos 2: UndefinedError: 'dict object' has no attribute 'event'
3:14:02 PM – (ERROR) Automation
```

### Automation YAML config

```yaml
alias: Controller - IKEA E1744 SYMFONISK Rotary Remote
description: ""
use_blueprint:
  path: EPMatt/ikea_e1744.yaml
  input:
    integration: ZHA
    controller_device: 3659701b58b574d729917c8de5b6ba87
    helper_last_controller_event: input_text.ikea_symphonisk_text
    action_rotate_left:
      - device_id: 9c9f5586a53c69878bd1424a3b7f5023
        domain: light
        entity_id: light.office_rgb_i
        type: brightness_decrease
    action_rotate_right:
      - device_id: 9c9f5586a53c69878bd1424a3b7f5023
        domain: light
        entity_id: light.office_rgb_i
        type: brightness_increase
    action_click_short:
      - type: toggle
        device_id: 9c9f5586a53c69878bd1424a3b7f5023
        entity_id: light.office_rgb_i
        domain: light
    rotate_left_loop: true
    rotate_right_loop: true
    action_rotate_left_stop: []
    action_rotate_right_stop: []
```

### To Reproduce

1. add the blueprint.
2. set the configuration and save the automation. then run the automation
3. Trigger the automation by pressing the button and turning the controller rotary encoded.
4. Toggle works but brightness control does not work and after checking the logs, I noticed the error listed above.

### Expected behavior

- Single click to toggle
- Turn right/left to adjust brightness

### Actual Behaviour

- Single press toggle works fine but with a long delay of upto 6 seconds.
- Rotate right/left does not do anything.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
