### ISSUE TITLE
Bug - Styrbar error

### ISSUE THREAD

**Issue by jayjayvm** [EPMatt/awesome-ha-blueprints#537]
### Blueprint name

Controller - IKEA E2001/E2002 STYRBAR Remote control

### Home Assistant Core Version

2023.4.5

### Home Assistant Installation Type

Home Assistant Operating System

### Description

![foutmelding strybar](https://user-images.githubusercontent.com/130906355/233381671-963dd06d-4dc8-4d2e-8b80-606288f4ce0b.png)

Message malformed: Service does not match format <domain><name>for dictionary value @ data .....

No idea what this means no idea why I get this or how to solve this?!

### Automation YAML config

```yaml
text_sensor:
  # There is no yaml code for the blueprint goes wrong.
  - platform: Error
    ip_address:
      name: "${plug_name} - IP"
  - platform: version
    name: "${plug_name} - ESPHome Version"
```

### To Reproduce

3. Trigger the automation '....'

### Expected behavior

That the automation will be writen, but alas nothing goes no safe of filled in blueprint

### Actual Behaviour

Nothing goes, blueprint refuses to save

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Screenshots

![foutmelding strybar](https://user-images.githubusercontent.com/130906355/233382043-be20de6f-80cb-413e-8945-4fffa364a8b4.png)

### Additional context

Just an error getting it running
