### ISSUE TITLE
Bug - volume_down/up_repeat doesn't work if the media player takes more than 250ms to update

### ISSUE THREAD

**Issue by harristom** [EPMatt/awesome-ha-blueprints#539]
### Blueprint name

media_player

### Home Assistant Core Version

2023.4.2

### Home Assistant Installation Type

Home Assistant Supervised

### Description

If the media_player takes more than 250 ms to set the volume (as is the case with an [Alexa media player ](https://github.com/custom-components/alexa_media_player/) then a continuous rotate of the controller will only change the volume by one step

https://github.com/EPMatt/awesome-ha-blueprints/blob/9ee5920a3633c87bd8ee8713b83bbbf4705cc31d/blueprints/hooks/media_player/media_player.yaml#L326

I guess the fix is to remove the 250 ms delay and instead wait for the volume to change (with some kind of timeout)

### Automation YAML config

```yaml
alias: Study Media Player Hook
description: ""
use_blueprint:
  path: EPMatt/media_player.yaml
  input:
    controller_model: IKEA E1744 SYMFONISK Rotary Remote
    media_player: media_player.study
    controller_entity: sensor.symfonisk_volume_action
    volume_steps_short: 20
    volume_steps_long: 20
```

### To Reproduce

1. Setup a media player hook for a media player that takes more than 250 ms to change volume (e.g. Alexa media player)
2. Connect a rotary controller to the media player hook
3. Rotate the controller for an extended time

### Expected behavior

The volume changes by multiple steps

### Actual Behaviour

The volume changes once

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
