### ISSUE TITLE
Bug - Controller - IKEA E1743 TRÅDFRI On/Off Switch & Dimmer - Double Tap stopped working

### ISSUE THREAD

**Issue by tumtumsback** [EPMatt/awesome-ha-blueprints#544]
### Blueprint name

Controller - IKEA E1743 TRÅDFRI On/Off Switch & Dimmer

### Home Assistant Core Version

2023.5.1

### Home Assistant Installation Type

Home Assistant Operating System

### Description

The Blueprint 'Controller - IKEA E1743 On/Off Switch & Dimmer' stopped working after recent Home Assistant update

Upon further inspection it’s simply the double tap feature of that controller/blueprint that’s not working. The single press and long press functionality is working but the double press functionality is dead and appears to be throwing errors in the error log. Here is just one example of what I see simply after a home assistant reboot:

Logger: homeassistant.components.automation
Source: components/automation/config.py:207
Integration: Automation (documentation, issues)
First occurred: 6:58:51 AM (1 occurrences)
Last logged: 6:58:51 AM

Blueprint 'Controller - IKEA E1743 On/Off Switch & Dimmer' generated invalid automation with inputs {'integration': 'deCONZ', 'controller_device': 'd798e7a289381fe620c8ca2f6f1c7c9e', 'helper_last_controller_event': 'input_text.text1', 'action_button_up_double': [{'service': 'light.turn_on', 'data': {}, 'target': {'entity_id': 'light.living_room_fan_lights'}}], 'action_button_down_double': [{'service': ''}], 'button_up_double_press': True, 'button_down_double_press': True, 'helper_double_press_delay': 1000, 'action_button_up_short': [{'type': 'turn_on', 'device_id': 'bc0d7e01c84ff0e016a4c6bd1a6c480b', 'entity_id': 'light.texas_instruments_cc1352_cc2652_z_stack_3_30_build_20220219_living_room_downlights_zha_group_zha_group_0x0002', 'domain': 'light', 'brightness_pct': 100}], 'action_button_down_short': [{'type': 'turn_off', 'device_id': 'bc0d7e01c84ff0e016a4c6bd1a6c480b', 'entity_id': 'light.texas_instruments_cc1352_cc2652_z_stack_3_30_build_20220219_living_room_downlights_zha_group_zha_group_0x0002', 'domain': 'light'}], 'action_button_up_long': [{'device_id': 'bc0d7e01c84ff0e016a4c6bd1a6c480b', 'domain': 'light', 'entity_id': 'light.texas_instruments_cc1352_cc2652_z_stack_3_30_build_20220219_living_room_downlights_zha_group_zha_group_0x0002', 'type': 'brightness_increase'}], 'action_button_down_long': [{'device_id': 'bc0d7e01c84ff0e016a4c6bd1a6c480b', 'domain': 'light', 'entity_id': 'light.texas_instruments_cc1352_cc2652_z_stack_3_30_build_20220219_living_room_downlights_zha_group_zha_group_0x0002', 'type': 'brightness_decrease'}], 'button_up_long_loop': True, 'button_down_long_loop': True, 'button_up_long_max_loop_repeats': 2500, 'button_down_long_max_loop_repeats': 2500}: Service does not match format <domain>.<name> for dictionary value @ data['action'][3]['choose'][3]['sequence'][0]['choose'][0]['sequence'][0]['choose'][0]['sequence'][2]['choose'][0]['sequence'][0]['service']. Got ''

### Automation YAML config

```yaml
alias: Bathroom - Doubletap - Fan
description: ""
use_blueprint:
  path: EPMatt/ikea_e1743.yaml
  input:
    integration: deCONZ
    controller_device: 1291a6dbd2844a87b99006cff6b0a308
    helper_last_controller_event: input_text.text1
    button_up_double_press: true
    button_down_double_press: true
    action_button_up_double:
      - type: turn_on
        device_id: 4b3c7d62506e2024325e9ac0a60eeed0
        entity_id: switch.bathroom_fan
        domain: switch
    action_button_down_double:
      - type: turn_off
        device_id: 4b3c7d62506e2024325e9ac0a60eeed0
        entity_id: switch.bathroom_fan
        domain: switch
    helper_double_press_delay: 1000
```

### To Reproduce

3. Trigger the automation '....'

Logger: homeassistant.helpers.template
Source: helpers/template.py:237
First occurred: 8:35:01 AM (1 occurrences)
Last logged: 8:35:01 AM

Template variable error: 'dict object' has no attribute 'event' when rendering '{%- if integration_id == "zigbee2mqtt" -%} {{ trigger.event.data.new_state.state }} {%- elif integration_id == "deconz" -%} {{ trigger.event.data.event }} {%- elif integration_id == "zha" -%} {{ trigger.event.data.command }}{{"_" if trigger.event.data.args|length > 0}}{{ trigger.event.data.args|join("_") }} {%- endif -%}'

Logger: homeassistant.components.automation.bathroom_doubletap_fan
Source: helpers/script.py:410
Integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 8:35:01 AM (1 occurrences)
Last logged: 8:35:01 AM

Bathroom - Doubletap - Fan: Error executing script. Error rendering template for variables at pos 2: UndefinedError: 'dict object' has no attribute 'event'

Logger: homeassistant.components.automation.bathroom_doubletap_fan
Source: components/automation/__init__.py:254
Integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 8:35:01 AM (1 occurrences)
Last logged: 8:35:01 AM

Error while executing automation automation.bathroom_doubletap_fan: UndefinedError: 'dict object' has no attribute 'event'

### Expected behavior

I would expect the device_id of 4b3c7d62506e2024325e9ac0a60eeed0 to turn on/off.

### Actual Behaviour

Nothing -- error is thrown, and device never receives command.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
