### ISSUE TITLE
Bug - IKEA E1744 SYMFONISK Rotary Remote doesn't stop increasing or decreasing the volume.

### ISSUE THREAD

**Issue by ThatBeardGuy** [EPMatt/awesome-ha-blueprints#547]
### Blueprint name

Hook - IKEA E1744 SYMFONISK Rotary Remote

### Home Assistant Core Version

2023.5.2

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Recently my E1744 remote stopped working correctly. I saw another bug report but this seemed to be an issue regarding ZHA, this is Z2mqtt.

I have tried and troubleshooted a few things, making new blueprints to replace the old maybe outdated ones, no luck.

Looking at the text input helper, there is a rotate action recorded, also a stop action recorded as it should. So my best guess will be that the issue lies in the hook. I just don't know what changed since I haven't touched the automations in quite some time.

### Automation YAML config

```yaml
#controller

alias: Controller - IKEA E1744 SYMFONISK Rotary Remote
description: ""
use_blueprint:
  path: EPMatt/ikea_e1744.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.dial_button_action
    helper_last_controller_event: input_text.symfonisk
    rotate_left_loop: true
    rotate_right_loop: true
    action_rotate_left: []
    action_rotate_left_stop: []
    action_rotate_right: []
    helper_debounce_delay: 0

#hook

alias: Hook - Media Player
description: ""
use_blueprint:
  path: EPMatt/media_player.yaml
  input:
    controller_device: ac3bd30286fa7c9f59f9aafc5017b18a
    controller_entity: sensor.dial_button_action
    controller_model: IKEA E1744 SYMFONISK Rotary Remote
    media_player: #input media player here
```

### To Reproduce

1. Have the controller and the hook setup like in the YAML and connect it to a media player, in my case a google home speaker or group. But it also does the same thing when connected to any helper or other media player.
2. Rotate the remote.
3. Stop rotating the remote

### Expected behavior

The volume should increase or decrease slightly.

### Actual Behaviour

The volume increases or decreases to full blast or mute.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
