### ISSUE TITLE
Bug - IKEA Rotary Remote Controller Automation only works with single tap

### ISSUE THREAD

**Issue by motoridersd** [EPMatt/awesome-ha-blueprints#553]
### Blueprint name

Hook - Media Player

### Home Assistant Core Version

2023.6.2

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Tapping the IKEA Rotary controller once will trigger the Controller Automation, which then plays/pauses the media via the Media Player hook. Turning the knob or double tapping will generate a Controller Automation event, but the Hook doesn't perform the associated task.

### Automation YAML config

```yaml
alias: New IKEA Symfonisk Knob Automation
description: ""
use_blueprint:
  path: EPMatt/ikea_e1744.yaml
  input:
    integration: ZHA
    controller_device: 244dc58991bf3d0bc5879ea49d68fd2f
    helper_last_controller_event: input_text.helper_last_controller_event_rotary_ikea
    action_rotate_left: []
    action_rotate_right: []
    rotate_left_loop: false
    rotate_right_loop: false
    action_click_short: []
    action_click_double: []

alias: New IKEA Symfonisk Knob Automation
description: ""
use_blueprint:
  path: EPMatt/ikea_e1744.yaml
  input:
    integration: ZHA
    controller_device: 244dc58991bf3d0bc5879ea49d68fd2f
    helper_last_controller_event: input_text.helper_last_controller_event_rotary_ikea
    action_rotate_left: []
    action_rotate_right: []
    rotate_left_loop: false
    rotate_right_loop: false
    action_click_short: []
    action_click_double: []
```

### To Reproduce

1. Start music playback on media player tied to Media Player Hook
2. Rotate IKEA Controller
3. Volume does not change
4. See logbook entries in screenshot section

### Expected behavior

The volume will change with rotation

### Actual Behaviour

Nothing happens

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Screenshots

![image](https://github.com/EPMatt/awesome-ha-blueprints/assets/5197858/0ce0397e-2fe5-47d0-95ec-2ce8f2016c71)

### Additional context

I manually updated the blueprint to remove extra spaces/characters that were causing volume rotations to not stop. This worked great for a while, but maybe the latest update broke something else https://github.com/EPMatt/awesome-ha-blueprints/issues/547
