### ISSUE TITLE
Bug - Hook - Lights Automation loops thousands of times when used with E1743 and LED1836G9 bulb

### ISSUE THREAD

**Issue by mark1foley** [EPMatt/awesome-ha-blueprints#557]
### Blueprint name

Hook - Light

### Home Assistant Core Version

2023.7.2

### Home Assistant Installation Type

Home Assistant Operating System

### Description

I recently purchase some Ikea 1743 switches and LED1836G9 bulbs.  I used the "Controller - IKEA E1743 TRÅDFRI On/Off Switch & Dimmer" blueprint (thank you!) and created automations to turn the bulbs on and off using the switch that work great.

I then used the "Hook - Light" blueprint to create automations to adjust the brightness with a long press.  However, when using a long press (either up or down) the automation seems to loop endlessly (or at least for several minutes).  The bulb brightness goes for the lowest to the highest value (or vice versa for a long down press).

I increased the "Light brightness steps - long actions" option to 100 and, although it reduced change in brightness for each step it still has the same result.  I even tried disabling the "Up button long press - loop until release" option in the 1743 automation but the problem persisted.  Also, the traces for the Hook automation show them running for several minutes.  I have 3 pairs of switches and bulbs and they all experience the same issue.

I'm presume it's something I done but can't work out what.

### Automation YAML config

```yaml
alias: Mqtt-SpareBedroomLampLeft
description: ""
use_blueprint:
  path: EPMatt/ikea_e1743.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.sw_dim_spare_bedroom_lamp1_action
    helper_last_controller_event: input_text.sw_dim_spare_bedroom_lamp1_action
    action_button_up_short:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.sw_pwr_4gn_spare_bedroom1_p2
    action_button_down_short:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.sw_pwr_4gn_spare_bedroom1_p2
    button_up_long_loop: false
    button_down_long_loop: false
    button_up_long_max_loop_repeats: 5
    button_down_long_max_loop_repeats: 5
```

### To Reproduce

1. Do long press, either up or down, on switch.
2.

### Expected behavior

Brightness steps should stop when button is released

### Actual Behaviour

Automation runs after the button is released, even when looping is disabled.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Screenshots

![image](https://github.com/EPMatt/awesome-ha-blueprints/assets/50077728/29b3dc4c-6d94-4abc-9bd5-6ae2b3cf4fc1)

![image](https://github.com/EPMatt/awesome-ha-blueprints/assets/50077728/d8c81198-bbcf-442b-bbab-4869523094a8)

![image](https://github.com/EPMatt/awesome-ha-blueprints/assets/50077728/0da45ef4-0479-41c5-a369-71be593ccd49)

[Zigbee2MQTT - Work - Microsoft​ Edge 2023-07-16 10-40-13.zip](https://github.com/EPMatt/awesome-ha-blueprints/files/12063078/Zigbee2MQTT.-.Work.-.Microsoft.Edge.2023-07-16.10-40-13.zip)
