### ISSUE TITLE
Bug - IKEA Symfonisk e1744 connected as media_player controller

### ISSUE THREAD

**Issue by stefancvetkovic** [EPMatt/awesome-ha-blueprints#569]
### Blueprint name

https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e1744

### Home Assistant Core Version

2023.10.10

### Home Assistant Installation Type

Home Assistant Container

### Description

Im using zigbee2mqtt, and I paired my ikea symfonisk controller.
I noticed in my logs that it shows actions in my payload like: play/pause (single short click), previous/next (left/right encoder turning)

I want to have light controller with signle short pressing account, double tap, dimm in dimm out.

Because of wrong mapping, my blueprint does not work.

Im not sure where this mapping is done? Thanks

### Automation YAML config

```yaml
alias: Controller - IKEA E1744 SYMFONISK Rotary Remote
description: ""
use_blueprint:
  path: EPMatt/ikea_e1744.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.ikea_symfonisk_test_action
    helper_last_controller_event: input_text.ikea_symfonisk_blueprint_helper
    action_click_short:
      - service: persistent_notification.create
        data:
          message: test
          title: test
```

### To Reproduce

Just a question for mapping

### Expected behavior

shold return payload short click, dopuble pressed and similar

### Actual Behaviour

returns different actions than expected (play/stop, next/previous)

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
