### ISSUE TITLE
IKEA LED2003G10 with IKEA E2001/E2002 Styrbar remote / Zigbee2MQTT

### ISSUE THREAD

**Issue by monsterflo** [EPMatt/awesome-ha-blueprints#581]
### Blueprint name

Hook - Light

### Home Assistant Core Version

2023.11.2

### Home Assistant Installation Type

Home Assistant Supervised

### Description

Hello,
my Ikea bulbs misbehave for a while now and since it's getting darker outside this issue starts to annoy me again.
When dimming or brightening the lights they just keep on going instead of stopping when the remote button is released.
I don't know if this connected with an update of Zigbee2MQTT and if the behavour of Z2M changed.

Any help is appreciated.

Thanks in advance
Florian

### Automation YAML config

```yaml
alias: Wandlampe Fernbedienung AN-AUS-Helligkeit-Farbe
description: ""
use_blueprint:
  path: EPMatt/ikea_e2001_e2002.yaml
  input:
    integration: Zigbee2MQTT
    controller_device: 21124e381ab0840918bef480453a2c8c
    controller_entity: sensor.zb_remote_eg_kz1_action
    helper_last_controller_event: input_text.zb_remote_kz1_helper


alias: Wandlampe Fernbedienung
description: ""
use_blueprint:
  path: EPMatt/light.yaml
  input:
    controller_device: 21124e381ab0840918bef480453a2c8c
    controller_entity: sensor.zb_remote_eg_kz1_action
    controller_model: IKEA E2001/E2002 STYRBAR Remote control
    light: light.kinderzimmer_wandlampe
    min_brightness: 2
    force_brightness: true
    on_brightness: 5
```

### To Reproduce

3. Trigger the automation '....'

### Expected behavior

stop dimming/brightening when remote button is released

### Actual Behaviour

dimming/brightening doesn't stop

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
