### ISSUE TITLE
Ikea STYRBAR Blueprint double Tap #mapping 2 Configuration 

### ISSUE THREAD

**Issue by aravindnadumane** [EPMatt/awesome-ha-blueprints#585]
### Blueprint name

Controller - IKEA E2001/E2002 STYRBAR Remote control

### Home Assistant Core Version

2023.12.1

### Home Assistant Installation Type

Home Assistant Operating System

### Description

I configured my TRÅDFRI lights (LED1924G9) with the STYRBAR IKEA E2001/E2002.

used Blueprints:
Controller: [Controller - IKEA E2001/E2002 STYRBAR Remote control | Awesome HA Blueprints 2](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e2001_e2002/)
bulb: [Hook - Light | Awesome HA Blueprints 2](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/hooks/light/)

All works well but I cannot dim/bright the light step-wise. 
The Brightness Up button short press no effect. Long press (just for a 2 sec, gives a maximum brightness. same with the Brightness down button, pressing is long shall bring it to a the lowest brightness. intermediate brightness is not possible.

Is there a way to configure Mapping#2 ?
my Automation from these blueprints doesn’t have this option, which i atleast expected that i could use any dropdown to select the one of those mappings listed in the controller blueprint link

![image](https://github.com/EPMatt/awesome-ha-blueprints/assets/43443060/fa967c60-c22b-4865-8394-f082c4b9993e)

### Automation YAML config

```yaml
- id: '1701696353263'
  alias: EsszimmerWandLampeSchalter
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e2001_e2002.yaml
    input:
      integration: Zigbee2MQTT
      controller_entity: sensor.esszimmerwandlampe_schalter_action
      controller_device: a62b5b10d8067eac2358587e0dd60446
      button_left_double_press: false
      helper_last_controller_event: input_text.helper_last_loop_event_input
      button_up_double_press: true
      button_down_double_press: true
- id: '1701699785167'
  alias: EsszimmerWandLampeA_Automation
  description: ''
  use_blueprint:
    path: EPMatt/light.yaml
    input:
      controller_device: a62b5b10d8067eac2358587e0dd60446
      controller_entity: sensor.esszimmerwandlampe_schalter_action
      controller_model: IKEA E2001/E2002 STYRBAR Remote control
      light: light.esszimmerwandlampe_lampea
      on_brightness: 121
- id: '1701701229646'
  alias: EsszimmerWandLampeB_Automation
  description: ''
  use_blueprint:
    path: EPMatt/light.yaml
    input:
      controller_device: a62b5b10d8067eac2358587e0dd60446
      controller_entity: sensor.esszimmerwandlampe_schalter_action
      controller_model: IKEA E2001/E2002 STYRBAR Remote control
      light: light.esszimmerwandlampe_lampeb
      on_brightness: 121
```

### To Reproduce

Press the Brightness Up button "Long press".
or
Press the Brightness down button "Long press"

### Expected behavior

Brightness Up button "Long press":
  shall result in the small increase in the brightness
Brightness down button "Long press"
  shall result in the small decrease in the brightness

### Actual Behaviour

Brightness Up button "Long press":
  Bightness keeps increasing untill maximum level is achieved
Brightness down button "Long press"
  Bightness keeps decreasing untill minimum level is achieved

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Screenshots

![image](https://github.com/EPMatt/awesome-ha-blueprints/assets/43443060/42da7479-a804-4592-9027-f44b6d73bedd)
