### ISSUE TITLE
Bug - Aqara Opple 6 Button don't work (wxcjkg13lm)

### ISSUE THREAD

**Issue by Typ1er** [EPMatt/awesome-ha-blueprints#591]
### Blueprint name

xiaomi_wxcjkg13lm.yaml

### Home Assistant Core Version

2024.1.1

### Home Assistant Installation Type

Home Assistant Operating System

### Description

I have a problem getting my Opple 6 button to work with the Blueprint.

From another blueprint for the 2 button Opple. I had to remove this line (attribute: action), then the blueprint worked. I also had the same problem with my HueTap (ZGP) switch. Both blueprints contain this line under the trigger:

trigger:
  platform: state
  entity_id: !input action_sensor
# attribute: action

Do I have the wrong setting in Zigbee2mqtt or has something changed in HomeAssistant? Can I change the setting here, if so where?

Here is the blueprint, which works so far.
https://community.home-assistant.io/t/zigbee2mqtt-aqara-opple-switch-2-buttons-wxcjkg11lm/504310

The automation is triggered somehow, the timestamp is reset each time.

### Automation YAML config

```yaml
alias: Controller - Xiaomi WXCJKG13LM Aqara Opple 6 button remote
description: ""
use_blueprint:
  path: EPMatt/xiaomi_wxcjkg13lm.yaml
  input:
    action_button_1_short:
      - service: light.toggle
        metadata: {}
        data: {}
        target:
          device_id: 25ec6d2e8579a2873ead83e0d2bd3f41
    integration: Zigbee2MQTT
    controller_entity: sensor.schlafzimmer_lichtschalter_2_action
```

### To Reproduce

3. Trigger the automation '....'

### Expected behavior

no text

### Actual Behaviour

 no text

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
