### ISSUE TITLE
Bug - Ikea Shortcut Button Double Click does not work

### ISSUE THREAD

**Issue by hackintoshlover** [EPMatt/awesome-ha-blueprints#593]
### Blueprint name

Controller - IKEA E1812 TRÅDFRI Shortcut button

### Home Assistant Core Version

2023.11.3

### Home Assistant Installation Type

Home Assistant Operating System

### Description

I imported the Ikea shortcut button blueprint and set it up everything works as expected, except double click.
Attached screenshots of setup with error.
I having configured the device using zigbee 2 mqtt setup.

### Automation YAML config

```yaml
Attachedalias: Controller - IKEA E1812 TRÅDFRI Shortcut button
description: ""
use_blueprint:
  path: EPMatt/ikea_e1812.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.0x94deb8fffee14abe_action
    action_button_double:
      - service: switch.toggle
        data: {}
        target:
          device_id: 9d9d853ecd3efa803f10702640113de1
    helper_double_press_delay: 1000
    button_double_press: true
    helper_last_controller_event: input_text.helper_last_controller_event
```

### To Reproduce

Import blueprint.
Setup as image below.
Run.

### Expected behavior

Double click should toggle switch.

### Actual Behaviour

Nothing.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Screenshots

![Screenshot (364)](https://github.com/EPMatt/awesome-ha-blueprints/assets/40655406/d4f1b5a1-26dd-43fc-90af-317f230ee56b)
![Screenshot (363)](https://github.com/EPMatt/awesome-ha-blueprints/assets/40655406/52756f14-2370-409f-96e7-a4416eebf282)
![Screenshot (362)](https://github.com/EPMatt/awesome-ha-blueprints/assets/40655406/c74f5005-9b8b-43a8-a731-0103b69e16ed)
![Screenshot (361)](https://github.com/EPMatt/awesome-ha-blueprints/assets/40655406/9ea2bd12-6069-4cac-8ca9-356519ed89b9)
![Screenshot (360)](https://github.com/EPMatt/awesome-ha-blueprints/assets/40655406/204dc24c-2a7c-424a-8571-b3458b01ffc5)
![Screenshot (359)](https://github.com/EPMatt/awesome-ha-blueprints/assets/40655406/76bbdca4-c5d0-4041-a759-9c4a404e9f01)
![Screenshot (358)](https://github.com/EPMatt/awesome-ha-blueprints/assets/40655406/c4031001-eedc-4dd9-90c3-00daac46d1ff)
![Screenshot (357)](https://github.com/EPMatt/awesome-ha-blueprints/assets/40655406/291acb7b-a4fd-4e63-93de-ffadab388961)
![Screenshot (356)](https://github.com/EPMatt/awesome-ha-blueprints/assets/40655406/c5e7beba-3858-4374-818a-c3230c815153)
