### ISSUE TITLE
Bug - Wrong actions Styrbar for ZHA

### ISSUE THREAD

**Issue by LikonCZ** [EPMatt/awesome-ha-blueprints#596]
### Blueprint name

Controller - IKEA E2001/E2002 STYRBAR Remote control

### Home Assistant Core Version

2024.1.6

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Actions for UP and DOWN buttons long press were wrong for ZHA. Buddle press and release doesnt work either for all buttons. In additional content, there is my repaired code (just for long press of UP or DOWN) with comments what was changed.

### Automation YAML config

```yaml
.
```

### To Reproduce

Using blueprint above for long press and release of UP and DOWN button

### Expected behavior

Actions working

### Actual Behaviour

Actions not working

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Additional context

```yaml
    zha:
      button_left_short:
        - press_257_13_0
      button_left_long:
        - hold_3329_0
      button_left_release:
        - release_1365
      button_right_short:
        - press_256_13_0
      button_right_long:
        - hold_3328_0
      button_right_release:
        - release_-27903
      button_up_short:
        - "on"
      button_up_long:
        - move_with_on_off_MoveMode.Up_83 #originaly move_with_on_off_0_83
      button_up_release:
        - stop
      button_down_short:
        - "off"
      button_down_long:
        - move_MoveMode.Down_83_0_0 #originaly move_1_83
      button_down_release:
        - stop
```
