### ISSUE TITLE
Bug - Volume controls do not work with Samsung Smart TVs

### ISSUE THREAD

**Issue by mkopec** [EPMatt/awesome-ha-blueprints#599]
### Blueprint name

media_player

### Home Assistant Core Version

2024.1.6

### Home Assistant Installation Type

Home Assistant Container

### Description

Samsung Smart TV integrations expose a 0 - 100 scale volume slider that is not functional with my TV - Samsung S95B (2022). Calling the `volume_{up, down}` services on them works fine, only the slider setting does not get applied.

The media player automaiton tries to set a volume explicitly if possible, so it fails on my TV. I worked this around by simply always calling the `volume_{up,down}` services in the blueprint.

Not sure if this is a bug for you, for hass or for Samsung to solve. Can we have a toggle for disabling explicit volume control and only using the up / down actions?

### Automation YAML config

```yaml
remote:


- id: '1707323080188'
  alias: Hook - Bedroom lights
  description: ''
  use_blueprint:
    path: EPMatt/light.yaml
    input:
      controller_entity: sensor.styrbar_action
      controller_model: IKEA E2001/E2002 STYRBAR Remote control
      light: light.bedroom_2
      light_color_mode: Auto
      light_transition: 100
      brightness_steps_short: 10
      brightness_steps_long: 10
      min_brightness: 1
      smooth_power_on: false
      smooth_power_off: false
```

hook:
```
- id: '1707349134240'
  alias: Hook - Media Player
  description: ''
  use_blueprint:
    path: EPMatt/media_player.yaml
    input:
      controller_entity: sensor.styrbar_action
      controller_model: IKEA E2001/E2002 STYRBAR Remote control
      media_player: media_player.samsung_s95b
```
```


### To Reproduce

1. Long press the up button on the remote
2. Wait for volume to begin changing

### Expected behavior

Volume starts to increase

### Actual Behaviour

Volume stays the same

### Additional Details

- [X] I'd like to help developing a fix for this issue.

### Screenshots

_No response_

### Additional context

_No response_
