### ISSUE TITLE
Spook unknown device 

### ISSUE THREAD

**Issue by brusarp** [EPMatt/awesome-ha-blueprints#601]
### Blueprint name

Controller - IKEA E1524/E1810 TRÅDFRI Wireless 5-Button Remote

### Home Assistant Core Version

2024.2.2

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Hi!
I've installed Spook on my HA and after the last update it recognize some unknown device referred to this blueprint.

![Screenshot_20240217_135651_Home Assistant](https://github.com/EPMatt/awesome-ha-blueprints/assets/14950532/7631faf6-0229-4cc0-905c-95a795fb7b5a)

### Automation YAML config

```yaml
alias: Telecomando Ikea
description: Comandi da Ikea
use_blueprint:
  path: EPMatt/ikea_e1524_e1810.yaml
  input:
    integration: Zigbee2MQTT
    action_button_center_double: []
    action_button_center_short:
      - type: toggle
        device_id: xxxxxxxx
        entity_id: light.ikea_salotto
        domain: light
    controller_entity: sensor.telecomando_1_action
    helper_last_controller_event: input_text.controller_telecomando1
    action_button_left_short: []
    action_button_up_short:
      - device_id: xxxxxxx
        domain: light
        entity_id: light.ikea_salotto
        type: brightness_increase
    action_button_down_short:
      - device_id: xxxxxxx
        domain: light
        entity_id: light.ikea_salotto
        type: brightness_decrease
    button_up_long_loop: true
    button_down_long_loop: true
    action_button_up_long:
      - device_id: xxxxxxx
        domain: light
        entity_id: light.ikea_salotto
        type: brightness_increase
    action_button_down_long:
      - device_id: xxxxxxxx
        domain: light
        entity_id: light.ikea_salotto
        type: brightness_decrease
```

### To Reproduce

1. Install Spook from HACS
2. Spook notify you

### Expected behavior

No Spook notification 

### Actual Behaviour

Spook notify of unknown device 

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
