### ISSUE TITLE
Bug - IKEA e1812 double press does not fire any action

### ISSUE THREAD

**Issue by drublin** [EPMatt/awesome-ha-blueprints#603]
### Blueprint name

Controller - IKEA E1812 TRÅDFRI Shortcut button [Version 2022.08.08]

### Home Assistant Core Version

2024.3.0

### Home Assistant Installation Type

Home Assistant Operating System

### Description

i try to configure Tradfri E1812 Shortcut button to work {Z2MQTT]. Single and Long press work well. Double press though does not fire anything.
*Single press Logs (works well):
>`Debug 2024-03-14 13:59:11Received Zigbee message from 'SHORTCUT button - Bedroom', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 0
Info 2024-03-14 13:59:11MQTT publish: topic 'zigbee2mqtt/SHORTCUT button - Bedroom', payload '{"action":"on","battery":90,"linkquality":123,"update":{"installed_version":604241926,"latest_version":604241926,"state":"idle"},"update_available":null}'
Info 2024-03-14 13:59:11MQTT publish: topic 'zigbee2mqtt/SHORTCUT button - Bedroom', payload '{"action":"","battery":90,"linkquality":123,"update":{"installed_version":604241926,"latest_version":604241926,"state":"idle"},"update_available":null}'
Info 2024-03-14 13:59:11MQTT publish: topic 'zigbee2mqtt/SHORTCUT button - Bedroom/action', payload 'on'
Debug 2024-03-14 13:59:12Received MQTT message on 'zigbee2mqtt/Bath_4/set' with data '{"state":"ON","brightness":3,"color_temp":357}'
Debug 2024-03-14 13:59:12Publishing 'set' 'brightness' to 'Bath_4'`

*Double press Logs (doesn't work):

> `Debug 2024-03-14 14:02:56Received Zigbee message from 'SHORTCUT button - Bedroom', type 'commandOff', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 0
Info 2024-03-14 14:02:56MQTT publish: topic 'zigbee2mqtt/SHORTCUT button - Bedroom', payload '{"action":"off","battery":90,"linkquality":120,"update":{"installed_version":604241926,"latest_version":604241926,"state":"idle"},"update_available":null}'
Info 2024-03-14 14:02:56MQTT publish: topic 'zigbee2mqtt/SHORTCUT button - Bedroom', payload '{"action":"","battery":90,"linkquality":120,"update":{"installed_version":604241926,"latest_version":604241926,"state":"idle"},"update_available":null}'
Info 2024-03-14 14:02:56MQTT publish: topic 'zigbee2mqtt/SHORTCUT button - Bedroom/action', payload 'off'`

The blueprint documents say that double press action is not exposed, and is virtual with a separate switch. In the Z2Mqtt docs for IKEA shortcut button i see a consistent description of "action":"off" on double press. Same "off" action i see in the Z2M logs upon Double Press, but automation does not do what it is supposed to do.

I see the blueprint describes the exposed actions except "off". 
`zigbee2mqtt:
      button_short:
        - "on"
      button_long:
        - brightness_move_up
      button_release:
        - brightness_stop
  button_short: '{{ actions_mapping[integration_id]["button_short"] }}'
  button_long: '{{ actions_mapping[integration_id]["button_long"] }}'
  button_release: '{{ actions_mapping[integration_id]["button_release"] }}'
`

### Automation YAML config

```yaml
alias: Shortcut button (simple) Bedroom - action
description: ""
use_blueprint:
  path: EPMatt/ikea_e1812.yaml
  input:
    integration: Zigbee2MQTT
    action_button_short:
      - service: scene.turn_on
        metadata: {}
        target:
          entity_id: scene.sc_2_sleep
    action_button_long:
      - service: scene.turn_on
        metadata: {}
        target:
          entity_id: scene.sc_2_evening
    action_button_release: []
    helper_last_controller_event: input_text.blueprint_text_helper_shortcut_button_bedroom
    controller_entity: sensor.shortcut_button_bedroom_action
    action_button_double:
      - service: scene.turn_on
        metadata: {}
        target:
          entity_id: scene.sc_all_upstairs_lights_off
    button_long_loop: false
    button_long_max_loop_repeats: 4
    button_double_press: true
    helper_double_press_delay: 1000
```

### To Reproduce

1.  Create an Automation based on EPMatt E1812 blueprint.
2. Assign an Action to Double Press
3. Double Press the button.
4. See MQTT press log with "action":"off", see no automation actions.

### Expected behavior

activate a scene on button double press.

### Actual Behaviour

double press is seen in logs, no automation actions are fired.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Screenshots

Short Press and light going on:
![image](https://github.com/EPMatt/awesome-ha-blueprints/assets/102928430/ef080cc6-5c62-4378-a375-de0ecf96dcee)

Double Press and no light action:
![image](https://github.com/EPMatt/awesome-ha-blueprints/assets/102928430/a46a6aa9-6cca-4402-9aa5-824738434703)

![image](https://github.com/EPMatt/awesome-ha-blueprints/assets/102928430/24fd0f8d-3d28-4fa8-b43a-757e4a3c6786)
