### ISSUE TITLE
Bug - Philips 324131092621 with Hook Light

### ISSUE THREAD

**Issue by loicdelecroix** [EPMatt/awesome-ha-blueprints#607]
### Blueprint name

Hook - Light

### Home Assistant Core Version

2024.5.4

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Hello,

I've been trying to make the Controller + Hook work for the Philips 324131092621 Hue Switch, but the Hook Light automation is never triggered.

I can see that the Controller automation is triggered, and the input_text helper is filled with values, but on the other hand, the Hook Light automation is never triggered : 
![image](https://github.com/EPMatt/awesome-ha-blueprints/assets/45817385/bc6e2ca0-49c1-4aba-bf94-dc45516ccb84)
![image](https://github.com/EPMatt/awesome-ha-blueprints/assets/45817385/65c97a41-91b2-4516-962d-6fc0d840fdda)

Is it something wrong on my conf, or is it a bug ?
Thanks for your help.

### Automation YAML config

```yaml
## Controller
id: "1716235558696"
alias: Controller - Philips Hue Salon
description: ""
use_blueprint:
  path: EPMatt/philips_324131092621.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.switch_salon_action
    helper_last_controller_event: input_text.light_salon_switch

## Hook
id: "1716235690485"
alias: Hook - Light Salon
description: ""
use_blueprint:
  path: EPMatt/light.yaml
  input:
    controller_entity: sensor.switch_salon_action
    controller_model: Philips 324131092621 Hue Dimmer switch
    light: light.led_salon_2
    light_color_mode: None
```

### To Reproduce

3. Trigger the automation '....'

### Expected behavior

The Hook - Light automation is triggered

### Actual Behaviour

The Hook - Light automation is not triggered

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
