### ISSUE TITLE
Bug - Controller - Hue Dimmer switch only working for one entity per trigger 

### ISSUE THREAD

**Issue by DarthSonic** [EPMatt/awesome-ha-blueprints#608]
### Blueprint name

Controller - Philips 324131092621 Hue Dimmer switch

### Home Assistant Core Version

2024.8.1

### Home Assistant Installation Type

Home Assistant Operating System

### Description

When single press Hue Dimmer v1 ZHA is triggering automation of blueprint but only turns on / off one entity configured in the action. When pressing a second time (single click), the second entity will be turned on / off also most of the time.

Both entities are ZHA groups of lights. 

### Automation YAML config

```yaml
alias: Dimmer Wohnzimmer
description: ""
use_blueprint:
  path: EPMatt/philips_324131092621.yaml
  input:
    integration: ZHA
    controller_device: 30b66a32381456e7b170cfd28c40b85c
    action_button_on_short:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          entity_id:
            - light.silicon_labs_ezsp_essbereich
            - light.silicon_labs_ezsp_wohnbereich
    action_button_on_double: []
    action_button_off_long:
      - action: light.turn_off
        target:
          entity_id:
            - light.home_office_spot_licht
            - light.tv_sync_only
            - light.silicon_labs_ezsp_essbereich
            - light.wohnzimmer_sync
            - light.silicon_labs_ezsp_wohnbereich
        data: {}
    action_button_on_long:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          entity_id:
            - light.home_office_spot_licht
            - light.silicon_labs_ezsp_essbereich
            - light.wohnzimmer_sync
            - light.silicon_labs_ezsp_wohnbereich
    action_button_off_short:
      - action: light.turn_off
        target:
          entity_id:
            - light.silicon_labs_ezsp_essbereich
            - light.silicon_labs_ezsp_wohnbereich
            - light.home_office_spot_licht
        data: {}
    action_button_off_double: []
    helper_last_controller_event: input_text.dimmer_wohnzimmer_last_event
    button_on_double_press: false
    button_off_double_press: false
    action_button_up_short: []
    action_button_off_release: []
    action_button_on_release: []
```

### To Reproduce

3. Trigger the automation '....'

### Expected behavior

Multiple lights on / off with a single press. 

### Actual Behaviour

Only one entity (zha group) is turned on / off. 

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
