### ISSUE TITLE
Bug - Automation delay step cancels when (Optional) Expose up button double press event or (Optional) Expose down button double press event are on

### ISSUE THREAD

**Issue by atrain2009** [EPMatt/awesome-ha-blueprints#616]
### Blueprint name

Controller - IKEA E1766 TRÅDFRI Open/Close Remote

### Home Assistant Core Version

2024.10.0

### Home Assistant Installation Type

Home Assistant Container

### Description

The automations for two of my IKEA TRADFRI E1766 remotes cancel after a delay when I have either "Optional) Expose up button double press event" or "Optional) Expose down button double press event" toggled on. I'm not sure why, since I use the same blueprint for another IKEA TRADFRI E1766 remote that works fine, but those two remotes seem to get stuck at a delay built to check the Double Press Delay during the automation - when I check the Trace for the delay, I see "done: false", which seems to cancel the automation. I find that the automation completes successfully once I toggle "Optional) Expose up button double press event" and "Optional) Expose down button double press event" off.

### Automation YAML config

```yaml
alias: IKEA Desk Remote - E1766 TRÅDFRI Open/Close Remote
description: ""
use_blueprint:
  path: EPMatt/ikea_e1766.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.ikea_remote_desk_action
    action_button_up_short:
      - action: scene.create
        metadata: {}
        data:
          scene_id: desk_window_revert
          snapshot_entities:
            - cover.blinds_desk
      - if:
          - condition: state
            entity_id: timer.tamper_lock_desk_down
            state: active
        then:
          - action: switch.toggle
            metadata: {}
            data: {}
            target:
              entity_id: switch.buzzer
          - action: cover.stop_cover
            metadata: {}
            data: {}
            target:
              device_id: 29a333085a757dc7543fa3ed613ea110
          - action: scene.turn_on
            metadata: {}
            target:
              entity_id: scene.desk_window_revert
        else:
          - action: cover.open_cover
            data: {}
            target:
              device_id: 29a333085a757dc7543fa3ed613ea110
          - action: timer.start
            metadata: {}
            data: {}
            target:
              entity_id: timer.tamper_lock_desk_up
    action_button_down_short:
      - action: scene.create
        metadata: {}
        data:
          scene_id: desk_window_revert
          snapshot_entities:
            - cover.blinds_desk
      - if:
          - condition: state
            entity_id: timer.tamper_lock_desk_up
            state: active
        then:
          - action: switch.toggle
            metadata: {}
            data: {}
            target:
              entity_id: switch.buzzer
          - action: cover.stop_cover
            metadata: {}
            data: {}
            target:
              device_id: 29a333085a757dc7543fa3ed613ea110
          - action: scene.turn_on
            metadata: {}
            target:
              entity_id: scene.desk_window_revert
        else:
          - action: cover.close_cover
            data: {}
            target:
              device_id: 29a333085a757dc7543fa3ed613ea110
          - action: timer.start
            metadata: {}
            data: {}
            target:
              entity_id: timer.tamper_lock_desk_down
    helper_last_controller_event: input_text.helper_last_controller_event_back
    action_button_up_double:
      - action: cover.open_cover
        data: {}
        target:
          device_id:
            - fe90be58cced7f98bd28b66310097b94
            - 29a333085a757dc7543fa3ed613ea110
    action_button_down_double:
      - action: script.assess_side_blinds_for_ac_on_close
        data: {}
    button_up_double_press: true
    button_down_double_press: true
    action_button_up_release: []
    action_button_down_release: []
    helper_double_press_delay: 1000
    helper_debounce_delay: 0
```

### To Reproduce

Unsure exactly how to reproduce considering one of my remotes works fine, but this happens when I press up or down on either of my other IKEA E1766 remotes. I check the trace for when my helper changes to include "open" or "close" in the trigger action and see that the automation cancels after a delay that is part of a default action within a choose action.

### Expected behavior

The automation continues after the delay.

### Actual Behaviour

The automation cancels at the delay.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

### Screenshots

I've included a screenshot of the Trace log to help show where the automation fails.
![Screenshot 2024-10-03 124326](https://github.com/user-attachments/assets/b54520a5-ae08-49d0-9b10-61f74a989350)
