### ISSUE TITLE
Bug - ZHA ikea e2002 long hold buttons presses not triggering correctly

### ISSUE THREAD

**Issue by Ivarvdb** [EPMatt/awesome-ha-blueprints#619]
### Blueprint name

ikea_e2001_e2002.yaml

### Home Assistant Core Version

2024.7.4

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Zigbee home assistant long button presses on Ikea E2002 are not registred properly and events associated with the button press are not trigged.

### Automation YAML config

```yaml
alias: Controller - IKEA E2001/E2002 STYRBAR Remote control
description: ""
use_blueprint:
  path: EPMatt/ikea_e2001_e2002.yaml
  input:
    integration: ZHA
    helper_last_controller_event: input_text.xxxxxxxxxxx
    controller_device: xxxxxxxxxxxxxx
    button_left_long_loop: true
    button_right_long_loop: true
    button_up_long_loop: true
    button_down_long_loop: true
```

### To Reproduce

1. Use the ZHA integration option
2. Add E2002 device (Firmware 0x00010024)
3. Long press any of the 4 buttons 
4. Expected automation action sequences are not triggered
5. See automation trigger trace to see that the zha codes do not match with expected codes

### Expected behavior

Long pressing any of buttons to trigger the respective action sequences

### Actual Behaviour

Long pressing any of buttons **does not** trigger the respective action sequences

### Additional Details

- [x] I'd like to help developing a fix for this issue.

### Screenshots

Left button long press:
![image](https://github.com/user-attachments/assets/cba4fe22-a67f-4913-8268-7b35551eed45)

Right button long press:
![image](https://github.com/user-attachments/assets/b177967d-958b-4a8b-b60e-83f23ddd8a6a)

Down button long press:
![image](https://github.com/user-attachments/assets/e8e85645-7ad1-4074-bf0d-22f469cfb491)

Up button long press:
![image](https://github.com/user-attachments/assets/3a7df57e-ee71-42e5-8e00-f385f3d20fac)

### Additional context

Currently working on a fix.
