### ISSUE TITLE
Bug - ZHA E2002 Long Press don't stop on release

### ISSUE THREAD

**Issue by FraBomba6** [EPMatt/awesome-ha-blueprints#621]
### Blueprint name

Controller - IKEA E2001/E2002 STYRBAR Remote control

### Home Assistant Core Version

2024.11.2

### Home Assistant Installation Type

Home Assistant Operating System

### Description

When releasing one of the buttons after a long press the brightness/color/temperature continues changing until another button is pressed or 0 brightness is reached

### Automation YAML config

```yaml
alias: Controller - Soggiorno
description: ""
use_blueprint:
  path: EPMatt/ikea_e2001_e2002.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.controller_soggiorno_action
    helper_last_controller_event: input_text.helper_controller_soggiorno
```

### To Reproduce

1. Use the ZHA integration option
2. Add E2002 device
3. Long press any of the 4 buttons

### Expected behavior

When releasing the button the change in brightness/color/temperature stops

### Actual Behaviour

When releasing the button the target parameter continues changing until another button is pressed or 0 brightness is reached

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
