### ISSUE TITLE
Bug - Double Press No Action

### ISSUE THREAD

**Issue by accordxtc** [EPMatt/awesome-ha-blueprints#664]
### Blueprint name

Controller - IKEA E1812 TRÅDFRI Shortcut button

### Home Assistant Core Version

2025.1.2

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Only double press will not work. Have tried for light device with double press to toggle light on / off which wont work. Single and long press work with no issues. 

### Automation YAML config

```yaml
alias: Mya's Shortcut Button
description: ""
use_blueprint:
  path: EPMatt/ikea_e1812.yaml
  input:
    integration: Zigbee2MQTT
    controller_entity: sensor.mya_s_button_action
    helper_last_controller_event: input_text.tradfri_shortcut_button
    action_button_short:
      - type: toggle
        device_id: e68e55f4acb30bcbbb6149402b6c2d72
        entity_id: abe63b77a2523d39af157d88c02c5804
        domain: light
    action_button_double:
      - type: toggle
        device_id: f8efceaa398bb371d88ce60abfee646d
        entity_id: a8a4f8c4eb36b912af220541bb3a94c9
        domain: light
    action_button_long:
      - action: script.kids_bedtime
        metadata: {}
        data: {}
    button_long_loop: false
    button_double_press: true
    helper_double_press_delay: 500
```

### To Reproduce

Double Tap Will Not Work

### Expected behavior

Double Tap should toggle light on / off

### Actual Behaviour

Nothing happens

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
