### ISSUE TITLE
Bug - Aqara Wireless Switch Mini No Longer Found

### ISSUE THREAD

**Issue by accordxtc** [EPMatt/awesome-ha-blueprints#686]
### Blueprint name

Controller - Xiaomi WXKG11LM Aqara Wireless Switch Mini

### Home Assistant Core Version

2025.2.3

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Blueprint update 2025.2.13 has lost the ability to see the Aqara Wireless Mini

### Automation YAML config

```yaml
description: ""
alias: Controller - Xiaomi WXKG11LM Aqara Wireless Switch Mini
use_blueprint:
  path: EPMatt/xiaomi_wxkg11lm.yaml
```

### To Reproduce

Try to add one to the blueprint

### Expected behavior

Prior to 2025.2.13, it was possible and running no problem for me. 

### Actual Behaviour

No Matching Devices Found

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
