### ISSUE TITLE
Bug - ZHA E2002 Long Press Down not releasing

### ISSUE THREAD

**Issue by kkthxbye-code** [EPMatt/awesome-ha-blueprints#698]
### Blueprint name

Controller - IKEA E2001/E2002 STYRBAR Remote control

### Home Assistant Core Version

2025.2.5

### Home Assistant Installation Type

Home Assistant Container

### Description

When using an IKEA E2002 STYRBAR with zha as the integration, the brightness down hold command does not release and keeps turning down the brightness until another button is held.

### Automation YAML config

```yaml
alias: IKEA Remote N2 1 Automation
description: ""
use_blueprint:
  path: EPMatt/ikea_e2001_e2002.yaml
  input:
    integration: ZHA
    controller_device: 3d26ff8eff16feb11377f4450d9d92ef
    helper_last_controller_event: input_text.ikea_remote_n2_1_last_controller_event
    button_up_long_loop: true
    button_right_long_loop: true
    button_left_long_loop: true
    button_down_long_loop: true
```

### To Reproduce

* Use the ZHA integration option
* Add E2002 device
* Add the light hook
* Hold the brightness down button and release

### Expected behavior

Brightness should stop turning down.

### Actual Behaviour

Brightness keeps turning down.

### Additional Details

- [x] I'd like to help developing a fix for this issue.

### Additional context

I fixed it locally by adding `stop_0_0` to button_down_release.

`      button_down_release: [stop, stop_with_on_off, stop_0_0]`

At least my controller sends stop_0_0:

```
event_type: zha_event
data:
  ...
  endpoint_id: 1
  cluster_id: 8
  command: stop
  args:
    - 0
    - 0
  params:
    options_mask: 0
    options_override: 0
origin: LOCAL
...
```
