### ISSUE TITLE
[BUG] Hook Media Player with IKEA E1743

### ISSUE THREAD

**Issue by ShagoY** [EPMatt/awesome-ha-blueprints#7]
**Bug Details**

- Blueprint name: Controller - IKEA E1743 On/Off Switch & Dimmer + Hook Media Player
- Home Assistant Core Version: 2021.3.4
- Home Assistant Installation Type:  Home Assistant OS

**Description**
When I perform an action with the mediaplayer hook to activate, I get an error in the logs and the action is not performed.
But I have a persistent notification when the action is taken.

**To Reproduce**
```
alias: Hook - Media Player - Ikea Switch
description: ''
use_blueprint:
  path: EPMatt/media_player.yaml
  input:
    controller_entity: sensor.tradfri_switch_1_action
    controller_model: IKEA E1743 On/Off Switch
    media_player: media_player.lg_webos_smart_tv
```
```
alias: Controller - IKEA E1743 On/Off Switch & Dimmer
description: ''
use_blueprint:
  path: EPMatt/ikea_e1743.yaml
  input:
    integration: Zigbee2MQTT
    zigbee2mqtt_remote: sensor.tradfri_switch_1_action
    action_up_short:
      - service: notify.persistent_notification
        data:
          message: Ikea switch - Up button - short press
    helper_last_loop_event_input: input_text.tradfri_switch
    action_up_double:
      - service: notify.persistent_notification
        data:
          message: Ikea switch - Up button - double press
    action_up_long:
      - service: notify.persistent_notification
        data:
          message: Ikea switch - Up button - long press
    action_up_release:
      - service: notify.persistent_notification
        data:
          message: Ikea switch - Up button - release after long press
    action_down_short:
      - service: notify.persistent_notification
        data:
          message: Ikea switch - Down button - short press
    action_down_double:
      - service: notify.persistent_notification
        data:
          message: Ikea switch - Down button - double press
    action_down_long:
      - service: notify.persistent_notification
        data:
          message: Ikea switch - Down button - long press
    action_down_release:
      - service: notify.persistent_notification
        data:
          message: Ikea switch - Down button - release after long press
    button_up_double_press: true
    button_down_double_press: true
```

**Additional context**
```
ERROR (MainThread) [homeassistant.components.automation.hook_media_player_ikea_switch] Error rendering variables: UndefinedError: 'dict object' has no attribute ''
```
