### ISSUE TITLE
Bug - Philips dimmer v2 restart option breaks with ZHA

### ISSUE THREAD

**Issue by mguaylam** [EPMatt/awesome-ha-blueprints#713]
### Blueprint name

Controller - Philips 929002398602 Hue Dimmer switch v2

### Home Assistant Core Version

2025.3.0

### Home Assistant Installation Type

Home Assistant Container

### Description

Since https://github.com/zigpy/zha-device-handlers/pull/2340, ZHA sends two events one right after the other and kills from time to time the current execution, killing itself the ZHA call.

It was not an issue before because there was a small delay preventing that.
We would need a solution to avoid killing the execution trying to happen.
That means we would need to filter the events we really want instead of taking everything and using `restart` at any event.

### Automation YAML config

```yaml
alias: Télécommande chambre bureau
description: ""
use_blueprint:
  path: EPMatt/philips_929002398602.yaml
  input:
    integration: ZHA
    controller_device: 8fd0ea26a00acb14a6aede353f98c83c
    helper_last_controller_event: input_text.telecommande_chambre_bureau
    action_button_on_short:
      - data: {}
        action: light.toggle
        target:
          device_id: 42ffe63edad8ebe5459e37e4f3b670d6
    action_button_on_long:
      - target:
          entity_id: scene.bonne_nuit
        metadata: {}
        action: scene.turn_on
        data: {}
    action_button_up_short:
      - data:
          transition: 0.5
          brightness_step_pct: 15
        target:
          device_id: 42ffe63edad8ebe5459e37e4f3b670d6
        action: light.turn_on
    action_button_up_long:
      - data:
          transition: 0.5
          brightness_step_pct: 15
        target:
          device_id: 42ffe63edad8ebe5459e37e4f3b670d6
        action: light.turn_on
      - delay:
          hours: 0
          minutes: 0
          seconds: 0
          milliseconds: 500
    action_button_down_short:
      - data:
          transition: 0.5
          brightness_step_pct: -15
        target:
          device_id: 42ffe63edad8ebe5459e37e4f3b670d6
        action: light.turn_on
    action_button_down_long:
      - data:
          transition: 0.5
          brightness_step_pct: -15
        target:
          device_id: 42ffe63edad8ebe5459e37e4f3b670d6
        action: light.turn_on
      - delay:
          hours: 0
          minutes: 0
          seconds: 0
          milliseconds: 500
    button_up_long_loop: true
    button_down_long_loop: true
```

### To Reproduce

1. Have the latest version of HA
2. Try to interact with the light with any command.

### Expected behavior

Light should follow the commands.

### Actual Behaviour

Some commands don't have the time to reach the network and nothing happen.

### Additional Details

- [x] I'd like to help developing a fix for this issue.

### Additional context

Here are the relevant issues :
https://github.com/home-assistant/core/issues/131694
