### ISSUE TITLE
Bug - IKEA E1812 TRÅDFRI Shortcut Button – Double Clicks Only Published as "off" Action

### ISSUE THREAD

**Issue by lgoio** [EPMatt/awesome-ha-blueprints#714]
### Blueprint name

EPMatt/ikea_e1812.yaml

### Home Assistant Core Version

2025.3.3

### Home Assistant Installation Type

Home Assistant Operating System

### Description

# IKEA E1812 TRÅDFRI Shortcut Button – Double Clicks are Now Published as "off" Action

Mappings sould be as follows:
- **action_button_long:** brightness_move_up  
- **action_button_release:** brightness_stop  
- **action_button_short:** on
- **action_button_double:** off 

**Device and Software Information:**

- **IKEA E1812 TRÅDFRI Shortcut Button**  
  - Installed Version: 604241926  
  - Firmware Version: 2.3.015 & 24.4.6  

- **Home Assistant:**  
  - Core: 2025.3.3  
  - Supervisor: 2025.03.2  
  - Operating System: 14.2  
  - Frontend: 20250109.0  

- **Zigbee2MQTT:**  
  - Version: 2.1.3-1  

- **Zigbee Coordinator:**  
  - Device: Sonoff Zigbee 3.0 USB Dongle Plus  
  - Coordinator Type: zStack3x0  
  - Coordinator Version: 20240710 (CC1352P2_CC2652P_launchpad_coordinator_20240710.zip)

**Workaround:**  
I replaced my blueprint implementation with separate automations:

```yaml
- id: "shortcut_button_action_long"
  alias: My IKEA E1812 TRÅDFRI Shortcut button long action
  description: ""
  mode: single
  triggers:
    - domain: mqtt
      device_id: my_device_id
      type: action
      subtype: "brightness_move_up"
      trigger: device
  conditions: []
  actions:
    - action: script.my_action_button_long
      metadata: {}
      data: {}
      
- id: "shortcut_button_action_long_release"
  alias: My IKEA E1812 TRÅDFRI Shortcut button long release action
  description: ""
  mode: single
  triggers:
    - domain: mqtt
      device_id: my_device_id
      type: action
      subtype: "brightness_stop"
      trigger: device
  conditions: []
  actions:
    - action: script.my_action_button_long_release
      metadata: {}
      data: {}
      
- id: "shortcut_button_action_short"
  alias: My IKEA E1812 TRÅDFRI Shortcut button short action
  description: ""
  mode: single
  triggers:
    - domain: mqtt
      device_id: my_device_id
      type: action
      subtype: "on"
      trigger: device
  conditions: []
  actions:
    - action: script.my_action_button_short
      metadata: {}
      data: {}

- id: "shortcut_button_action_double"
  alias: My IKEA E1812 TRÅDFRI Shortcut button double action
  description: ""
  mode: single
  triggers:
    - domain: mqtt
      device_id: my_device_id
      type: action
      subtype: "off"
      trigger: device
  conditions: []
  actions:
    - action: script.my_action_button_double
      metadata: {}
      data: {}
```

### Automation YAML config

```yaml
- id: "shortcut_button_actions"
  alias: My IKEA E1812 TRÅDFRI Shortcut button actions
  description: ""
  use_blueprint:
    path: EPMatt/ikea_e1812.yaml
    input:
      integration: Zigbee2MQTT
      controller_device: my_device_id
      helper_last_controller_event: input_text.my_last_event_helper
      button_double_press: true
      action_button_long:
        - action: script.my_action_button_long
          metadata: {}
          data: {}
      action_button_release:
        - action: script.my_action_button_long_release
          metadata: {}
          data: {}
      action_button_short:
        - action: script.my_action_button_short
          metadata: {}
          data: {}
      action_button_double:
        - action: script.my_action_button_double
          metadata: {}
          data: {}
```

### To Reproduce

Update Zigbee2MQTT and the E1812 TRÅDFRI Shortcut button
Test the double click

### Expected behavior

The blueprint should maps the "off" action directly to action_button_double and the "on" action directly to action_button_short. 
All helper functions, numerical values, and additional options are no longer necessary since there is no "on" action for a double click.

### Actual Behaviour

The blueprint doesn't detect a double click cause there is no on action in case of double clicks anymore. 

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
