### ISSUE TITLE
Bug - ZHA E2201 Controller: Error message

### ISSUE THREAD

**Issue by maxlk96** [EPMatt/awesome-ha-blueprints#720]
### Blueprint name

Controller - IKEA E2201 RODRET Dimmer

### Home Assistant Core Version

2025.3.3

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Hey,

First of all thanks for this amazing projekt!
I just happened to time my checking in this as the controller for IKEAs E2201 was released.

I'm using ZHA.

I am getting the following error message when trying to save an automation created from this blueprint:
`Message malformed: required key not provided @ data['actions'][0]['choose'][0]['sequence'][0]['then'][0]['choose'][0]['conditions']`

I have filled in the desired device, when saving it returns the error. 

I also use the Controller blueprint for E2001/E2002 without any issues, it does have an integration selector which this blueprint does not have, I guess that is intended(?).

### Automation YAML config

```yaml
blueprint:
  name: Controller - IKEA E2201 RODRET Dimmer
  description: "# Controller - IKEA E2201 RODRET Dimmer\n\nController automation for
    executing any kind of action triggered by the provided IKEA E2201 RODRET Dimmer.\nAllows
    to optionally loop an action on a button long press.\nAllows for Virtual Double
    Presses. Needs to be enabled in blueprint.\nSupports Zigbee2MQTT, ZHA, deCONZ.\n\nAutomations
    created with this blueprint can be connected with one or more [Hooks](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/hooks)
    supported by this controller.\nHooks allow to easily create controller-based automations
    for interacting with lights, covers, media players, and potentially more.\nSee
    the list of [Hooks available for this controller](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e2201#available-hooks)
    for additional details.\n\n## More Info\n\nℹ️ Version 2025.03.20\n\U0001F4DD [Changelog](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e2201/#changelog)\n\U0001F4D5
    Full documentation regarding this blueprint is available [here](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e2201).\n\n\U0001F680
    This blueprint is part of the **[Awesome HA Blueprints](https://epmatt.github.io/awesome-ha-blueprints)
    project**. Please consider **[leaving a star on GitHub](https://github.com/EPMatt/awesome-ha-blueprints)**!
    \U0001F31F\n"
  source_url: https://github.com/EPMatt/awesome-ha-blueprints/blob/9cfe03515ba3ddcb506cb68657efee1df1b19310/blueprints/controllers/ikea_e2201/ikea_e2201.yaml
  domain: automation
  homeassistant:
    min_version: 2024.10.0
  input:
    controller_device:
      name: (Required) (Zigbee2MQTT, ZHA, deCONZ) Controller Device
      description: The controller device to use for the automation. Choose a value
        only if the remote is integrated with Zigbee2MQTT, ZHA, deCONZ.
      default: ''
      selector:
        device:
          filter:
          - integration: mqtt
            manufacturer: IKEA
            model: RODRET wireless dimmer/power switch
          - integration: mqtt
            manufacturer: IKEA
            model: RODRET wireless dimmer/power switch (E2201)
          - integration: zha
            manufacturer: IKEA of Sweden
            model: RODRET Dimmer
          - integration: deconz
            manufacturer: IKEA of Sweden
            model: RODRET Dimmer
          multiple: false
    action_button_up_short:
      name: (Optional) Up button short press
      description: Action to run on short up button press.
      default: []
      selector:
        action: {}
    action_button_up_long:
      name: (Optional) Up button long press
      description: Action to run on long up button press.
      default: []
      selector:
        action: {}
    action_button_up_release:
      name: (Optional) Up button release
      description: Action to run on up button release after long press.
      default: []
      selector:
        action: {}
    action_button_up_double:
      name: (Optional) Up button double press
      description: Action to run on double up button press.
      default: []
      selector:
        action: {}
    action_button_down_short:
      name: (Optional) Down button short press
      description: Action to run on short down button press.
      default: []
      selector:
        action: {}
    action_button_down_long:
      name: (Optional) Down button long press
      description: Action to run on long down button press.
      default: []
      selector:
        action: {}
    action_button_down_release:
      name: (Optional) Down button release
      description: Action to run on down button release after long press.
      default: []
      selector:
        action: {}
    action_button_down_double:
      name: (Optional) Down button double press
      description: Action to run on double down button press.
      default: []
      selector:
        action: {}
    long_press_options_section:
      name: Long Press options
      icon: mdi:remote
      collapsed: true
      input:
        button_up_long_max_loop_repeats:
          name: (Optional) Up button long press - Maximum loop repeats
          description: Maximum number of repeats for the custom action, when looping
            is enabled. Use it as a safety limit to prevent an endless loop in case
            the corresponding stop event is not received.
          default: 20
          selector:
            number:
              min: 1.0
              max: 1000.0
              mode: slider
              step: 1.0
        button_down_long_max_loop_repeats:
          name: (Optional) Down button long press - Maximum loop repeats
          description: Maximum number of repeats for the custom action, when looping
            is enabled. Use it as a safety limit to prevent an endless loop in case
            the corresponding stop event is not received.
          default: 20
          selector:
            number:
              min: 1.0
              max: 1000.0
              mode: slider
              step: 1.0
        helper_long_press_delay:
          name: (Optional) Helper - Long Press delay
          description: Max delay between the pushing and releasing of a button long
            press event. Increase this value if you notice that the long press action
            is not triggered properly.
          default: 250
          selector:
            number:
              min: 100.0
              max: 5000.0
              unit_of_measurement: milliseconds
              mode: box
              step: 10.0
    double_press_options_section:
      name: Double Press options
      icon: mdi:remote
      collapsed: true
      input:
        button_up_double_press_exposed:
          name: (Optional) Expose up button double press event
          description: Choose whether or not to expose the virtual double press event
            for the up button. Turn this on if you are providing an action for the
            up button double press event.
          default: false
          selector:
            boolean: {}
        button_down_double_press_exposed:
          name: (Optional) Expose down button double press event
          description: Choose whether or not to expose the virtual double press event
            for the down button. Turn this on if you are providing an action for the
            down button double press event.
          default: false
          selector:
            boolean: {}
        helper_double_press_delay:
          name: (Optional) Helper - Double Press delay
          description: Max delay between the first and the second button press for
            the double press event. Provide a value only if you are using a double
            press action. Increase this value if you notice that the double press
            action is not triggered properly.
          default: 250
          selector:
            number:
              min: 100.0
              max: 5000.0
              unit_of_measurement: milliseconds
              mode: box
              step: 10.0
variables:
  controller_id: !input controller_device
  integration_id: '{{ trigger.id.split("-")[0] }}'
  helper_long_press_delay: !input helper_long_press_delay
  button_up_long_max_loop_repeats: !input button_up_long_max_loop_repeats
  button_down_long_max_loop_repeats: !input button_down_long_max_loop_repeats
  helper_double_press_delay: !input helper_double_press_delay
  button_up_double_press_exposed: !input button_up_double_press_exposed
  button_down_double_press_exposed: !input button_down_double_press_exposed
  actions_mapping:
    z2m:
      button_up_short:
      - 'on'
      button_up_long:
      - brightness_move_up
      button_up_release:
      - brightness_stop
      button_down_short:
      - 'off'
      button_down_long:
      - brightness_move_down
      button_down_release:
      - brightness_stop
    zha:
      button_up_short:
      - 'on'
      button_up_long:
      - move_with_on_off
      button_up_release:
      - stop_with_on_off
      button_down_short:
      - 'off'
      button_down_long:
      - move
      button_down_release:
      - stop
    dcz:
      button_up_short:
      - '1002'
      button_up_long:
      - '1001'
      button_up_release:
      - '1003'
      button_down_short:
      - '2002'
      button_down_long:
      - '2001'
      button_down_release:
      - '2003'
  button_up_short: '{{ actions_mapping[integration_id]["button_up_short"] }}'
  button_up_long: '{{ actions_mapping[integration_id]["button_up_long"] }}'
  button_up_release: '{{ actions_mapping[integration_id]["button_up_release"] }}'
  button_down_short: '{{ actions_mapping[integration_id]["button_down_short"] }}'
  button_down_long: '{{ actions_mapping[integration_id]["button_down_long"] }}'
  button_down_release: '{{ actions_mapping[integration_id]["button_down_release"]
    }}'
mode: single
max_exceeded: silent
triggers:
- trigger: device
  id: z2m-button-up-short
  domain: mqtt
  device_id: !input controller_device
  type: action
  subtype: 'on'
- trigger: device
  id: z2m-button-up-long
  domain: mqtt
  device_id: !input controller_device
  type: action
  subtype: brightness_move_up
- trigger: device
  id: z2m-button-down-short
  domain: mqtt
  device_id: !input controller_device
  type: action
  subtype: 'off'
- trigger: device
  id: z2m-button-down-long
  domain: mqtt
  device_id: !input controller_device
  type: action
  subtype: brightness_move_down
- trigger: device
  id: z2m-button-release
  domain: mqtt
  device_id: !input controller_device
  type: action
  subtype: brightness_stop
- trigger: event
  id: zha-button-up-short
  event_type: zha_event
  event_data:
    device_id: !input controller_device
    command: 'on'
    cluster_id: 6
    endpoint_id: 1
- trigger: event
  id: zha-button-up-long
  event_type: zha_event
  event_data:
    device_id: !input controller_device
    command: move_with_on_off
    cluster_id: 8
    endpoint_id: 1
    args:
    - 0
    - 83
- trigger: event
  id: zha-button-release
  event_type: zha_event
  event_data:
    device_id: !input controller_device
    command: stop_with_on_off
    cluster_id: 8
    endpoint_id: 1
- trigger: event
  id: zha-button-down-short
  event_type: zha_event
  event_data:
    device_id: !input controller_device
    command: 'off'
    cluster_id: 6
    endpoint_id: 1
- trigger: event
  id: zha-button-down-long
  event_type: zha_event
  event_data:
    device_id: !input controller_device
    command: move
    cluster_id: 8
    endpoint_id: 1
    args:
    - 1
    - 83
    - 0
    - 0
- trigger: event
  id: zha-button-release
  event_type: zha_event
  event_data:
    device_id: !input controller_device
    command: stop
    cluster_id: 8
    endpoint_id: 1
- trigger: event
  id: dcz-button-up-short
  event_type:
  - deconz_event
  event_data:
    device_id: !input controller_device
    event: '1002'
- trigger: event
  id: dcz-button-up-long
  event_type:
  - deconz_event
  event_data:
    device_id: !input controller_device
    event: '1001'
- trigger: event
  id: dcz-button-down-short
  event_type:
  - deconz_event
  event_data:
    device_id: !input controller_device
    event: '2002'
- trigger: event
  id: dcz-button-down-long
  event_type:
  - deconz_event
  event_data:
    device_id: !input controller_device
    event: '2001'
- trigger: event
  id: dcz-button-release
  event_type:
  - deconz_event
  event_data:
    device_id: !input controller_device
    event: '1003'
- trigger: event
  id: dcz-button-release
  event_type:
  - deconz_event
  event_data:
    device_id: !input controller_device
    event: '2003'
conditions:
- condition: and
  conditions:
  - '{%- set trigger_action -%} {%- if integration_id == "z2m" -%} {{ trigger.payload
    }} {%- elif integration_id == "zha" -%} {{ trigger.event.data.command }}{{"_"
    if trigger.event.data.args|length > 0}}{{ trigger.event.data.args|join("_") }}
    {%- elif integration_id == "dcz" -%} {{ trigger.event.data.event }} {%- endif
    -%} {%- endset -%} {{ trigger_action not in ["","None","unknown"] }}'
actions:
- choose:
  - conditions:
    - condition: trigger
      id:
      - z2m-button-up-short
      - zha-button-up-short
      - dcz-button-up-short
    sequence:
    - if:
      - condition: template
        value_template: '{{ button_up_double_press_exposed }}'
      then:
      - choose:
        - sequence:
          - wait_for_trigger:
            - trigger: device
              domain: mqtt
              device_id: !input controller_device
              type: action
              subtype: 'on'
            - trigger: event
              event_type: zha_event
              event_data:
                device_id: !input controller_device
                command: 'on'
                cluster_id: 6
                endpoint_id: 1
            - trigger: event
              event_type: deconz_event
              event_data:
                device_id: !input controller_device
                event: '1002'
            timeout:
              milliseconds: '{{ helper_double_press_delay }}'
            continue_on_timeout: true
          - if:
            - condition: template
              value_template: '{{ wait.trigger.idx is defined }}'
            then:
            - event: ahb_controller_event
              event_data:
                controller: '{{ controller_id }}'
                action: button_up_double
            - choose:
              - conditions: []
                sequence: !input action_button_up_double
            else:
            - event: ahb_controller_event
              event_data:
                controller: '{{ controller_id }}'
                action: button_up_short
            - choose:
              - conditions: []
                sequence: !input action_button_up_short
      else:
      - event: ahb_controller_event
        event_data:
          controller: '{{ controller_id }}'
          action: button_up_short
      - choose:
        - conditions: []
          sequence: !input action_button_up_short
  - conditions:
    - condition: trigger
      id:
      - z2m-button-down-short
      - zha-button-down-short
      - dcz-button-down-short
    sequence:
    - if:
      - condition: template
        value_template: '{{ button_down_double_press_exposed }}'
      then:
      - choose:
        - sequence:
          - wait_for_trigger:
            - trigger: device
              domain: mqtt
              device_id: !input controller_device
              type: action
              subtype: 'off'
            - trigger: event
              event_type: zha_event
              event_data:
                device_id: !input controller_device
                command: 'off'
                cluster_id: 6
                endpoint_id: 1
            - trigger: event
              event_type: deconz_event
              event_data:
                device_id: !input controller_device
                event: '2002'
            timeout:
              milliseconds: '{{ helper_double_press_delay }}'
            continue_on_timeout: true
          - if:
            - condition: template
              value_template: '{{ wait.trigger.idx is defined }}'
            then:
            - event: ahb_controller_event
              event_data:
                controller: '{{ controller_id }}'
                action: button_down_double
            - choose:
              - conditions: []
                sequence: !input action_button_down_double
            else:
            - event: ahb_controller_event
              event_data:
                controller: '{{ controller_id }}'
                action: button_down_short
            - choose:
              - conditions: []
                sequence: !input action_button_down_short
      else:
      - event: ahb_controller_event
        event_data:
          controller: '{{ controller_id }}'
          action: button_down_short
      - choose:
        - conditions: []
          sequence: !input action_button_down_short
  - conditions:
    - condition: trigger
      id:
      - z2m-button-up-long
      - zha-button-up-long
      - dcz-button-up-long
    sequence:
    - repeat:
        count: !input button_up_long_max_loop_repeats
        sequence:
        - parallel:
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_up_long
          - sequence:
            - choose:
              - conditions: []
                sequence: !input action_button_up_long
          - sequence:
            - choose:
              - sequence:
                - wait_for_trigger:
                  - trigger: device
                    domain: mqtt
                    device_id: !input controller_device
                    type: action
                    subtype: brightness_stop
                  - trigger: event
                    event_type: zha_event
                    event_data:
                      device_id: !input controller_device
                      command: stop_with_on_off
                      cluster_id: 8
                      endpoint_id: 1
                  - trigger: event
                    event_type: deconz_event
                    event_data:
                      device_id: !input controller_device
                      event: '1003'
                  timeout:
                    milliseconds: !input helper_long_press_delay
                  continue_on_timeout: true
                - if:
                  - condition: template
                    value_template: '{{ wait.trigger.idx is defined }}'
                  then:
                  - event: ahb_controller_event
                    event_data:
                      controller: '{{ controller_id }}'
                      action: button_up_release
                  - choose:
                    - conditions: []
                      sequence: !input action_button_up_release
                  - stop: button_up_released
  - conditions:
    - condition: trigger
      id:
      - z2m-button-down-long
      - zha-button-down-long
      - dcz-button-down-long
    sequence:
    - repeat:
        count: !input button_down_long_max_loop_repeats
        sequence:
        - parallel:
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_down_long
          - sequence:
            - choose:
              - conditions: []
                sequence: !input action_button_down_long
          - sequence:
            - choose:
              - sequence:
                - wait_for_trigger:
                  - trigger: device
                    domain: mqtt
                    device_id: !input controller_device
                    type: action
                    subtype: brightness_stop
                  - trigger: event
                    event_type: zha_event
                    event_data:
                      device_id: !input controller_device
                      command: stop
                      cluster_id: 8
                      endpoint_id: 1
                  - trigger: event
                    event_type: deconz_event
                    event_data:
                      device_id: !input controller_device
                      event: '2003'
                  timeout:
                    milliseconds: !input helper_long_press_delay
                  continue_on_timeout: true
                - if:
                  - condition: template
                    value_template: '{{ wait.trigger.idx is defined }}'
                  then:
                  - event: ahb_controller_event
                    event_data:
                      controller: '{{ controller_id }}'
                      action: button_down_release
                  - choose:
                    - conditions: []
                      sequence: !input action_button_down_release
                  - stop: button_down_released
  - conditions:
    - condition: trigger
      id:
      - z2m-button-release
      - zha-button-release
      - dcz-button-release
    sequence:
    - event: ahb_controller_event
      event_data:
        controller: '{{ controller_id }}'
        action: button_up_release
    - choose:
      - conditions: []
        sequence: !input action_button_up_release
  - conditions:
    - condition: trigger
      id:
      - z2m-button-release
      - zha-button-release
      - dcz-button-release
    sequence:
    - event: ahb_controller_event
      event_data:
        controller: '{{ controller_id }}'
        action: button_down_release
    - choose:
      - conditions: []
        sequence: !input action_button_down_release
```

### To Reproduce

See top description

### Expected behavior

No error?

### Actual Behaviour

Returns error, preventing me from saving an automation from the blueprint, despite having selected the device.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
