### ISSUE TITLE
Bug - Ikea Stybrar long press loop dont work Z2M

### ISSUE THREAD

**Issue by Nicop51430** [EPMatt/awesome-ha-blueprints#762]
### Blueprint name

Controller - IKEA E2001/E2002 STYRBAR Remote control

### Home Assistant Core Version

2025.4.2

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Hi, 
when I activate the "loop" option on long presses to increase or decrease the brightness, it does not work. 
The operation is not repeated.
I have to redo the operation manually on the switch.
I use Z2M in latest version 

### Automation YAML config

```yaml
alias: Interrupteur chambre Alex Nico
description: ""
use_blueprint:
  path: EPMatt/ikea_e2001_e2002.yaml
  input:
    integration: Zigbee2MQTT
    controller_device: 8613310e82fd0d91d8b4e1b41fd25556
    helper_last_controller_event: input_text.interrupteur_chambre_alex_nico
    action_button_up_short:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: 10
        target:
          entity_id: light.chambre_alex_nico
    action_button_up_long:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: 20
        target:
          entity_id: light.chambre_alex_nico
    action_button_down_short:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: -10
        target:
          entity_id: light.chambre_alex_nico
    action_button_down_long:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: -20
        target:
          entity_id: light.chambre_alex_nico
    button_up_long_loop: true
    button_down_long_loop: true
    button_up_long_max_loop_repeats: 10
    button_down_long_max_loop_repeats: 10

```

### To Reproduce

3. Trigger the automation '....'

### Expected behavior

use the "loop" function

### Actual Behaviour

The "loop" dosent work

### Additional Details

- [x] I'd like to help developing a fix for this issue.
