### ISSUE TITLE
Bug - IKEA STYRBAR E2002 blueprint stopped working after Zigbee Channel change

### ISSUE THREAD

**Issue by UnBornLord** [EPMatt/awesome-ha-blueprints#806]
### Blueprint name

Controller - IKEA E2001/E2002 STYRBAR Remote control

### Home Assistant Core Version

2025.5.2

### Home Assistant Installation Type

Home Assistant Operating System

### Description

Hi,

In my smart home I have multiple Ikea STYRBAR switches in my (HA yellow on-board, Nabu Casa Yellow v1.2) zigbee network. These worked perfect with the "Controller - IKEA E2001/E2002 STYRBAR Remote control" blueprint, in combination with "Hook - Light". I recently (had to) switch the zigbee channel and reconnected the Styrbar's (same name, entity ID, etc.). Unfortunately I cannot get them to work anymore.

I tried a complete 'blank' connection (removed the original device, complete HA reboot and connected the Styrbar again and created a Controller - IKEA E2001/E2002 STYRBAR Remote control only. Created a new helper, added one light turn on (on button up short press) and same light turn off (on button down short press). Unfortunately without any positive result.

There are 2 more things to try: reconnect Styrbar with new name / entity ID and try again (i will do that later today) and second: buy a new Styrbar and try again. This second option I have to be at an Ikea at sometime, as I will not travel to Ikea for one remote control only.

Am I doing something wrong or what am I missing here?

Thanks for your response (and hopefully I can make my children happy again, as these buttons are on their bedrooms for lights and WLED boards)

### Automation YAML config

```yaml
- id: '1747988560329'
  alias: temptemp
  description: ''
  use_blueprint:
    path: lsismeiro/ikea_e2001_e2002.yaml
    input:
      integration: ZHA
      controller_device: 05bea653914f12e12aa0b9160735008e
      helper_last_controller_event: input_text.temptemp
      action_button_up_short:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: light.bedroom_NAME_repeater_light
      action_button_down_short:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: light.bedroom_NAME_repeater_light
```

### To Reproduce

Changed zigbee chanel from 15 to 25
Lost Styrbar with "Controller - IKEA E2001/E2002 STYRBAR Remote control" function

### Expected behavior

In this simple case, turn on and off one single light
(when I run these actions in the automation the light will turn on and off)

### Actual Behaviour

Noting happens :(

Also no traces found in the Automation.
Nothing saved back to the helper (contents stays "unknown')

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
