### ISSUE TITLE
Bug - Entities not being triggered.

### ISSUE THREAD

**Issue by Suechtle** [EPMatt/awesome-ha-blueprints#812]
### Blueprint name

Controller - Philips 324131092621 Hue Dimmer switch

### Home Assistant Core Version

2025.05.3

### Home Assistant Installation Type

Home Assistant Operating System

### Description

I used the blueprint to make an automation for the Philips Hue Switch. 

The Automation is being triggered when the button is pressed. 
The Input_Text is being updated accordingly. 

The Lamp/Entity is not being triggered. 

If I add the same entity to a different Automation it gets turned  on. 

I am not sure if it is just stupidity from my side or if the blueprint is not working properly. 

### Automation YAML config

```yaml
alias: Controller - Philips 324131092621 Hue Dimmer switch
description: ""
use_blueprint:
  path: EPMatt/philips_324131092621.yaml
  input:
    integration: ZHA
    controller_device: addd577ec016f30487c7edb2cdfaa59b
    helper_last_controller_event: input_text.input_text
    action_button_on_short:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          entity_id:
            - light.schreibtisch_light_2
            - light.signify_netherlands_b_v_lst002_light_2
            - light.signify_netherlands_b_v_lst002_light_3
    action_button_off_short:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          area_id: wohnzimmer
```

### To Reproduce

1. "Install" Blueprint.
2. Use Blueprint to create an Automation. 
3. Add Lamps etc. 
4. Click on switch button

### Expected behavior

Entity should be turned on.

### Actual Behaviour

Entity is not being turned on.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
