### ISSUE TITLE
Bug - ikea -2201 RODRET

### ISSUE THREAD

**Issue by Mozartuss** [EPMatt/awesome-ha-blueprints#817]
### Blueprint name

ikea_e2201

### Home Assistant Core Version

2025.5.3

### Home Assistant Installation Type

Home Assistant Operating System

### Description

I don't know why, but now event is fired. If I trigger the actions manually, every action worked, but not if I press the button. The automation recognize input since I see a trace update, but I can't see what happens.

### Automation YAML config

```yaml
alias: Schreibtisch Schalter Automation
description: ""
use_blueprint:
  path: EPMatt/ikea_e2201.yaml
  input:
    controller_device: 24a60dc989fd48df785f445a52e726a2
    action_button_up_short:
      - type: turn_on
        device_id: 70521f41a4f7a203c819014c495726e0
        entity_id: 8f84a8df05f050b543a7533b3bfcd71d
        domain: switch
    action_button_up_long: []
    action_button_down_short:
      - type: turn_off
        device_id: 70521f41a4f7a203c819014c495726e0
        entity_id: 8f84a8df05f050b543a7533b3bfcd71d
        domain: switch
    action_button_down_long: []
    action_button_up_release:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: light.koplettwohnzimmer
    action_button_down_release:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: light.koplettwohnzimmer
```

### To Reproduce

Use this Blueprint with a new RODRET

### Expected behavior

The events should be fired

### Actual Behaviour

Nothing happens

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
