### ISSUE TITLE
Bug - I can't turn off the light

### ISSUE THREAD

**Issue by delli87** [EPMatt/awesome-ha-blueprints#821]
### Blueprint name

Hook - Light

### Home Assistant Core Version

2025.5.3

### Home Assistant Installation Type

Home Assistant Operating System

### Description

If I briefly press the 0 button, the light instead of turning off sets itself to minimum brightness.

### Automation YAML config

```yaml
alias: "Comando Luce Sala Da Pranzo "
description: ""
use_blueprint:
  path: EPMatt/light.yaml
  input:
    controller_device: b1fd58fc10ab439296b03238291c7059
    controller_model: IKEA E1743 TRÅDFRI On/Off Switch & Dimmer (#2)
    light: light.luce_sala_da_pranzo
```

### To Reproduce

Pressing the zero button

### Expected behavior

Light off

### Actual Behaviour

The light doesn't turn off but it is set to minimum.

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
