### ISSUE TITLE
Osram Switch Mini (button_center_double_press)

### ISSUE THREAD

**Issue by pex81** [EPMatt/awesome-ha-blueprints#89]
Thank you for taking the time to report here! :tada:

**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to process your request more rapidly.

This template should only be used to report a bug with a blueprint. If this is not your case, you can [choose a different issue template](https://github.com/EPMatt/awesome-ha-blueprints/issues/new/choose). If you have a question instead, please open a discussion [here](https://github.com/EPMatt/awesome-ha-blueprints/discussions/new).

\*_=required_

## Bug Details\*

- Blueprint name: Controller - Osram SMART+ Switch Mini
- Home Assistant Core Version: 2021.6.5
- Home Assistant Installation Type: Home Assistant Supervised

## Description\*

I tried the blueprint with Osram Smart + Switch Mini and it works very well, the only feature that is not right is the double middle button. I tried with 2 mini switches and it does the same thing, it doesn't perform the action.

## Automation YAML config\*

```yaml
- alias: Osram Switch Camera
  description: ''
  use_blueprint:
    path: EPMatt/osram_ac025xx00nj.yaml
    input:
      integration: ZHA
      controller_device: 329556686e830cb76d019012e8664378
      action_button_up_double:
      - type: turn_on
        device_id: fb31e5b6e32e2a33b2fe8e53614af58c
        entity_id: switch.presa_iphone
        domain: switch
      action_button_center_double:
      - type: toggle
        device_id: fb31e5b6e32e2a33b2fe8e53614af58c
        entity_id: switch.presa_iphone
        domain: switch
      action_button_down_double:
      - type: turn_off
        device_id: fb31e5b6e32e2a33b2fe8e53614af58c
        entity_id: switch.presa_iphone
        domain: switch
      button_up_double_press: true
      button_center_double_press: true
      button_down_double_press: true
      helper_last_controller_event: input_text.prova
```

## To Reproduce\*

Steps to reproduce the issue:

3. Trigger the automation '....'

## Actual Behaviour\*

The double up button works
The double down button works
The double center button does not work

Even with the same action.

## Additional Details\*

- [ ] I'd like to help developing a fix for this issue.

**Comment by alexdelprete** [comment]
Could you please post the events generated by the double-click of the center button?

You can do it by using the `developer tools` section of HA, then go to `events ` tab and in the input box of `listen to events` write `zha_event`, then click on the `start listening` button. Then double click on the center button, and you should see a series of events generated. Paste them in the reply, so @EPMatt can debug things faster. :)

![image](https://user-images.githubusercontent.com/7027842/122491874-157e6f00-cfe5-11eb-82d9-7d90f000f926.png)

**Comment by pex81** [comment]
i am testing this setup in automation.
Thanks.
```
      action_button_center_double:
      - service: switch.toggle
        data:
          entity_id: switch.presa_iphone  
```

```
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:0d:6f:00:0e:1b:79:1a",
        "unique_id": "00:0d:6f:00:0e:1b:79:1a:3:0x0008",
        "device_id": "329556686e830cb76d019012e8664378",
        "endpoint_id": 3,
        "cluster_id": 8,
        "command": "move_to_level_with_on_off",
        "args": [
            254,
            10
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2021-06-18T06:31:37.135071+00:00",
    "context": {
        "id": "f2ed8763db1bcc4817ae9befd95a83f5",
        "parent_id": null,
        "user_id": null
    }
}
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:0d:6f:00:0e:1b:79:1a",
        "unique_id": "00:0d:6f:00:0e:1b:79:1a:3:0x0008",
        "device_id": "329556686e830cb76d019012e8664378",
        "endpoint_id": 3,
        "cluster_id": 8,
        "command": "move_to_level_with_on_off",
        "args": [
            254,
            10
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2021-06-18T06:31:37.135071+00:00",
    "context": {
        "id": "f2ed8763db1bcc4817ae9befd95a83f5",
        "parent_id": null,
        "user_id": null
    }
}
```

**Comment by alexdelprete** [comment]
Grazie. ;)

Ora aspettiamo Matteo...

**Comment by EPMatt** [comment]
Ciao @pex81 @alexdelprete, sorry for the delay.
Does the single center button press work? 

You can test it with the following action config:
```yaml
action_button_center_short:
- service: switch.toggle
  data:
    entity_id: switch.presa_iphone  
```
Thanks!

...and grazie @alexdelprete for helping out with the issue. ;)
