### ISSUE TITLE
[BUG] IKEA E1744 SYMFONISK Rotary Remote

### ISSUE THREAD

**Issue by ShagoY** [EPMatt/awesome-ha-blueprints#9]
**Bug Details**

- Blueprint name: IKEA E1744 SYMFONISK Rotary Remote
- Home Assistant Core Version: 2021.3.4
- Home Assistant Installation Type: Home Assistant OS

**Description**
The "reset the text helper" part for "helper_last_controller_event" input is missing

**Additional context**
```
  # reset the text helper
  - service: 'input_text.set_value'
    data:
      entity_id: !input helper_last_controller_event
      value: ''
```
