### ISSUE TITLE
IKEA E1810 long press keeps looping with Light controller-hook

### ISSUE THREAD

**Issue by lebeno** [EPMatt/awesome-ha-blueprints#93]
Thank you for taking the time to report here! :tada:

**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to process your request more rapidly.

This template should only be used to report a bug with a blueprint. If this is not your case, you can [choose a different issue template](https://github.com/EPMatt/awesome-ha-blueprints/issues/new/choose). If you have a question instead, please open a discussion [here](https://github.com/EPMatt/awesome-ha-blueprints/discussions/new).

\*_=required_

## Bug Details\*

- Blueprint name: Hook - Light + Controller - IKEA E1524/E1810 5-Button Remote
- Home Assistant Core Version: 2021.6.5
- Home Assistant Installation: Type Home Assistant OS

## Description\*

I create an automation for an IKEA E1810 5-Button remote and use the Light hook to control an IKEA TRADFRI bulb E27 CWS opal 600lm. The automation should change hue/sat when pressing left/right and changing brightness when pressing up/down. This works, except when holding the left or right button. Even when holding for 1 second the automation does not seem to *catch* the release of the button because it keeps changing the light color enlessly. Short pressing the same button ends the loop.

## Automation YAML config\*
The automation for the controller:
```yaml
alias: IKEA RGB CWS with 5-Button Remote (TEMP)
description: ''
use_blueprint:
  path: EPMatt/ikea_e1524_e1810.yaml
  input:
    integration: ZHA
    controller_device: 2db9252e1f360e9a01449e49cd29db3d
    helper_last_controller_event: input_text.ikea_5_button_remote_1
    button_left_long_max_loop_repeats: 10
    button_right_long_max_loop_repeats: 10
    button_up_long_max_loop_repeats: 10
    button_down_long_max_loop_repeats: 10
    button_down_long_loop: true
    button_up_long_loop: true
    button_right_long_loop: true
    button_left_long_loop: true
```
The automation for the light:
```yaml
alias: Hook - Light
description: ''
use_blueprint:
  path: EPMatt/light.yaml
  input:
    light_color_mode: Hue - Saturation
    controller_device: 2db9252e1f360e9a01449e49cd29db3d
    controller_model: IKEA E1524/E1810 5-Button remote
    light: >-
      light.ikea_of_sweden_tradfri_bulb_e27_cws_opal_600lm_60ea21fe_level_light_color_on_off
    smooth_power_off: false
```

## To Reproduce\*

Steps to reproduce the issue:

1. Center press the controller to turn on the light: the light turns on
2. One of multiple short press left or right: the color changes in small steps
3. Long press left or right (1 or 2 seconds): the color keeps changing
4. Short press left or right: the color change cycle stops

## Expected behavior\*

The color should change while holding down the left or right button but should immediately stop changing when letting go of that button.

## Actual Behaviour\*

The color of the light keeps changing.

## Additional Details\*

When short pressing the right button the entity for *Helper - Last Controller Event* gets a single update:
```
{"trigger_action": "press_256_13_0", "last_triggered": "2021-06-20 09:26:55.527544+02:00"}
```
When long pressing the right button it gets two updates,
```
{"trigger_action": "hold_3328_0", "last_triggered": "2021-06-20 09:28:16.288400+02:00"}
{"trigger_action": "release_1159", "last_triggered": "2021-06-20 09:28:17.450062+02:00"}
``` 
So it looks like the release is not correctly processed by the automation?

I did try the *remove battery for a few minutes* trick, but that did not solve the behavior.
